<x-app-layout title="Create Counselling Case" :breadcrumbs="$breadcrumbs">
    <div class="mx-auto max-w-5xl space-y-5"><div class="flex items-center justify-between gap-3"><div><h1 class="text-2xl font-semibold text-slate-950">Create Counselling Case</h1><p class="text-sm text-slate-500">Assign care follow-up with due date, priority, and private notes.</p></div><a href="{{ route('counselling.index') }}" class="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700"><i data-lucide="list" class="size-4"></i>Cases</a></div>
        @if ($errors->any())<div class="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm font-medium text-rose-700">{{ $errors->first() }}</div>@endif
        <section class="dashboard-card"><form method="POST" action="{{ route('counselling.store') }}" class="grid gap-4 md:grid-cols-2">@csrf
            <label class="space-y-1 text-sm font-medium text-slate-700">Member<select name="member_id" required class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">@foreach($members as $member)<option value="{{ $member->opaqueId() }}" @selected(old('member_id') === $member->opaqueId())>{{ $member->first_name }} {{ $member->last_name }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Campus<select name="campus_id" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="">Use member campus</option>@foreach($campuses as $campus)<option value="{{ $campus->opaqueId() }}" @selected(old('campus_id') === $campus->opaqueId())>{{ $campus->name }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Assigned To<select name="assigned_user_id" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="">Unassigned</option>@foreach($users as $user)<option value="{{ $user->opaqueId() }}" @selected(old('assigned_user_id') === $user->opaqueId())>{{ $user->name }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Type<select name="type" required class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">@foreach($types as $type)<option value="{{ $type }}" @selected(old('type', 'Counseling') === $type)>{{ $type }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Priority<select name="priority" required class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">@foreach($priorities as $priority)<option value="{{ $priority }}" @selected(old('priority', 'medium') === $priority)>{{ Str::headline($priority) }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Status<select name="status" required class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">@foreach($statuses as $status)<option value="{{ $status }}" @selected(old('status', 'pending') === $status)>{{ Str::headline($status) }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Next Action<input name="next_action" value="{{ old('next_action') }}" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Due At<input name="due_at" type="datetime-local" value="{{ old('due_at') }}" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label>
            <label class="space-y-1 text-sm font-medium text-slate-700 md:col-span-2">Notes<textarea name="notes" rows="5" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">{{ old('notes') }}</textarea></label>
            <div class="md:col-span-2 flex justify-end gap-2"><a href="{{ route('counselling.index') }}" class="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700">Cancel</a><button class="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white"><i data-lucide="plus" class="size-4"></i>Create Case</button></div>
        </form></section>
    </div>
</x-app-layout>
