<x-app-layout title="Edit Counselling Case" :breadcrumbs="$breadcrumbs">
    <div class="mx-auto max-w-5xl space-y-5"><div class="flex items-center justify-between gap-3"><div><h1 class="text-2xl font-semibold text-slate-950">Edit Counselling Case</h1><p class="text-sm text-slate-500">{{ $case->member ? $case->member->first_name.' '.$case->member->last_name : 'Unknown member' }}</p></div><a href="{{ route('counselling.index') }}" class="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700"><i data-lucide="list" class="size-4"></i>Cases</a></div>
        @if ($errors->any())<div class="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm font-medium text-rose-700">{{ $errors->first() }}</div>@endif
        <section class="dashboard-card"><form method="POST" action="{{ route('counselling.update', $case) }}" class="grid gap-4 md:grid-cols-2">@csrf @method('PUT')
            <label class="space-y-1 text-sm font-medium text-slate-700">Member<select name="member_id" required class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">@foreach($members as $member)<option value="{{ $member->opaqueId() }}" @selected(old('member_id', $case->member?->opaqueId()) === $member->opaqueId())>{{ $member->first_name }} {{ $member->last_name }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Campus<select name="campus_id" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="">Use member campus</option>@foreach($campuses as $campus)<option value="{{ $campus->opaqueId() }}" @selected(old('campus_id', $case->campus?->opaqueId()) === $campus->opaqueId())>{{ $campus->name }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Assigned To<select name="assigned_user_id" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="">Unassigned</option>@foreach($users as $user)<option value="{{ $user->opaqueId() }}" @selected(old('assigned_user_id', $case->assignedUser?->opaqueId()) === $user->opaqueId())>{{ $user->name }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Type<select name="type" required class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">@foreach($types as $type)<option value="{{ $type }}" @selected(old('type', $case->type) === $type)>{{ $type }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Priority<select name="priority" required class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">@foreach($priorities as $priority)<option value="{{ $priority }}" @selected(old('priority', $case->priority) === $priority)>{{ Str::headline($priority) }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Status<select name="status" required class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">@foreach($statuses as $status)<option value="{{ $status }}" @selected(old('status', $case->status) === $status)>{{ Str::headline($status) }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Next Action<input name="next_action" value="{{ old('next_action', $case->next_action) }}" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Due At<input name="due_at" type="datetime-local" value="{{ old('due_at', $case->due_at?->format('Y-m-d\\TH:i')) }}" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label>
            <label class="space-y-1 text-sm font-medium text-slate-700 md:col-span-2">Notes<textarea name="notes" rows="5" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">{{ old('notes', $case->notes) }}</textarea></label>
            <div class="md:col-span-2 flex justify-between gap-2"><button form="delete-case" class="rounded-lg border border-rose-200 px-4 py-2.5 text-sm font-semibold text-rose-700">Archive</button><div class="flex gap-2"><a href="{{ route('counselling.index') }}" class="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700">Cancel</a><button class="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white"><i data-lucide="save" class="size-4"></i>Save Changes</button></div></div>
        </form><form id="delete-case" method="POST" action="{{ route('counselling.destroy', $case) }}" class="hidden">@csrf @method('DELETE')</form></section>
    </div>
</x-app-layout>
