<x-app-layout title="Final Attendance Record" :breadcrumbs="$breadcrumbs">
    <div class="space-y-5">
        <div class="flex items-center gap-4"><div class="grid size-14 place-items-center rounded-lg bg-violet-100 text-violet-600"><i data-lucide="badge-check" class="size-7"></i></div><div><h1 class="text-2xl font-semibold text-slate-950">Attendance Record (Final)</h1><p class="text-sm text-slate-500">{{ $attendanceSession->eventSession->title }}</p></div></div>
        <section class="grid gap-4 xl:grid-cols-[360px_1fr]">
            <aside class="rounded-lg border border-slate-200 bg-white p-5 text-center shadow-sm"><div class="mx-auto grid size-24 place-items-center rounded-full bg-violet-100 text-2xl text-violet-700">{{ $record->member ? Str::substr($record->member->first_name,0,1).Str::substr($record->member->last_name,0,1) : 'G' }}</div><h2 class="mt-4 text-xl text-slate-950">{{ $record->member?->first_name ?? 'Guest' }} {{ $record->member?->last_name }}</h2><p class="mt-1 text-sm text-slate-500">{{ $record->member?->email }}</p><span class="mt-4 inline-flex rounded-full bg-emerald-50 px-3 py-1 text-sm text-emerald-700 ring-1 ring-emerald-100">{{ Str::headline($record->status) }}</span></aside>
            <main class="space-y-4"><section class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><h2 class="mb-4 text-base text-slate-950">Summary</h2><dl class="grid gap-3 text-sm md:grid-cols-2"><div class="flex justify-between gap-4"><dt class="text-slate-500">Session</dt><dd>{{ $attendanceSession->eventSession->title }}</dd></div><div class="flex justify-between gap-4"><dt class="text-slate-500">Date</dt><dd>{{ $record->service_date?->format('M d, Y') }}</dd></div><div class="flex justify-between gap-4"><dt class="text-slate-500">Check-in Time</dt><dd>{{ $record->checked_in_at?->format('h:i A') }}</dd></div><div class="flex justify-between gap-4"><dt class="text-slate-500">Final Method</dt><dd>{{ Str::headline($record->final_method ?? 'manual') }}</dd></div><div class="flex justify-between gap-4"><dt class="text-slate-500">Verification Attempts</dt><dd>{{ $record->verifications->count() }}</dd></div><div class="flex justify-between gap-4"><dt class="text-slate-500">Policy</dt><dd>{{ Str::headline($attendanceSession->verification_policy) }}</dd></div></dl></section>
                <section class="rounded-lg border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-4"><h2 class="text-base text-slate-950">Verification Evidence</h2></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Method</th><th class="px-5 py-3">Provider</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Verified At</th><th class="px-5 py-3">Confidence</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($record->verifications as $verification)<tr><td class="px-5 py-4">{{ Str::headline($verification->method) }}</td><td class="px-5 py-4">{{ Str::headline($verification->provider ?? 'system') }}</td><td class="px-5 py-4"><span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs text-emerald-700">{{ Str::headline($verification->status) }}</span></td><td class="px-5 py-4">{{ $verification->verified_at?->format('h:i A') }}</td><td class="px-5 py-4">{{ $verification->confidence }}%</td></tr>@endforeach</tbody></table></div></section></main>
        </section>
    </div>
</x-app-layout>
