<x-app-layout title="Attendance Session" :breadcrumbs="$breadcrumbs">
    @php $enabled = $attendanceSession->methods ?? []; @endphp
    <div class="space-y-5">
        <div class="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div class="flex items-center gap-4"><div class="grid size-14 place-items-center rounded-lg bg-violet-100 text-violet-600"><i data-lucide="clipboard-check" class="size-7"></i></div><div><h1 class="text-2xl font-semibold text-slate-950">Attendance Session</h1><p class="text-sm text-slate-500">{{ $session->title }} | {{ $session->session_date->format('M d, Y') }}</p></div></div><a href="{{ route('attendance.methods', $attendanceSession) }}" class="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2.5 text-sm text-white"><i data-lucide="scan-line" class="size-4"></i>Open Check-in</a></div>
        @if(session('status'))<div class="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{{ $errors->first() }}</div>@endif
        <section class="grid gap-4 xl:grid-cols-[360px_1fr]">
            <form method="POST" action="{{ route('event-sessions.attendance.update', $session) }}" class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm">@csrf @method('PUT')
                <h2 class="mb-4 text-base text-slate-950">Attendance Session Details</h2><div class="space-y-3 text-sm"><label class="block text-slate-600">Status<select name="status" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2">@foreach(['scheduled'=>'Scheduled','open'=>'Open','closed'=>'Closed'] as $key=>$label)<option value="{{ $key }}" @selected($attendanceSession->status === $key)>{{ $label }}</option>@endforeach</select></label><label class="block text-slate-600">Verification Policy<select name="verification_policy" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2"><option value="any_one" @selected($attendanceSession->verification_policy === 'any_one')>Any One</option><option value="best_confidence" @selected($attendanceSession->verification_policy === 'best_confidence')>Best Confidence</option><option value="manual_review" @selected($attendanceSession->verification_policy === 'manual_review')>Manual Review</option></select></label><div class="grid gap-3 sm:grid-cols-2"><label class="block text-slate-600">Latitude<input name="geo_latitude" value="{{ $attendanceSession->geo_latitude }}" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2"></label><label class="block text-slate-600">Longitude<input name="geo_longitude" value="{{ $attendanceSession->geo_longitude }}" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2"></label></div><label class="block text-slate-600">Location Accuracy<input name="geo_radius_meters" type="number" min="10" value="{{ $attendanceSession->geo_radius_meters }}" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2"></label><label class="block text-slate-600">Expected Attendance<input name="expected_attendance" type="number" min="0" value="{{ $attendanceSession->expected_attendance }}" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2"></label><label class="inline-flex items-center gap-2"><input type="checkbox" name="require_authenticated" value="1" @checked($attendanceSession->require_authenticated) class="rounded border-slate-300 text-violet-600">Require authenticated user</label><label class="inline-flex items-center gap-2"><input type="checkbox" name="allow_guests" value="1" @checked($attendanceSession->allow_guests) class="rounded border-slate-300 text-violet-600">Allow guests</label></div>
                <h3 class="mb-2 mt-5 text-sm text-slate-950">Allowed Attendance Methods</h3><div class="grid gap-2 text-sm">@foreach(['manual'=>'Manual Check-in','qr'=>'QR Code','geolocation'=>'Geolocation','kiosk'=>'Kiosk','face'=>'Face Recognition','zoom'=>'Zoom','google_meet'=>'Google Meet','jitsi'=>'Jitsi Meet','livekit'=>'LiveKit'] as $method=>$label)<label class="flex items-center justify-between rounded-lg border border-slate-200 px-3 py-2"><span>{{ $label }}</span><input type="checkbox" name="methods[]" value="{{ $method }}" @checked(in_array($method, $enabled, true)) class="rounded border-slate-300 text-violet-600"></label>@endforeach</div><button class="mt-4 w-full rounded-lg bg-violet-600 px-4 py-2.5 text-sm text-white">Save Attendance Policy</button>
            </form>
            <div class="rounded-lg border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 p-4"><h2 class="text-base text-slate-950">Final Attendance Records</h2><span class="text-sm text-slate-500">{{ $records->total() }} records</span></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Member</th><th class="px-5 py-3">Final Method</th><th class="px-5 py-3">Checked In</th><th class="px-5 py-3">Evidence</th><th class="px-5 py-3 text-right">Record</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($records as $record)<tr><td class="px-5 py-4">{{ $record->member?->first_name }} {{ $record->member?->last_name }}</td><td class="px-5 py-4">{{ Str::headline($record->final_method ?? 'manual') }}</td><td class="px-5 py-4">{{ $record->checked_in_at?->format('M d, Y h:i A') }}</td><td class="px-5 py-4">{{ $record->verifications->count() }} methods</td><td class="px-5 py-4 text-right">@if($record->member)<a href="{{ route('attendance.records.show', [$attendanceSession, $record->member->opaqueId()]) }}" class="text-violet-600">View</a>@endif</td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-slate-500">No attendance records yet.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-100 p-4">{{ $records->links() }}</div></div>
        </section>
    </div>
</x-app-layout>
