@php
    $connection = $youtubeConnection;
    $lastSyncFailed = filled($connection?->last_sync_error);
    $lastTestPassed = $connection?->last_connection_test_status === 'passed';
    $lastTestFailed = $connection?->last_connection_test_status === 'failed';
@endphp

<x-app-layout title="YouTube Integration" :breadcrumbs="$breadcrumbs">
    <div class="space-y-5">
        <header class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
            <div class="flex items-center gap-4"><div class="grid size-14 place-items-center rounded-xl bg-red-50 text-red-600"><i data-lucide="youtube" class="size-7"></i></div><div><p class="text-xs font-black uppercase tracking-[.16em] text-slate-400">Administration · Integrations</p><h1 class="mt-1 text-2xl font-semibold text-slate-950">YouTube Integration</h1><p class="mt-1 max-w-3xl text-sm text-slate-500">Configure, test, and monitor the channel connection that powers your sermon library.</p></div></div>
            <div class="flex flex-wrap gap-2">
                @if ($connection)<form method="POST" action="{{ route('youtube-integration.test') }}">@csrf<button class="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700 shadow-sm transition hover:bg-slate-50"><i data-lucide="plug-zap" class="size-4 text-emerald-600"></i>Test connection</button></form>@endif
                @if ($connection && $canManageMedia)<form method="POST" action="{{ route('sermons.youtube.sync') }}">@csrf<button class="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm transition hover:bg-violet-700"><i data-lucide="refresh-cw" class="size-4"></i>Sync now</button></form>@endif
                <a href="{{ route('sermons.index') }}" class="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700 shadow-sm transition hover:bg-slate-50"><i data-lucide="arrow-left" class="size-4"></i>Sermons & Media</a>
            </div>
        </header>

        @if (session('status'))<div class="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-700"><i data-lucide="circle-check" class="mr-2 inline size-4"></i>{{ session('status') }}</div>@endif
        @if (session('error'))<div class="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm font-semibold text-rose-700"><i data-lucide="circle-alert" class="mr-2 inline size-4"></i>{{ session('error') }}</div>@endif
        @if ($errors->any())<div class="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm font-semibold text-rose-700">{{ $errors->first() }}</div>@endif

        <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <div class="dashboard-card flex items-center gap-3 p-4"><span class="grid size-10 place-items-center rounded-lg bg-red-50 text-red-600"><i data-lucide="key-round" class="size-5"></i></span><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">OAuth setup</p><p class="mt-1 text-sm font-bold {{ $youtubeCredentials ? 'text-emerald-600' : 'text-amber-600' }}">{{ $youtubeCredentials ? 'Credentials saved' : 'Needs configuration' }}</p></div></div>
            <div class="dashboard-card flex items-center gap-3 p-4"><span class="grid size-10 place-items-center rounded-lg {{ $connection ? 'bg-emerald-50 text-emerald-600' : 'bg-slate-100 text-slate-400' }}"><i data-lucide="radio" class="size-5"></i></span><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Channel</p><p class="mt-1 truncate text-sm font-bold {{ $connection ? 'text-emerald-600' : 'text-slate-500' }}">{{ $connection?->channel_title ?: 'Not connected' }}</p></div></div>
            <div class="dashboard-card flex items-center gap-3 p-4"><span class="grid size-10 place-items-center rounded-lg bg-violet-50 text-violet-600"><i data-lucide="library-big" class="size-5"></i></span><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Videos indexed</p><p class="mt-1 text-sm font-bold text-slate-700">{{ number_format($youtubeStats['total']) }}</p></div></div>
            <div class="dashboard-card flex items-center gap-3 p-4"><span class="grid size-10 place-items-center rounded-lg {{ $lastSyncFailed ? 'bg-rose-50 text-rose-600' : 'bg-blue-50 text-blue-600' }}"><i data-lucide="activity" class="size-5"></i></span><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Last sync</p><p class="mt-1 text-sm font-bold {{ $lastSyncFailed ? 'text-rose-600' : 'text-slate-700' }}">{{ $connection?->last_synced_at ? $connection->last_synced_at->diffForHumans() : 'Never' }}</p></div></div>
        </section>

        <div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]">
            <section class="dashboard-card overflow-hidden p-0">
                <div class="flex items-center justify-between border-b border-slate-100 px-5 py-4 sm:px-6"><div><h2 class="font-bold text-slate-950">Google OAuth credentials</h2><p class="mt-1 text-xs text-slate-500">Use a Google Cloud OAuth web application with YouTube Data API access.</p></div><i data-lucide="shield-check" class="size-5 text-emerald-500"></i></div>
                <form method="POST" action="{{ route('sermons.youtube.credentials.update') }}" autocomplete="off" class="space-y-5 p-5 sm:p-6">@csrf @method('PUT')<label class="block"><span class="mb-1.5 block text-xs font-bold text-slate-600">OAuth client ID</span><input name="client_id" autocomplete="off" value="{{ old('client_id', $youtubeCredentials?->client_id) }}" required class="h-11 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-900" placeholder="1234567890-abc.apps.googleusercontent.com"></label><label class="block"><span class="mb-1.5 block text-xs font-bold text-slate-600">OAuth client secret</span><input type="password" name="client_secret" autocomplete="new-password" class="h-11 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-900" placeholder="{{ $youtubeCredentials ? 'Leave blank to keep the saved secret' : 'Paste your Google client secret' }}"><span class="mt-1.5 block text-xs text-slate-400">Stored encrypted and never displayed after saving.</span></label><label class="block"><span class="mb-1.5 block text-xs font-bold text-slate-600">Authorized redirect URI</span><input type="url" name="redirect_uri" autocomplete="off" value="{{ old('redirect_uri', $youtubeCredentials?->redirect_uri ?: route('sermons.youtube.callback')) }}" required class="h-11 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-900"><span class="mt-1.5 block text-xs text-slate-400">Add this exact URL to your Google Cloud OAuth client.</span></label><div class="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-5"><p class="text-xs text-slate-500">Credentials apply to {{ $church->name }}.</p><button class="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-5 py-2.5 text-sm font-bold text-white transition hover:bg-violet-700"><i data-lucide="save" class="size-4"></i>Save credentials</button></div></form>
            </section>

            <aside class="space-y-5">
                <section class="dashboard-card p-5"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Connection health</p><h2 class="mt-2 text-lg font-bold text-slate-950">{{ $connection?->channel_title ?: 'No channel connected' }}</h2></div><span class="rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-wide {{ $connection ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500' }}">{{ $connection ? 'Connected' : 'Not connected' }}</span></div><p class="mt-3 text-sm leading-6 text-slate-500">{{ $connection?->channel_id ? 'Channel ID: '.$connection->channel_id : 'Save credentials, then connect your channel from Sermons & Media.' }}</p>@if ($connection)<div class="mt-4 border-t border-slate-100 pt-4 text-xs text-slate-500"><div class="flex justify-between gap-3"><span>Token expires</span><strong class="font-semibold text-slate-700">{{ $connection->token_expires_at?->diffForHumans() ?: 'Unknown' }}</strong></div><div class="mt-2 flex justify-between gap-3"><span>Uploads playlist</span><strong class="max-w-[170px] truncate font-semibold text-slate-700">{{ $connection->uploads_playlist_id ?: 'Pending' }}</strong></div></div>@endif</section>
                <section class="rounded-xl border border-violet-100 bg-violet-50/70 p-5"><div class="flex items-center gap-2 text-xs font-black uppercase tracking-[.14em] text-violet-700"><i data-lucide="list-checks" class="size-4"></i>Sync coverage</div><div class="mt-4 space-y-3 text-sm text-slate-600"><div class="flex items-center justify-between"><span>All channel uploads</span><strong class="text-slate-900">{{ number_format($youtubeStats['total']) }}</strong></div><div class="flex items-center justify-between"><span>Upcoming streams</span><strong class="text-slate-900">{{ number_format($youtubeStats['upcoming']) }}</strong></div><div class="flex items-center justify-between"><span>Active live streams</span><strong class="text-slate-900">{{ number_format($youtubeStats['live']) }}</strong></div><div class="flex items-center justify-between"><span>Completed live streams</span><strong class="text-slate-900">{{ number_format($youtubeStats['completed']) }}</strong></div></div></section>
            </aside>
        </div>

        <section class="dashboard-card overflow-hidden p-0">
            <div class="flex flex-col gap-2 border-b border-slate-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><h2 class="font-bold text-slate-950">Sync diagnostics</h2><p class="mt-1 text-xs text-slate-500">Operational details from the most recent synchronization and API test.</p></div>@if ($connection)<span class="inline-flex items-center gap-2 self-start rounded-full px-3 py-1.5 text-xs font-bold {{ $lastSyncFailed ? 'bg-rose-50 text-rose-700' : 'bg-emerald-50 text-emerald-700' }}"><span class="size-1.5 rounded-full {{ $lastSyncFailed ? 'bg-rose-500' : 'bg-emerald-500' }}"></span>{{ $lastSyncFailed ? 'Last sync failed' : ($connection->last_synced_at ? 'Sync completed' : 'Awaiting first sync') }}</span>@endif</div>
            @if ($connection)<div class="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4 sm:px-6"><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Started</p><p class="mt-1 text-sm font-semibold text-slate-700">{{ $connection->last_sync_started_at?->format('M j, Y · g:i A') ?: '—' }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Completed</p><p class="mt-1 text-sm font-semibold text-slate-700">{{ $connection->last_sync_completed_at?->format('M j, Y · g:i A') ?: '—' }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Checked</p><p class="mt-1 text-sm font-semibold text-slate-700">{{ $connection->last_sync_total !== null ? number_format($connection->last_sync_total).' videos' : '—' }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Duration</p><p class="mt-1 text-sm font-semibold text-slate-700">{{ $connection->last_sync_duration_ms !== null ? number_format($connection->last_sync_duration_ms).' ms' : '—' }}</p></div></div><div class="grid gap-4 border-t border-slate-100 p-5 sm:grid-cols-3 sm:px-6"><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">New imports</p><p class="mt-1 text-lg font-black text-emerald-600">{{ $connection->last_sync_imported !== null ? number_format($connection->last_sync_imported) : '—' }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Updated records</p><p class="mt-1 text-lg font-black text-violet-600">{{ $connection->last_sync_updated !== null ? number_format($connection->last_sync_updated) : '—' }}</p></div><div><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Last API test</p><p class="mt-1 text-sm font-semibold {{ $lastTestPassed ? 'text-emerald-600' : ($lastTestFailed ? 'text-rose-600' : 'text-slate-700') }}">{{ $connection->last_connection_tested_at ? $connection->last_connection_tested_at->diffForHumans() : 'Never tested' }}</p></div></div>@if ($connection->last_sync_error)<div class="border-t border-rose-100 bg-rose-50 px-5 py-4 text-sm text-rose-700 sm:px-6"><strong>Last sync error:</strong> {{ $connection->last_sync_error }}</div>@elseif ($connection->last_connection_test_message)<div class="border-t border-slate-100 px-5 py-4 text-xs text-slate-500 sm:px-6"><strong class="text-slate-700">Last API test:</strong> {{ $connection->last_connection_test_message }}</div>@endif
            @else<div class="p-10 text-center"><i data-lucide="plug-zap" class="mx-auto size-8 text-slate-300"></i><h3 class="mt-3 font-bold text-slate-900">No diagnostics yet</h3><p class="mt-1 text-sm text-slate-500">Connect a YouTube channel to start collecting sync and API health information.</p></div>@endif
        </section>
    </div>
</x-app-layout>
