<x-app-layout title="Verse Comparison" :breadcrumbs="$breadcrumbs" main-class="px-4 py-5 sm:px-6 lg:px-7">
    <div class="space-y-5">
        <header class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
            <div class="flex items-start gap-3"><span class="grid size-11 place-items-center rounded-xl bg-violet-50 text-violet-600"><i data-lucide="scale" class="size-6"></i></span><div><h1 class="text-2xl font-black text-slate-950">Verse Comparison <i data-lucide="bookmark" class="ml-1 inline size-5 text-slate-500"></i></h1><p class="mt-1 text-sm text-slate-500">Compare Bible verses across multiple translations side by side.</p></div></div>
            <div class="flex flex-wrap gap-2"><a href="{{ route('bible.search', ['q' => $book, 'tool' => 'commentaries', 'book' => $book, 'chapter' => $chapter]) }}" class="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-700"><i data-lucide="notebook-tabs" class="size-4 text-emerald-600"></i>Commentaries</a><a href="{{ route('bible.compare', ['book' => $book, 'chapter' => $chapter, 'verse' => $verse]) }}" class="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-700"><i data-lucide="command" class="size-4 text-violet-600"></i>Cross References</a><button type="button" class="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2.5 text-sm font-bold text-white"><i data-lucide="bookmark" class="size-4"></i>Save Comparison <i data-lucide="chevron-down" class="size-4"></i></button></div>
        </header>

        <div class="grid gap-4 xl:grid-cols-[minmax(0,1fr)_330px]">
            <main class="min-w-0 space-y-4">
                <form method="GET" action="{{ route('bible.compare') }}" class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
                    <div class="grid gap-3 md:grid-cols-3"><label class="text-xs font-bold text-slate-500">Book<select name="book" class="mt-1.5 h-11 w-full rounded-lg border border-slate-200 px-3 text-sm">@foreach($books as $item)<option value="{{ $item }}" @selected($book === $item)>{{ $item }}</option>@endforeach</select></label><label class="text-xs font-bold text-slate-500">Chapter<select name="chapter" class="mt-1.5 h-11 w-full rounded-lg border border-slate-200 px-3 text-sm">@foreach($chapters as $item)<option value="{{ $item }}" @selected($chapter === (int) $item)>Chapter {{ $item }}</option>@endforeach</select></label><label class="text-xs font-bold text-slate-500">Verse<input name="verse" type="number" min="1" value="{{ $verse }}" class="mt-1.5 h-11 w-full rounded-lg border border-slate-200 px-3 text-sm"></label></div>
                    <div class="mt-4 border-t border-slate-100 pt-4"><div class="flex flex-wrap items-center justify-between gap-2"><p class="text-xs font-bold text-slate-500">Translations ({{ $translations->count() }})</p><button class="rounded-lg bg-violet-600 px-4 py-2 text-xs font-bold text-white">Compare</button></div><div class="mt-3 flex flex-wrap gap-2">@foreach($translations as $translation)<label class="inline-flex cursor-pointer items-center gap-2 rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-bold text-slate-700 has-[:checked]:border-violet-300 has-[:checked]:bg-violet-50 has-[:checked]:text-violet-700"><input type="checkbox" name="versions[]" value="{{ $translation->id }}" @checked($selectedTranslationIds->isEmpty() || $selectedTranslationIds->contains($translation->id)) class="size-3.5 accent-violet-600">{{ $translation->abbreviation }}<span class="text-[10px] font-normal text-slate-400">{{ Str::limit($translation->name, 22) }}</span></label>@endforeach</div></div>
                </form>

                <section class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">@forelse($translations as $translation)<article class="flex min-h-[330px] flex-col rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between border-b border-slate-100 pb-3"><div><h2 class="font-black text-slate-950">{{ $translation->abbreviation }}</h2><p class="text-xs text-slate-500">{{ $translation->name }}</p></div><button type="button" class="text-slate-400" title="Translation options"><i data-lucide="more-horizontal" class="size-4"></i></button></div><div class="mt-5 flex flex-1 gap-3"><strong class="text-sm text-slate-700">{{ $verse }}</strong><p class="text-base leading-7 text-slate-700">{{ $verses->get($translation->id)?->text ?: 'This verse is not available in this translation yet.' }}</p></div><a href="{{ route('bible.index', ['translation' => $translation->abbreviation, 'book' => $book, 'chapter' => $chapter]) }}" class="mt-4 font-bold text-violet-700">{{ $book }} {{ $chapter }}:{{ $verse }} <i data-lucide="bookmark" class="ml-1 inline size-4"></i></a></article>@empty<div class="rounded-xl border border-dashed border-slate-300 bg-white p-8 text-sm text-slate-500 md:col-span-2 xl:col-span-4">Select at least one installed translation to compare.</div>@endforelse</section>
                <section class="rounded-xl border border-slate-200 bg-violet-50/50 p-5"><div class="flex items-start gap-3"><span class="grid size-9 place-items-center rounded-xl bg-violet-100 text-violet-600"><i data-lucide="lightbulb" class="size-5"></i></span><div><h2 class="font-black text-slate-950">About Verse Comparisons</h2><p class="mt-1 text-sm leading-6 text-slate-600">Comparing translations helps reveal nuances in the original languages and provides a richer understanding of Scripture.</p></div></div></section>
            </main>

            <aside class="space-y-4"><section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex items-center justify-between"><h2 class="text-sm font-black text-slate-950">Comparison Notes</h2><span class="text-[11px] font-bold text-violet-700">Private</span></div><textarea maxlength="500" placeholder="Add your notes about this comparison..." class="mt-3 h-28 w-full resize-none rounded-lg border border-slate-200 p-3 text-sm text-slate-700"></textarea><p class="mt-2 text-right text-[10px] text-slate-400">Your notes are private.</p></section><section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex items-center justify-between"><h2 class="text-sm font-black text-slate-950">Related Passages</h2><a href="{{ route('bible.search', ['q' => $book, 'book' => $book, 'chapter' => $chapter]) }}" class="text-[11px] font-bold text-violet-700">View all</a></div><div class="mt-3 space-y-2">@forelse($relatedVerses as $related)<a href="{{ route('bible.compare', ['book' => $book, 'chapter' => $chapter, 'verse' => $related->verse]) }}" class="flex items-start gap-2 rounded-lg p-2 hover:bg-violet-50"><i data-lucide="book-open" class="mt-0.5 size-4 shrink-0 text-violet-600"></i><span><strong class="block text-xs text-violet-700">{{ $book }} {{ $chapter }}:{{ $related->verse }}</strong><span class="text-xs text-slate-500">{{ Str::limit($related->text, 70) }}</span></span></a>@empty<p class="text-sm text-slate-500">No related passages available.</p>@endforelse</div></section><section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex items-center justify-between"><h2 class="text-sm font-black text-slate-950">Recent Comparisons</h2><span class="text-[11px] font-bold text-violet-700">{{ $book }} {{ $chapter }}:{{ $verse }}</span></div><div class="mt-3 rounded-lg bg-slate-50 p-3"><p class="text-xs font-black text-violet-700">{{ $book }} {{ $chapter }}:{{ $verse }}</p><p class="mt-1 text-xs text-slate-500">{{ $translations->pluck('abbreviation')->join(', ') }}</p></div></section></aside>
        </div>
    </div>
</x-app-layout>
