<x-app-layout title="Bible" :breadcrumbs="$breadcrumbs" main-class="px-4 py-5 sm:px-6 lg:px-7">
    <div class="space-y-4">
        <section class="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white px-5 py-4 shadow-sm lg:flex-row lg:items-center lg:justify-between">
            <div class="flex items-center gap-3"><span class="grid size-11 place-items-center rounded-xl bg-violet-100 text-violet-700"><i data-lucide="book-open" class="size-6"></i></span><div><h1 class="flex items-center gap-2 text-2xl font-black text-slate-950">Bible <i data-lucide="bookmark" class="size-5 text-slate-500"></i></h1><p class="text-sm text-slate-500">Explore, study and grow in God’s Word.</p></div></div>
            <div class="flex flex-wrap items-center gap-3"><div class="hidden items-center gap-3 rounded-lg border border-slate-200 px-4 py-2 sm:flex"><span class="grid size-8 place-items-center rounded-lg bg-violet-50 text-violet-600"><i data-lucide="sun" class="size-4"></i></span><div><p class="text-[11px] text-slate-500">Daily Verse</p><p class="text-sm font-bold text-slate-900">Philippians 4:13</p></div><i data-lucide="arrow-right" class="ml-3 size-4 text-slate-400"></i></div><div class="hidden items-center gap-3 rounded-lg border border-slate-200 px-4 py-2 sm:flex"><span class="grid size-8 place-items-center rounded-lg bg-rose-50 text-rose-500"><i data-lucide="flame" class="size-4"></i></span><div><p class="text-[11px] text-slate-500">Reading Streak</p><p class="text-sm font-bold text-slate-900">12 days</p></div><i data-lucide="arrow-right" class="ml-3 size-4 text-slate-400"></i></div><a href="{{ route('bible.plans') }}" class="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-5 py-3 text-sm font-bold text-white shadow-sm hover:bg-violet-700"><i data-lucide="calendar-days" class="size-4"></i>Start Reading Plan <i data-lucide="chevron-down" class="size-4"></i></a></div>
        </section>

        <nav class="flex gap-7 overflow-x-auto border-b border-slate-200 px-2 text-sm font-bold text-slate-500"><a href="{{ route('bible.index') }}" class="border-b-2 border-violet-600 px-1 py-3 text-violet-700">Read</a><a href="{{ route('bible.plans') }}" class="px-1 py-3 hover:text-violet-700">Plans</a><a href="{{ route('bible.bookmarks') }}" class="px-1 py-3 hover:text-violet-700">Bookmarks</a><a href="{{ route('bible.notes') }}" class="px-1 py-3 hover:text-violet-700">Notes</a><a href="{{ route('bible.highlights') }}" class="px-1 py-3 hover:text-violet-700">Highlights</a></nav>

        <div class="grid gap-3 xl:grid-cols-[minmax(0,1fr)_250px_300px]">
            <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
                <form method="GET" action="{{ route('bible.index') }}" class="grid gap-3 border-b border-slate-100 bg-white p-3 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_minmax(0,1fr)_auto] sm:items-end">
                    <label class="text-[11px] font-bold uppercase tracking-wide text-slate-500">Version<select name="translation" class="mt-1.5 h-11 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-800"><option value="">{{ $translation?->abbreviation }} — {{ $translation?->name }}</option>@foreach($translations as $item)<option value="{{ $item->abbreviation }}">{{ $item->abbreviation }} — {{ $item->name }}</option>@endforeach</select></label>
                    <label class="text-[11px] font-bold uppercase tracking-wide text-slate-500">Book<select name="book" class="mt-1.5 h-11 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-800"><option>John</option><option>Genesis</option><option>Psalms</option><option>Romans</option></select></label>
                    <label class="text-[11px] font-bold uppercase tracking-wide text-slate-500">Chapter<select name="chapter" class="mt-1.5 h-11 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-800">@for($number = 1; $number <= 50; $number++)<option value="{{ $number }}" @selected($chapter === $number)>{{ $number }}</option>@endfor</select></label>
                    <div class="flex gap-2"><button type="submit" class="grid size-11 place-items-center rounded-lg border border-slate-200 text-slate-700 hover:bg-slate-50" title="Open"><i data-lucide="search" class="size-5"></i></button><a href="{{ route('bible.settings') }}" class="grid size-11 place-items-center rounded-lg border border-slate-200 text-slate-700 hover:bg-slate-50" title="Reading settings"><i data-lucide="settings-2" class="size-5"></i></a></div>
                </form>
                <article class="p-5 sm:p-6"><div class="flex items-start justify-between"><div><p class="text-sm font-semibold text-slate-500">{{ $translation?->name }}</p><h2 class="mt-1 text-xl font-black text-slate-950">{{ $book }} {{ $chapter }}</h2><p class="mt-1 text-sm text-slate-500">{{ $translation?->name }} <span class="px-1">·</span> Chapter {{ $chapter }}</p></div><div class="flex gap-2"><button class="grid size-10 place-items-center rounded-lg border border-slate-200 text-slate-600 hover:bg-slate-50" title="Listen"><i data-lucide="volume-2" class="size-4"></i></button><button class="grid size-10 place-items-center rounded-lg border border-slate-200 text-slate-600 hover:bg-slate-50" title="More reading options"><i data-lucide="sliders-horizontal" class="size-4"></i></button></div></div><div class="mt-7 space-y-4 text-[15px] leading-7 text-slate-800">@forelse($verses as $verse)<p><sup class="mr-3 inline-block w-4 text-xs font-black text-slate-400">{{ $verse->verse }}</sup>{{ $verse->text }}</p>@empty<p class="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-6 text-sm text-slate-500">This chapter is not available in the selected translation yet. An administrator can import verse data from Bible Translations.</p>@endforelse</div><div class="mt-6 flex justify-between"><button class="grid size-9 place-items-center rounded-full border border-slate-200 text-slate-500 hover:bg-slate-50"><i data-lucide="chevron-left" class="size-4"></i></button><button class="grid size-9 place-items-center rounded-full border border-slate-200 text-slate-500 hover:bg-slate-50"><i data-lucide="chevron-right" class="size-4"></i></button></div></article>
                <div class="border-t border-slate-100 bg-gradient-to-r from-violet-50 via-white to-sky-50 p-5"><div class="flex items-start gap-3"><span class="grid size-10 place-items-center rounded-full bg-amber-100 text-amber-600"><i data-lucide="sun" class="size-5"></i></span><div><p class="text-xs font-black uppercase tracking-wide text-violet-700">Verse of the Day</p><p class="mt-1 text-base font-semibold text-slate-800">I can do all things through him who gives me strength.</p><p class="mt-1 text-xs font-bold text-violet-700">Philippians 4:13 ({{ $translation?->abbreviation }})</p></div><button class="ml-auto grid size-9 place-items-center rounded-lg border border-violet-200 text-violet-600"><i data-lucide="heart" class="size-4"></i></button></div></div>
            </section>

            <aside class="space-y-3"><section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h2 class="text-sm font-black text-slate-950">Study Tools</h2><div class="mt-2 space-y-0.5">@foreach([['share-2','Cross References','bible.compare','bg-violet-50','text-violet-600'],['message-square','Commentaries','bible.search','bg-emerald-50','text-emerald-600'],['book-open','Dictionaries','bible.search','bg-orange-50','text-orange-600'],['git-compare','Verse Comparison','bible.compare','bg-blue-50','text-blue-600'],['languages','Parallel Bible','bible.compare','bg-rose-50','text-rose-600'],['milestone','Bible Timeline','bible.search','bg-violet-50','text-violet-600'],['search','Topical Search','bible.search','bg-cyan-50','text-cyan-600']] as [$icon,$label,$route,$background,$foreground])<a href="{{ route($route) }}" class="flex items-center gap-2 rounded-lg px-1 py-2.5 text-xs font-semibold text-slate-700 hover:bg-slate-50 hover:text-violet-700"><span class="grid size-7 shrink-0 place-items-center rounded-md {{ $background }} {{ $foreground }}"><i data-lucide="{{ $icon }}" class="size-3.5"></i></span>{{ $label }}<i data-lucide="chevron-right" class="ml-auto size-3.5 text-slate-400"></i></a>@endforeach</div></section><section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h2 class="text-sm font-black text-slate-950">Quick Actions</h2><div class="mt-2 space-y-0.5">@foreach([['bookmark-plus','Add Bookmark','bible.bookmarks','text-violet-600'],['notebook-pen','Add Note','bible.notes','text-emerald-600'],['highlighter','Highlight Verse','bible.highlights','text-orange-500'],['share-2','Share Verse',null,'text-blue-600'],['copy','Copy Verse',null,'text-indigo-600'],['volume-2','Listen',null,'text-rose-500']] as [$icon,$label,$route,$foreground])@if($route)<a href="{{ route($route) }}" class="flex items-center gap-2 rounded-lg px-1 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50"><i data-lucide="{{ $icon }}" class="size-4 {{ $foreground }}"></i>{{ $label }}</a>@else<button type="button" class="flex w-full items-center gap-2 rounded-lg px-1 py-2 text-left text-xs font-semibold text-slate-700 hover:bg-slate-50"><i data-lucide="{{ $icon }}" class="size-4 {{ $foreground }}"></i>{{ $label }}</button>@endif @endforeach</div></section></aside>

            <aside class="space-y-3"><section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex items-center justify-between"><h2 class="text-sm font-black text-slate-950">My Notes</h2><a href="{{ route('bible.notes') }}" class="text-[11px] font-bold text-violet-700">View all</a></div><div class="mt-3 rounded-lg border border-slate-100 p-3"><div class="flex items-center justify-between"><h3 class="text-xs font-black text-slate-900">John 3:16</h3><span class="text-[10px] text-slate-400">Today</span></div><p class="mt-2 text-xs leading-5 text-slate-500">God’s love reminds me of His endless grace and purpose for my life.</p><i data-lucide="bookmark" class="mt-2 ml-auto block size-4 fill-amber-400 text-amber-500"></i></div></section><section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex items-center justify-between"><h2 class="text-sm font-black text-slate-950">Highlights</h2><a href="{{ route('bible.highlights') }}" class="text-[11px] font-bold text-violet-700">View all</a></div><div class="mt-3 space-y-2">@foreach([['ROMANS 8:28','And we know that in all things God works for the good of those who...','border-l-rose-400'],['PSALM 23:1','The Lord is my shepherd, I lack nothing.','border-l-emerald-400'],['PHILIPPIANS 4:6-7','Do not be anxious about anything, but in every situation, by prayer...','border-l-violet-400']] as [$reference,$text,$accent])<div class="rounded-lg border border-slate-100 border-l-4 {{ $accent }} p-3"><div class="flex justify-between text-[10px] font-bold text-slate-500"><span>{{ $reference }}</span><span>{{ $loop->first ? 'Yesterday' : 'May 24' }}</span></div><p class="mt-2 text-xs leading-5 text-slate-600">{{ $text }}</p></div>@endforeach</div></section><section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex items-center gap-2"><span class="grid size-8 place-items-center rounded-lg bg-violet-50 text-violet-600"><i data-lucide="book-open" class="size-4"></i></span><h2 class="text-sm font-black text-slate-950">Reading Plan Progress</h2></div><div class="mt-4 flex items-center justify-between text-xs"><span class="font-bold text-slate-800">Chronological Plan</span><span class="text-slate-500">32%</span></div><div class="mt-2 h-2 rounded-full bg-slate-100"><div class="h-2 w-1/3 rounded-full bg-violet-600"></div></div><div class="mt-3 flex items-center justify-between text-xs text-slate-500"><span>Day 45 of 365</span><span>12 day streak</span></div><div class="mt-4 rounded-lg bg-violet-50 p-3"><p class="text-xs font-black text-slate-900">Today’s Reading</p><p class="mt-1 text-xs text-slate-500">John 3–4, Psalm 19, Proverbs 10</p></div><a href="{{ route('bible.plans') }}" class="mt-3 block rounded-lg bg-violet-600 py-2.5 text-center text-xs font-bold text-white hover:bg-violet-700">Continue Reading</a></section></aside>
        </div>
    </div>
</x-app-layout>
