<x-app-layout title="Bible" :breadcrumbs="$breadcrumbs" main-class="px-4 py-5 sm:px-6 lg:px-7">
    <div class="space-y-4" style="font-size: {{ data_get($settings, 'font_size', 16) }}px; line-height: {{ data_get($settings, 'line_spacing', 'comfortable') === 'compact' ? '1.5' : (data_get($settings, 'line_spacing') === 'spacious' ? '2.25' : '1.75') }};">
        <section class="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white px-5 py-4 shadow-sm lg:flex-row lg:items-center lg:justify-between">
            <div class="flex items-center gap-3"><span class="grid size-11 place-items-center rounded-xl bg-violet-100 text-violet-700"><i data-lucide="book-open" class="size-6"></i></span><div><h1 class="flex items-center gap-2 text-2xl font-black text-slate-950">Bible <i data-lucide="bookmark" class="size-5"></i></h1><p class="text-sm text-slate-500">Explore, study and grow in God’s Word.</p></div></div>
            <div class="flex items-center gap-3"><a href="{{ route('bible.index', ['book' => $dailyVerse?->book, 'chapter' => $dailyVerse?->chapter]) }}" class="hidden items-center gap-3 rounded-lg border border-slate-200 px-4 py-2 sm:flex"><i data-lucide="sun" class="size-5 text-violet-600"></i><span><small class="block text-[11px] text-slate-500">Daily Verse</small><strong class="text-sm">{{ $dailyVerse ? $dailyVerse->book.' '.$dailyVerse->chapter.':'.$dailyVerse->verse : 'Not available' }}</strong></span></a><span class="hidden items-center gap-2 rounded-lg border border-slate-200 px-4 py-3 text-sm sm:flex"><i data-lucide="flame" class="size-5 text-rose-500"></i>{{ $activePlan?->users->first()?->pivot?->current_streak ?? 0 }} day streak</span><a href="{{ route('bible.plans') }}" class="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-5 py-3 text-sm font-bold text-white"><i data-lucide="calendar-days" class="size-4"></i>Reading Plans</a></div>
        </section>
        <nav class="flex gap-7 overflow-x-auto border-b border-slate-200 px-2 text-sm font-bold text-slate-500"><a href="{{ route('bible.index') }}" class="border-b-2 border-violet-600 px-1 py-3 text-violet-700">Read</a><a href="{{ route('bible.plans') }}" class="px-1 py-3">Plans</a><a href="{{ route('bible.bookmarks') }}" class="px-1 py-3">Bookmarks</a><a href="{{ route('bible.notes') }}" class="px-1 py-3">Notes</a><a href="{{ route('bible.highlights') }}" class="px-1 py-3">Highlights</a></nav>
        <div class="grid gap-3 xl:grid-cols-[minmax(0,1fr)_250px_300px]">
            <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
                <form method="GET" action="{{ route('bible.index') }}" class="grid gap-3 border-b border-slate-100 p-3 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_minmax(0,1fr)_auto]"><label class="text-[11px] font-bold uppercase text-slate-500">Version<select name="translation" class="mt-1 h-11 w-full rounded-lg border border-slate-200 px-3 text-sm">@foreach($translations as $item)<option value="{{ $item->abbreviation }}" @selected($translation?->id === $item->id)>{{ $item->abbreviation }} — {{ $item->name }}</option>@endforeach</select></label><label class="text-[11px] font-bold uppercase text-slate-500">Book<select name="book" class="mt-1 h-11 w-full rounded-lg border border-slate-200 px-3 text-sm">@foreach($books as $item)<option value="{{ $item }}" @selected($book === $item)>{{ $item }}</option>@endforeach</select></label><label class="text-[11px] font-bold uppercase text-slate-500">Chapter<select name="chapter" class="mt-1 h-11 w-full rounded-lg border border-slate-200 px-3 text-sm">@for($number = 1; $number <= 150; $number++)<option value="{{ $number }}" @selected($chapter === $number)>{{ $number }}</option>@endfor</select></label><button class="grid size-11 place-items-center self-end rounded-lg bg-violet-600 text-white" title="Open"><i data-lucide="search" class="size-5"></i></button></form>
                <article class="p-5 sm:p-6"><div class="flex items-start justify-between"><div><p class="text-sm font-semibold text-slate-500">{{ $translation?->name }}</p><h2 class="mt-1 text-xl font-black text-slate-950">{{ $book }} {{ $chapter }}</h2><p class="mt-1 text-sm text-slate-500">{{ $translation?->name }} · Chapter {{ $chapter }}</p></div><a href="{{ route('bible.settings') }}" class="grid size-10 place-items-center rounded-lg border border-slate-200"><i data-lucide="settings-2" class="size-4"></i></a></div><div class="mt-7 space-y-4 text-[15px] leading-7 text-slate-800">@forelse($verses as $verse)<p><sup class="mr-3 inline-block w-4 text-xs font-black text-slate-400">{{ $verse->verse }}</sup>{{ $verse->text }}</p>@empty<p class="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-6 text-sm text-slate-500">This chapter is not available in the selected installed translation.</p>@endforelse</div><div class="mt-6 flex justify-between"><a href="{{ route('bible.index', ['translation' => $translation?->abbreviation, 'book' => $book, 'chapter' => max(1, $chapter - 1)]) }}" class="grid size-9 place-items-center rounded-full border border-slate-200"><i data-lucide="chevron-left" class="size-4"></i></a><a href="{{ route('bible.index', ['translation' => $translation?->abbreviation, 'book' => $book, 'chapter' => $chapter + 1]) }}" class="grid size-9 place-items-center rounded-full border border-slate-200"><i data-lucide="chevron-right" class="size-4"></i></a></div></article>
                <div class="border-t border-slate-100 bg-violet-50 p-5"><p class="text-xs font-black uppercase text-violet-700">Verse of the Day</p><p class="mt-1 font-semibold text-slate-800">{{ $dailyVerse?->text ?? 'No verse is available in this translation yet.' }}</p>@if($dailyVerse)<p class="mt-1 text-xs font-bold text-violet-700">{{ $dailyVerse->book }} {{ $dailyVerse->chapter }}:{{ $dailyVerse->verse }} ({{ $translation?->abbreviation }})</p>@endif</div>
            </section>
            <aside class="space-y-3"><section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h2 class="text-sm font-black">Study Tools</h2>@foreach([['share-2','Cross References','bible.compare'],['git-compare','Verse Comparison','bible.compare'],['search','Search','bible.search']] as [$icon,$label,$route])<a href="{{ route($route) }}" class="flex items-center gap-2 py-3 text-xs font-semibold"><i data-lucide="{{ $icon }}" class="size-4 text-violet-600"></i>{{ $label }}<i data-lucide="chevron-right" class="ml-auto size-3"></i></a>@endforeach</section><section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h2 class="text-sm font-black">Quick Actions</h2>@foreach([['bookmark-plus','Add Bookmark','bible.bookmarks'],['notebook-pen','Add Note','bible.notes'],['highlighter','Highlight Verse','bible.highlights']] as [$icon,$label,$route])<a href="{{ route($route) }}" class="flex items-center gap-2 py-3 text-xs font-semibold"><i data-lucide="{{ $icon }}" class="size-4 text-violet-600"></i>{{ $label }}</a>@endforeach</section></aside>
            <aside class="space-y-3"><section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex justify-between"><h2 class="text-sm font-black">My Notes</h2><a href="{{ route('bible.notes') }}" class="text-xs font-bold text-violet-700">View all</a></div>@if($recentNote)<div class="mt-3 rounded-lg border p-3"><strong class="text-xs">{{ $recentNote->reference }}</strong><p class="mt-2 text-xs text-slate-500">{{ Str::limit(strip_tags($recentNote->body), 130) }}</p></div>@else<p class="mt-3 text-sm text-slate-500">No notes yet.</p>@endif</section><section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex justify-between"><h2 class="text-sm font-black">Highlights</h2><a href="{{ route('bible.highlights') }}" class="text-xs font-bold text-violet-700">View all</a></div><div class="mt-3 space-y-2">@forelse($recentHighlights as $highlight)<div class="rounded-lg border-l-4 border-violet-400 p-3"><strong class="text-xs">{{ $highlight->reference }}</strong><p class="mt-1 text-xs text-slate-500">{{ Str::limit($highlight->snippet, 100) }}</p></div>@empty<p class="text-sm text-slate-500">No highlights yet.</p>@endforelse</div></section><section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h2 class="text-sm font-black">Reading Plan Progress</h2>@if($activePlan)@php($pivot = $activePlan->users->first()->pivot)@php($planPercent = min(100, (int) round(($pivot->current_day / max(1, $activePlan->duration_days)) * 100)))<div class="mt-4 flex justify-between text-xs"><strong>{{ $activePlan->name }}</strong><span>{{ $planPercent }}%</span></div><div class="mt-2 h-2 rounded-full bg-slate-100"><div class="h-2 rounded-full bg-violet-600" style="width: {{ $planPercent }}%"></div></div><p class="mt-2 text-xs text-slate-500">Day {{ $pivot->current_day }} of {{ $activePlan->duration_days }} · {{ $pivot->current_streak }} day streak</p>@else<p class="mt-3 text-sm text-slate-500">No active reading plan.</p>@endif<a href="{{ route('bible.plans') }}" class="mt-3 block rounded-lg bg-violet-600 py-2.5 text-center text-xs font-bold text-white">{{ $activePlan ? 'Continue Reading' : 'Browse Reading Plans' }}</a></section></aside>
        </div>
    </div>
</x-app-layout>
