<x-app-layout title="Bible" :breadcrumbs="$breadcrumbs" main-class="px-4 py-5 sm:px-6 lg:px-7">
    <div class="space-y-4">
        <section class="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:flex-row lg:items-center lg:justify-between">
            <div class="flex items-center gap-3"><span class="grid size-12 place-items-center rounded-xl bg-violet-100 text-violet-700"><i data-lucide="book-open" class="size-6"></i></span><div><h1 class="text-2xl font-black text-slate-950">Bible</h1><p class="text-sm text-slate-500">Explore, study and grow in God’s Word.</p></div></div>
            <div class="flex flex-wrap gap-3"><div class="hidden items-center gap-3 rounded-xl border border-slate-200 px-4 py-2.5 sm:flex"><span class="grid size-8 place-items-center rounded-lg bg-violet-50 text-violet-600"><i data-lucide="sun" class="size-4"></i></span><div><p class="text-[11px] text-slate-500">Daily Verse</p><p class="text-sm font-bold text-slate-900">Philippians 4:13</p></div></div><div class="hidden items-center gap-3 rounded-xl border border-slate-200 px-4 py-2.5 sm:flex"><span class="grid size-8 place-items-center rounded-lg bg-rose-50 text-rose-500"><i data-lucide="flame" class="size-4"></i></span><div><p class="text-[11px] text-slate-500">Reading Streak</p><p class="text-sm font-bold text-slate-900">12 days</p></div></div><a href="{{ route('bible.placeholder', ['page' => 'plans']) }}" class="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-violet-700"><i data-lucide="calendar-days" class="size-4"></i>Start Reading Plan</a></div>
        </section>

        <nav class="flex gap-6 overflow-x-auto border-b border-slate-200 px-2 text-sm font-bold text-slate-500"><a href="{{ route('bible.index') }}" class="border-b-2 border-violet-600 px-1 py-3 text-violet-700">Read</a><a href="{{ route('bible.placeholder', ['page' => 'plans']) }}" class="px-1 py-3 hover:text-violet-700">Plans</a><a href="{{ route('bible.placeholder', ['page' => 'bookmarks']) }}" class="px-1 py-3 hover:text-violet-700">Bookmarks</a><a href="{{ route('bible.placeholder', ['page' => 'notes']) }}" class="px-1 py-3 hover:text-violet-700">Notes</a><a href="{{ route('bible.placeholder', ['page' => 'highlights']) }}" class="px-1 py-3 hover:text-violet-700">Highlights</a></nav>

        <div class="grid gap-4 xl:grid-cols-[minmax(0,1fr)_290px]">
            <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
                <form method="GET" action="{{ route('bible.index') }}" class="grid gap-3 border-b border-slate-100 bg-slate-50/60 p-4 sm:grid-cols-[1fr_1fr_1fr_auto]">
                    <label class="text-xs font-bold uppercase tracking-wide text-slate-500">Version<select name="translation" class="mt-1.5 h-11 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-800">@foreach($translations as $item)<option value="{{ $item->abbreviation }}" @selected($translation?->id === $item->id)>{{ $item->abbreviation }} — {{ $item->name }}</option>@endforeach</select></label>
                    <label class="text-xs font-bold uppercase tracking-wide text-slate-500">Book<select name="book" class="mt-1.5 h-11 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-800"><option>John</option><option>Genesis</option><option>Psalms</option><option>Romans</option></select></label>
                    <label class="text-xs font-bold uppercase tracking-wide text-slate-500">Chapter<select name="chapter" class="mt-1.5 h-11 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-800">@for($number = 1; $number <= 50; $number++)<option value="{{ $number }}" @selected($chapter === $number)>{{ $number }}</option>@endfor</select></label>
                    <button class="self-end rounded-lg bg-violet-600 px-4 py-3 text-sm font-bold text-white hover:bg-violet-700"><i data-lucide="search" class="mr-1 inline size-4"></i>Open</button>
                </form>
                <article class="p-6 sm:p-9"><div class="flex items-start justify-between"><div><p class="text-sm font-semibold text-slate-500">{{ $translation?->name }}</p><h2 class="mt-1 text-2xl font-black text-slate-950">{{ $book }} {{ $chapter }}</h2><p class="mt-1 text-sm text-slate-500">{{ $translation?->name }} <span class="px-1">·</span> Chapter {{ $chapter }}</p></div><div class="flex gap-2"><button class="grid size-10 place-items-center rounded-lg border border-slate-200 text-slate-600 hover:bg-slate-50" title="Listen"><i data-lucide="volume-2" class="size-4"></i></button><button class="grid size-10 place-items-center rounded-lg border border-slate-200 text-slate-600 hover:bg-slate-50" title="Reading settings"><i data-lucide="settings-2" class="size-4"></i></button></div></div><div class="mt-8 space-y-5 text-[17px] leading-8 text-slate-800">@forelse($verses as $verse)<p><sup class="mr-3 inline-block w-5 text-xs font-black text-slate-400">{{ $verse->verse }}</sup>{{ $verse->text }}</p>@empty<p class="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-6 text-sm text-slate-500">This chapter is not available in the selected translation yet. An administrator can add the translation and import its verse data.</p>@endforelse</div></article>
                <div class="border-t border-slate-100 bg-gradient-to-r from-violet-50 via-white to-sky-50 p-5"><div class="flex items-start gap-3"><span class="grid size-10 place-items-center rounded-full bg-amber-100 text-amber-600"><i data-lucide="sun" class="size-5"></i></span><div><p class="text-xs font-black uppercase tracking-wide text-violet-700">Verse of the Day</p><p class="mt-1 text-base font-semibold text-slate-800">I can do all things through Christ which strengtheneth me.</p><p class="mt-1 text-xs font-bold text-violet-700">Philippians 4:13 (KJV)</p></div></div></div>
            </section>
            <aside class="space-y-4"><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-base font-black text-slate-950">Study Tools</h2><div class="mt-3 space-y-1">@foreach([['git-compare','Verse Comparison','compare'],['search','Topical Search','search'],['languages','Parallel Bible','compare'],['bookmark','Bookmarks','bookmarks'],['notebook-pen','My Notes','notes']] as [$icon,$label,$page])<a href="{{ route('bible.placeholder', ['page' => $page]) }}" class="flex items-center gap-3 rounded-lg px-2 py-3 text-sm font-semibold text-slate-700 hover:bg-violet-50 hover:text-violet-700"><span class="grid size-8 place-items-center rounded-lg bg-violet-50 text-violet-600"><i data-lucide="{{ $icon }}" class="size-4"></i></span>{{ $label }}<i data-lucide="chevron-right" class="ml-auto size-4"></i></a>@endforeach</div></section><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-base font-black text-slate-950">Quick Actions</h2><div class="mt-3 space-y-2"><button class="flex w-full items-center gap-3 rounded-lg px-2 py-2 text-left text-sm font-semibold text-slate-700 hover:bg-slate-50"><i data-lucide="bookmark-plus" class="size-4 text-violet-600"></i>Add Bookmark</button><button class="flex w-full items-center gap-3 rounded-lg px-2 py-2 text-left text-sm font-semibold text-slate-700 hover:bg-slate-50"><i data-lucide="highlighter" class="size-4 text-amber-500"></i>Highlight Verse</button><button class="flex w-full items-center gap-3 rounded-lg px-2 py-2 text-left text-sm font-semibold text-slate-700 hover:bg-slate-50"><i data-lucide="share-2" class="size-4 text-sky-600"></i>Share Verse</button></div></section></aside>
        </div>
    </div>
</x-app-layout>
