<x-app-layout title="Bible Search" :breadcrumbs="$breadcrumbs" main-class="px-4 py-5 sm:px-6 lg:px-7">
    <div class="space-y-5">
        @include('bible._tabs')
        <div><h1 class="flex items-center gap-3 text-2xl font-black text-slate-950">Bible Search <i data-lucide="bookmark" class="size-5 text-slate-500"></i></h1><p class="mt-1 text-sm text-slate-500">Search across the Bible, notes, plans, and topics.</p></div>
        <div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]">
            <main class="min-w-0 space-y-4">
                <form method="GET" action="{{ route('bible.search') }}" class="flex gap-2"><div class="relative min-w-0 flex-1"><i data-lucide="search" class="absolute left-3 top-3.5 size-5 text-slate-500"></i><input name="q" value="{{ $query }}" autofocus class="h-12 w-full rounded-xl border-2 border-violet-500 pl-11 pr-10 text-sm font-semibold outline-none" placeholder="Search Bible, verses, topics...">@if($query)<a href="{{ route('bible.search') }}" class="absolute right-3 top-3.5 text-slate-500"><i data-lucide="x" class="size-5"></i></a>@endif</div><button class="rounded-xl bg-violet-600 px-6 text-sm font-bold text-white"><i data-lucide="search" class="mr-1 inline size-4"></i>Search</button></form>
                <form method="GET" action="{{ route('bible.search') }}" class="grid gap-2 md:grid-cols-2 xl:grid-cols-5"><input type="hidden" name="q" value="{{ $query }}"><label class="text-xs font-bold text-slate-500">Content Type<select name="content" class="mt-1 block h-10 w-full rounded-lg border border-slate-200 px-2 text-sm"><option value="">All Content</option><option value="verses" @selected($filters['content'] === 'verses')>Verses</option><option value="notes" @selected($filters['content'] === 'notes')>Notes</option></select></label><label class="text-xs font-bold text-slate-500">Translation<select name="translation_id" class="mt-1 block h-10 w-full rounded-lg border border-slate-200 px-2 text-sm"><option value="">All Translations</option>@foreach($translations as $translation)<option value="{{ $translation->id }}" @selected($filters['translation_id'] === (string) $translation->id)>{{ $translation->abbreviation }}</option>@endforeach</select></label><label class="text-xs font-bold text-slate-500">Testament<select name="testament" class="mt-1 block h-10 w-full rounded-lg border border-slate-200 px-2 text-sm"><option value="">All Testaments</option><option value="old" @selected($filters['testament'] === 'old')>Old Testament</option><option value="new" @selected($filters['testament'] === 'new')>New Testament</option></select></label><label class="text-xs font-bold text-slate-500">Book<select name="book" class="mt-1 block h-10 w-full rounded-lg border border-slate-200 px-2 text-sm"><option value="">All Books</option>@foreach($books as $book)<option value="{{ $book }}" @selected($filters['book'] === $book)>{{ $book }}</option>@endforeach</select></label><button class="mt-auto inline-flex h-10 items-center justify-center gap-2 rounded-lg border border-slate-200 text-sm font-bold text-slate-600"><i data-lucide="sliders-horizontal" class="size-4"></i>Filters</button></form>
                @if($query)
                    <div class="flex items-center gap-5 border-b border-slate-200 text-sm font-bold"><a href="{{ route('bible.search', request()->except('content') + ['q' => $query]) }}" class="border-b-2 border-violet-600 px-1 py-3 text-violet-700">All Results <span class="ml-1 rounded-full bg-violet-50 px-2 py-1 text-xs">{{ $verses->count() + $notes->count() }}</span></a><a href="{{ route('bible.search', request()->query() + ['content' => 'verses']) }}" class="px-1 py-3 text-slate-500">Verses <span class="ml-1 rounded-full bg-slate-100 px-2 py-1 text-xs">{{ $verses->count() }}</span></a><a href="{{ route('bible.search', request()->query() + ['content' => 'notes']) }}" class="px-1 py-3 text-slate-500">Notes <span class="ml-1 rounded-full bg-slate-100 px-2 py-1 text-xs">{{ $notes->count() }}</span></a><span class="ml-auto hidden text-xs font-normal text-slate-500 sm:inline">Sort by: <strong class="text-slate-700">Relevance</strong>⌄</span></div>
                    <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 p-4"><h2 class="flex items-center gap-2 font-black text-slate-950"><span class="grid size-7 place-items-center rounded-md bg-violet-50 text-violet-600"><i data-lucide="book-open" class="size-4"></i></span>Verses ({{ $verses->count() }})</h2><span class="text-xs font-bold text-violet-700">View all verses</span></div>@forelse($verses->take(3) as $verse)<article class="grid gap-3 border-b border-slate-100 p-4 lg:grid-cols-[105px_1fr_300px]"><div><h3 class="font-black text-violet-700">{{ $verse->book }} {{ $verse->chapter }}:{{ $verse->verse }}</h3><span class="mt-2 inline-block rounded bg-slate-100 px-2 py-1 text-xs font-bold text-slate-600">{{ $verse->translation?->abbreviation }}</span></div><p class="text-sm leading-6 text-slate-700">{{ Str::limit($verse->text, 190) }}</p><div class="flex items-center justify-between text-center text-[10px] font-semibold text-slate-600"><a href="{{ route('bible.index', ['book' => $verse->book, 'chapter' => $verse->chapter]) }}"><i data-lucide="book-open" class="mx-auto size-4"></i>Open</a><a href="{{ route('bible.bookmarks') }}"><i data-lucide="bookmark" class="mx-auto size-4"></i>Bookmark</a><a href="{{ route('bible.notes') }}"><i data-lucide="notebook-pen" class="mx-auto size-4"></i>Note</a><a href="{{ route('bible.highlights') }}"><i data-lucide="highlighter" class="mx-auto size-4 text-orange-500"></i>Highlight</a><a href="{{ route('bible.compare', ['book' => $verse->book, 'chapter' => $verse->chapter, 'verse' => $verse->verse]) }}"><i data-lucide="scale" class="mx-auto size-4"></i>Compare</a></div></article>@empty<div class="p-8 text-sm text-slate-500">No verses matched your search.</div>@endforelse</section>
                    <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 p-4"><h2 class="flex items-center gap-2 font-black text-slate-950"><span class="grid size-7 place-items-center rounded-md bg-emerald-50 text-emerald-600"><i data-lucide="notebook-pen" class="size-4"></i></span>Notes ({{ $notes->count() }})</h2><a href="{{ route('bible.notes') }}" class="text-xs font-bold text-violet-700">View all notes</a></div>@forelse($notes->take(3) as $note)<article class="flex items-center gap-4 border-b border-slate-100 p-4"><div class="min-w-0 flex-1"><h3 class="font-black text-slate-900">{{ $note->title }}</h3><p class="text-xs text-slate-500">{{ $note->reference }}</p></div><p class="hidden flex-1 text-sm text-slate-500 md:block">{{ Str::limit(strip_tags($note->body), 100) }}</p><a href="{{ route('bible.notes', ['selected' => $note->id]) }}" class="rounded-lg bg-violet-50 px-3 py-2 text-xs font-bold text-violet-700">Open</a></article>@empty<div class="p-8 text-sm text-slate-500">No notes matched your search.</div>@endforelse</section>
                @else
                    <section class="grid min-h-[420px] place-items-center rounded-xl border border-slate-200 bg-white p-8 text-center shadow-sm"><div><span class="mx-auto grid size-14 place-items-center rounded-2xl bg-violet-100 text-violet-700"><i data-lucide="search" class="size-7"></i></span><h2 class="mt-4 font-black text-slate-950">Search the Word</h2><p class="mt-1 text-sm text-slate-500">Try a word such as “love”, “faith”, or “strength”.</p></div></section>
                @endif
            </main>
            <aside class="space-y-4"><section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex items-center justify-between"><h2 class="font-black text-slate-950">Popular Topics</h2><a href="{{ route('bible.search') }}" class="text-xs font-bold text-violet-700">View all</a></div><div class="mt-3 space-y-2">@foreach([['God’s Love', '248'], ['Love and Relationships', '186'], ['Love in Action', '124'], ['Unfailing Love', '98'], ['Agape Love', '76']] as [$topic, $count])<a href="{{ route('bible.search', ['q' => $topic]) }}" class="flex items-center gap-2 text-sm text-slate-700"><span class="grid size-6 place-items-center rounded-md bg-violet-50 text-violet-600">#</span>{{ $topic }}<span class="ml-auto text-xs text-slate-500">{{ $count }}</span></a>@endforeach</div></section><section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex items-center justify-between"><h2 class="font-black text-slate-950">Recent Searches</h2><button type="button" class="text-xs font-bold text-violet-700">Clear all</button></div><div class="mt-3 space-y-3">@forelse($recentSearches as $recent)<a href="{{ route('bible.search', ['q' => $recent]) }}" class="flex items-start gap-2 text-sm text-slate-700"><i data-lucide="history" class="mt-0.5 size-4 text-slate-400"></i><span>{{ $recent }}<small class="block text-xs text-slate-400">Recent search</small></span><i data-lucide="x" class="ml-auto size-3 text-slate-400"></i></a>@empty<p class="text-sm text-slate-500">Your recent searches will appear here.</p>@endforelse</div></section><section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h2 class="font-black text-slate-950">Search Statistics</h2><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between"><dt class="text-slate-500">Total Results</dt><dd class="font-black text-slate-800">{{ $verses->count() + $notes->count() }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">Verses Found</dt><dd class="font-black text-slate-800">{{ $verses->count() }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">Notes Found</dt><dd class="font-black text-slate-800">{{ $notes->count() }}</dd></div></dl><div class="mt-4 rounded-lg bg-violet-50 p-3 text-xs text-violet-800"><i data-lucide="chart-no-axes-column-increasing" class="mr-1 inline size-4"></i>Search results update as you refine your filters.</div></section></aside>
        </div>
    </div>
</x-app-layout>
