<x-app-layout title="Delivery Logs" :breadcrumbs="$breadcrumbs">
    @php
        $cards = [
            ['label' => 'Total Delivery Attempts', 'value' => $stats['total'], 'icon' => 'send', 'tone' => 'bg-blue-50 text-blue-600 ring-blue-100'],
            ['label' => 'Successful Deliveries', 'value' => $stats['delivered'], 'icon' => 'shield-check', 'tone' => 'bg-emerald-50 text-emerald-600 ring-emerald-100'],
            ['label' => 'Failed Deliveries', 'value' => $stats['failed'], 'icon' => 'triangle-alert', 'tone' => 'bg-rose-50 text-rose-600 ring-rose-100'],
            ['label' => 'Retry Queue Size', 'value' => $stats['retry_queue'], 'icon' => 'refresh-cw', 'tone' => 'bg-orange-50 text-orange-600 ring-orange-100'],
            ['label' => 'Average Send Time', 'value' => $stats['avg_latency'].'ms', 'icon' => 'clock', 'tone' => 'bg-violet-50 text-violet-600 ring-violet-100'],
            ['label' => 'Provider Messages', 'value' => $stats['webhooks'], 'icon' => 'link', 'tone' => 'bg-cyan-50 text-cyan-600 ring-cyan-100'],
        ];
    @endphp
    <div class="space-y-5">
        <div class="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><h1 class="text-2xl font-semibold text-slate-950">Delivery Logs & Retry Handling</h1><p class="text-sm text-slate-500">Monitor delivery status, retry failures, and track communication events across channels and providers.</p></div><div class="flex gap-2"><a href="{{ route('communications.delivery-logs.export') }}" class="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm text-slate-700"><i data-lucide="download" class="size-4"></i>Download Logs</a><a href="{{ route('communications.integrations') }}" class="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2.5 text-sm text-white"><i data-lucide="settings" class="size-4"></i>Provider Diagnostics</a></div></div>
        @include('communications.partials.flash')
        @include('communications.partials.subnav')
        <section class="grid gap-4 md:grid-cols-2 xl:grid-cols-6">@foreach($cards as $card)<article class="dashboard-card"><div class="flex items-center gap-3"><span class="grid size-11 place-items-center rounded-lg ring-1 {{ $card['tone'] }}"><i data-lucide="{{ $card['icon'] }}" class="size-5"></i></span><div><div class="text-xs text-slate-500">{{ $card['label'] }}</div><div class="mt-1 text-2xl text-slate-950">{{ is_numeric($card['value']) ? number_format($card['value']) : $card['value'] }}</div></div></div></article>@endforeach</section>
        <form method="GET" class="rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><div class="grid gap-3 lg:grid-cols-[180px_180px_180px_1fr_auto] lg:items-end"><label class="text-sm text-slate-600">Channel<select name="channel" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5"><option value="">All Channels</option>@foreach($channels as $key=>$channel)<option value="{{ $key }}" @selected(request('channel') === $key)>{{ $channel['label'] }}</option>@endforeach</select></label><label class="text-sm text-slate-600">Provider<input name="provider" value="{{ request('provider') }}" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5"></label><label class="text-sm text-slate-600">Status<select name="status" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5"><option value="">All Statuses</option>@foreach(['queued','delivered','failed'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ Str::headline($status) }}</option>@endforeach</select></label><div></div><button class="rounded-lg bg-violet-600 px-4 py-2.5 text-sm text-white">Apply Filters</button></div></form>
        <section class="rounded-lg border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 p-4"><h2 class="text-base font-semibold text-slate-950">Delivery Attempts</h2><span class="text-sm text-slate-500">{{ number_format($deliveries->total()) }} results</span></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Timestamp</th><th class="px-5 py-3">Recipient</th><th class="px-5 py-3">Channel</th><th class="px-5 py-3">Provider</th><th class="px-5 py-3">Template</th><th class="px-5 py-3">Attempt</th><th class="px-5 py-3">Response</th><th class="px-5 py-3">Final Status</th><th class="px-5 py-3 text-right">Retry Action</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($deliveries as $delivery)<tr><td class="px-5 py-4">{{ $delivery->created_at?->format('M d, Y h:i A') }}</td><td class="px-5 py-4"><div class="font-medium text-slate-950">{{ $delivery->recipient_name }}</div><div class="text-xs text-slate-500">{{ $delivery->recipient_contact }}</div></td><td class="px-5 py-4">@include('communications.partials.channel-chips', ['selected' => [$delivery->channel], 'channels' => $channels])</td><td class="px-5 py-4">{{ $delivery->provider }}</td><td class="px-5 py-4">{{ $delivery->template?->name ?? $delivery->campaign?->name ?? 'Direct message' }}</td><td class="px-5 py-4">{{ $delivery->attempt }}</td><td class="px-5 py-4">{{ $delivery->response_code ?? $delivery->error ?? '-' }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs {{ $delivery->status === 'delivered' ? 'bg-emerald-50 text-emerald-700' : ($delivery->status === 'failed' ? 'bg-rose-50 text-rose-700' : 'bg-orange-50 text-orange-700') }}">{{ Str::headline($delivery->status) }}</span></td><td class="px-5 py-4 text-right">@if($delivery->status === 'failed')<form method="POST" action="{{ route('communications.delivery-logs.retry', $delivery) }}">@csrf<button class="rounded-lg bg-violet-50 px-3 py-2 text-xs text-violet-700">Retry</button></form>@else<span class="text-slate-400">-</span>@endif</td></tr>@empty<tr><td colspan="9" class="px-5 py-12 text-center"><x-empty-state icon="clipboard-list" title="No delivery attempts" message="Sent campaigns and provider tests create auditable delivery records." /></td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-100 p-4">{{ $deliveries->links() }}</div></section>
        <section class="grid gap-4 xl:grid-cols-3"><article class="dashboard-card"><h2 class="text-base font-semibold text-slate-950">Failed Reason Breakdown</h2><div class="mt-4 space-y-2 text-sm">@forelse($failedReasons as $reason)<div class="flex justify-between"><span class="truncate">{{ $reason->reason }}</span><span>{{ number_format($reason->total) }}</span></div>@empty<p class="text-slate-500">No failed deliveries.</p>@endforelse</div></article><article class="dashboard-card"><h2 class="text-base font-semibold text-slate-950">Provider Health</h2><div class="mt-4 space-y-2 text-sm">@foreach($providerHealth as $provider)<div class="flex justify-between"><span>{{ $provider['provider'] }}</span><span class="{{ $provider['rate'] >= 95 ? 'text-emerald-600' : 'text-orange-600' }}">{{ $provider['rate'] }}%</span></div>@endforeach</div></article><article class="dashboard-card"><h2 class="text-base font-semibold text-slate-950">Communication History Summary</h2><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between"><dt class="text-slate-500">Delivery Rate</dt><dd>{{ $stats['delivery_rate'] }}%</dd></div><div class="flex justify-between"><dt class="text-slate-500">Retry Queue</dt><dd>{{ number_format($stats['retry_queue']) }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">Failed</dt><dd>{{ number_format($stats['failed']) }}</dd></div></dl></article></section>
    </div>
</x-app-layout>
