<x-app-layout title="Notification Preferences" :breadcrumbs="$breadcrumbs">
    @php
        $cards = [
            ['label' => 'Users with Custom Preferences', 'value' => $stats['custom'], 'icon' => 'user-round-cog', 'tone' => 'bg-violet-50 text-violet-600 ring-violet-100'],
            ['label' => 'Default Policy Coverage', 'value' => $stats['coverage'], 'icon' => 'shield-check', 'tone' => 'bg-emerald-50 text-emerald-600 ring-emerald-100'],
            ['label' => 'Opted-Out Users', 'value' => $stats['opted_out'], 'icon' => 'bell-off', 'tone' => 'bg-rose-50 text-rose-600 ring-rose-100'],
            ['label' => 'Push-Enabled Devices', 'value' => $stats['push'], 'icon' => 'monitor', 'tone' => 'bg-blue-50 text-blue-600 ring-blue-100'],
            ['label' => 'Quiet Hours Enabled', 'value' => $stats['quiet'], 'icon' => 'clock', 'tone' => 'bg-violet-50 text-violet-600 ring-violet-100'],
            ['label' => 'Digest Subscribers', 'value' => $stats['digest'], 'icon' => 'mail', 'tone' => 'bg-cyan-50 text-cyan-600 ring-cyan-100'],
        ];
        $selectedPerson = $selected?->member ?: $selected?->user;
    @endphp
    <div class="space-y-5">
        <div class="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><h1 class="text-2xl font-semibold text-slate-950">User Notification Preferences</h1><p class="text-sm text-slate-500">Manage how users receive notifications across channels, quiet hours, digest mode, and consent.</p></div><a href="{{ route('communications.delivery-logs.export') }}" class="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm text-slate-700"><i data-lucide="download" class="size-4"></i>Export Report</a></div>
        @include('communications.partials.flash')
        @include('communications.partials.subnav')
        <section class="grid gap-4 md:grid-cols-2 xl:grid-cols-6">@foreach($cards as $card)<article class="dashboard-card"><div class="flex items-center gap-3"><span class="grid size-11 place-items-center rounded-lg ring-1 {{ $card['tone'] }}"><i data-lucide="{{ $card['icon'] }}" class="size-5"></i></span><div><div class="text-xs text-slate-500">{{ $card['label'] }}</div><div class="mt-1 text-2xl text-slate-950">{{ number_format($card['value']) }}</div></div></div></article>@endforeach</section>
        <form method="GET" class="rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><div class="grid gap-3 lg:grid-cols-[1fr_180px_180px_auto] lg:items-end"><label class="text-sm text-slate-600">Search<input name="q" value="{{ request('q') }}" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5" placeholder="Search by name, email, or member ID..."></label><label class="text-sm text-slate-600">Campus<select name="campus" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5"><option value="">All Campuses</option>@foreach($campuses as $campus)<option value="{{ $campus->id }}" @selected(request('campus') == $campus->id)>{{ $campus->name }}</option>@endforeach</select></label><label class="text-sm text-slate-600">Status<select name="status" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5"><option value="">All</option><option value="active" @selected(request('status') === 'active')>Active</option><option value="opted_out" @selected(request('status') === 'opted_out')>Opted Out</option></select></label><button class="rounded-lg bg-violet-600 px-4 py-2.5 text-sm text-white">Apply Filters</button></div></form>
        <section class="grid gap-4 xl:grid-cols-[1fr_360px]">
            <main class="rounded-lg border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 p-4"><h2 class="text-base font-semibold text-slate-950">Preference Directory</h2><span class="text-sm text-slate-500">{{ number_format($preferences->total()) }} users</span></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3"></th><th class="px-5 py-3">Member</th><th class="px-5 py-3">Campus</th><th class="px-5 py-3">Preferred Channels</th><th class="px-5 py-3">Critical Alerts</th><th class="px-5 py-3">Digest Mode</th><th class="px-5 py-3">Quiet Hours</th><th class="px-5 py-3">Language</th><th class="px-5 py-3">Status</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($preferences as $preference)@php($person = $preference->member ?: $preference->user)<tr><td class="px-5 py-4"><input type="checkbox" class="rounded border-slate-300 text-violet-600"></td><td class="px-5 py-4"><div class="font-medium text-slate-950">{{ $person instanceof \App\Models\Member ? trim($person->first_name.' '.$person->last_name) : $person?->name }}</div><div class="text-xs text-slate-500">{{ $person?->email }}</div></td><td class="px-5 py-4">{{ $preference->member?->campus?->name ?? $preference->user?->campus?->name ?? 'All campuses' }}</td><td class="px-5 py-4">@include('communications.partials.channel-chips', ['selected' => $preference->channels ?? [], 'channels' => $channels])</td><td class="px-5 py-4">{{ $preference->critical_alerts ? 'On' : 'Off' }}</td><td class="px-5 py-4">{{ Str::headline($preference->digest_mode) }}</td><td class="px-5 py-4">{{ $preference->quiet_hours_start ? substr((string) $preference->quiet_hours_start, 0, 5).' - '.substr((string) $preference->quiet_hours_end, 0, 5) : '-' }}</td><td class="px-5 py-4">{{ strtoupper($preference->language) }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs {{ $preference->opted_out_at ? 'bg-rose-50 text-rose-700' : 'bg-emerald-50 text-emerald-700' }}">{{ $preference->opted_out_at ? 'Opted Out' : 'Active' }}</span></td></tr>@empty<tr><td colspan="9" class="px-5 py-12 text-center"><x-empty-state icon="sliders-horizontal" title="No preferences found" message="Member communication preferences are synced from real member profiles." /></td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-100 p-4">{{ $preferences->links() }}</div></main>
            <aside class="space-y-4">
                <form method="POST" action="{{ $selected ? route('communications.preferences.update', $selected) : '#' }}" class="dashboard-card">
                    @csrf @method('PUT')
                    <h2 class="text-base font-semibold text-slate-950">{{ $selectedPerson instanceof \App\Models\Member ? trim($selectedPerson->first_name.' '.$selectedPerson->last_name) : ($selectedPerson?->name ?? 'Selected User') }}</h2>
                    <p class="mt-1 text-sm text-slate-500">{{ $selectedPerson?->email ?? 'No preference selected' }}</p>
                    <div class="mt-4 space-y-4 text-sm">
                        <div><div class="mb-2 text-slate-600">Channels</div><div class="grid gap-2">@foreach($channels as $key => $channel)<label class="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2"><span class="inline-flex items-center gap-2"><i data-lucide="{{ $channel['icon'] }}" class="size-4 text-violet-600"></i>{{ $channel['label'] }}</span><input type="checkbox" name="channels[]" value="{{ $key }}" @checked(in_array($key, $selected?->channels ?? [], true)) class="rounded border-slate-300 text-violet-600"></label>@endforeach</div></div>
                        <div><div class="mb-2 text-slate-600">Categories</div><div class="grid gap-2">@foreach($categories as $category)<label class="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2">{{ Str::headline($category) }}<input type="checkbox" name="categories[]" value="{{ $category }}" @checked(in_array($category, $selected?->categories ?? [], true)) class="rounded border-slate-300 text-violet-600"></label>@endforeach</div></div>
                        <div class="grid gap-3 sm:grid-cols-2"><label class="text-slate-600">Digest<select name="digest_mode" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5">@foreach(['instant','daily','weekly','off'] as $mode)<option value="{{ $mode }}" @selected(($selected?->digest_mode ?? 'instant') === $mode)>{{ Str::headline($mode) }}</option>@endforeach</select></label><label class="text-slate-600">Language<input name="language" value="{{ $selected?->language ?? 'en' }}" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5"></label></div>
                        <div class="grid gap-3 sm:grid-cols-2"><label class="text-slate-600">Quiet Start<input name="quiet_hours_start" value="{{ $selected?->quiet_hours_start ? substr((string) $selected->quiet_hours_start, 0, 5) : '22:00' }}" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5"></label><label class="text-slate-600">Quiet End<input name="quiet_hours_end" value="{{ $selected?->quiet_hours_end ? substr((string) $selected->quiet_hours_end, 0, 5) : '06:00' }}" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5"></label></div>
                        <label class="flex items-center justify-between rounded-lg border border-slate-200 px-3 py-2.5">Critical Alerts<input type="checkbox" name="critical_alerts" value="1" @checked($selected?->critical_alerts ?? true) class="rounded border-slate-300 text-violet-600"></label>
                        <label class="flex items-center justify-between rounded-lg border border-slate-200 px-3 py-2.5">Opted Out<input type="checkbox" name="opted_out" value="1" @checked((bool) $selected?->opted_out_at) class="rounded border-slate-300 text-violet-600"></label>
                    </div>
                    <button @disabled(! $selected) class="mt-4 w-full rounded-lg bg-violet-600 px-4 py-2.5 text-sm text-white disabled:opacity-50">Save Preferences</button>
                </form>
                <section class="dashboard-card"><h2 class="text-base font-semibold text-slate-950">Channel Preference Mix</h2><div class="mt-4 h-48"><canvas data-chart="doughnut" data-labels='@json(collect($channelMix)->pluck("label"))' data-values='@json(collect($channelMix)->pluck("value"))' data-colors='@json(collect($channelMix)->pluck("color"))'></canvas></div></section>
            </aside>
        </section>
    </div>
</x-app-layout>
