<?php

use App\Http\Controllers\AccountSettingsController;
use App\Http\Controllers\AssetInventoryController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\MfaController;
use App\Http\Controllers\Auth\NewPasswordController;
use App\Http\Controllers\Auth\PasswordResetLinkController;
use App\Http\Controllers\Auth\SocialAuthController;
use App\Http\Controllers\AuthenticationSettingsController;
use App\Http\Controllers\BibleController;
use App\Http\Controllers\BiblePlanManagementController;
use App\Http\Controllers\BibleStudyController;
use App\Http\Controllers\BibleTranslationController;
use App\Http\Controllers\BookstoreController;
use App\Http\Controllers\BrandingController;
use App\Http\Controllers\CampusManagementController;
use App\Http\Controllers\CentralSupportController;
use App\Http\Controllers\ChildrenYouthController;
use App\Http\Controllers\CommunicationController;
use App\Http\Controllers\CounsellingController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DeveloperHubController;
use App\Http\Controllers\EventFlowController;
use App\Http\Controllers\FamilyManagementController;
use App\Http\Controllers\FinanceController;
use App\Http\Controllers\FinancialAssistanceController;
use App\Http\Controllers\InstallerController;
use App\Http\Controllers\LeadershipReportController;
use App\Http\Controllers\MemberManagementController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\MinistryController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\ModuleManagementController;
use App\Http\Controllers\NotificationAutomationController;
use App\Http\Controllers\PastoralCareController;
use App\Http\Controllers\PaymentGatewaySettingsController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PublicGivingController;
use App\Http\Controllers\PublicMemberRegistrationController;
use App\Http\Controllers\RemoteSupportAccessController;
use App\Http\Controllers\RoleDirectoryController;
use App\Http\Controllers\RolePermissionController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\StripeWebhookController;
use App\Http\Controllers\SupportCommunityController;
use App\Http\Controllers\SupportResourceController;
use App\Http\Controllers\SupportTicketController;
use App\Http\Controllers\SystemSettingsController;
use App\Http\Controllers\SystemUpdateController;
use App\Http\Controllers\TopbarCountsController;
use App\Http\Controllers\UserDirectoryController;
use App\Http\Controllers\UserManagementController;
use App\Http\Controllers\WorkflowController;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken;
use Illuminate\Support\Facades\Route;

Route::post('webhooks/meeting-attendance/{provider}', [EventFlowController::class, 'onlineAttendanceWebhook'])
    ->name('meeting-attendance.webhook')
    ->middleware('throttle:120,1')
    ->withoutMiddleware([VerifyCsrfToken::class]);

Route::get('m/{code}/{provider}', [EventFlowController::class, 'shortRoom'])->where('code', '[A-Za-z0-9-]+')->middleware('throttle:60,1')->name('meetings.rooms.short');
Route::post('m/{code}/{provider}/join', [EventFlowController::class, 'joinShortRoom'])->where('code', '[A-Za-z0-9-]+')->middleware('throttle:10,1')->name('meetings.rooms.short.join');
Route::get('m/{code}/{provider}/state', [EventFlowController::class, 'publicStudioState'])->where('code', '[A-Za-z0-9-]+')->middleware(['module.enabled', 'throttle:120,1'])->name('meetings.rooms.short.state');
Route::post('m/{code}/{provider}/qna', [EventFlowController::class, 'storePublicQuestion'])->where('code', '[A-Za-z0-9-]+')->middleware(['module.enabled', 'throttle:20,1'])->name('meetings.rooms.short.qna.store');
Route::post('m/{code}/{provider}/polls/{poll}/vote', [EventFlowController::class, 'storePublicPollVote'])->where('code', '[A-Za-z0-9-]+')->middleware(['module.enabled', 'throttle:60,1'])->name('meetings.rooms.short.polls.vote');

Route::view('/', 'landing')->name('home');
Route::view('features', 'features')->name('features');
Route::get('member-registration', [PublicMemberRegistrationController::class, 'create'])->name('members.self-register');
Route::post('member-registration', [PublicMemberRegistrationController::class, 'store'])->middleware('throttle:10,1')->name('members.self-register.store');
Route::get('give', [PublicGivingController::class, 'create'])->name('giving.create');
Route::post('give/checkout', [PublicGivingController::class, 'checkout'])->middleware('throttle:10,1')->name('giving.checkout');
Route::get('give/success', [PublicGivingController::class, 'success'])->name('giving.success');
Route::get('give/cancel', [PublicGivingController::class, 'cancel'])->name('giving.cancel');
Route::post('webhooks/stripe', StripeWebhookController::class)->middleware('throttle:120,1')->name('webhooks.stripe');
Route::post('webhooks/payments/{provider}', StripeWebhookController::class)
    ->whereIn('provider', ['paystack', 'paypal'])
    ->middleware('throttle:120,1')
    ->name('webhooks.payment');

Route::post('support/central-access/exchange', [RemoteSupportAccessController::class, 'exchange'])
    ->withoutMiddleware([VerifyCsrfToken::class])
    ->middleware('throttle:20,1')
    ->name('central-support.remote.exchange');
Route::post('support/central-events', [RemoteSupportAccessController::class, 'event'])
    ->withoutMiddleware([VerifyCsrfToken::class])
    ->middleware('throttle:120,1')
    ->name('central-support.events.receive');
Route::get('support/central-access/login/{token}', [RemoteSupportAccessController::class, 'login'])
    ->where('token', '[A-Za-z0-9]{64}')
    ->middleware('throttle:20,1')
    ->name('central-support.remote.login');

Route::middleware('guest')->group(function (): void {
    Route::get('install', [InstallerController::class, 'create'])->name('install');
    Route::post('install', [InstallerController::class, 'store'])->middleware('throttle:5,1')->name('install.store');
});

Route::middleware('guest')->group(function (): void {
    Route::get('login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('login', [AuthenticatedSessionController::class, 'store'])->name('login.store');
    Route::get('auth/{provider}/redirect', [SocialAuthController::class, 'redirect'])->middleware('throttle:20,1')->name('social.redirect');
    Route::get('auth/{provider}/callback', [SocialAuthController::class, 'callback'])->middleware('throttle:20,1')->name('social.callback');
    Route::get('login/mfa', [MfaController::class, 'challenge'])->name('login.mfa');
    Route::post('login/mfa', [MfaController::class, 'verify'])->middleware('throttle:6,1')->name('login.mfa.verify');
    Route::get('forgot-password', [PasswordResetLinkController::class, 'create'])->name('password.request');
    Route::post('forgot-password', [PasswordResetLinkController::class, 'store'])->middleware('throttle:6,1')->name('password.email');
    Route::get('reset-password/{token}', [NewPasswordController::class, 'create'])->name('password.reset');
    Route::post('reset-password', [NewPasswordController::class, 'store'])->middleware('throttle:6,1')->name('password.store');
});

Route::middleware(['auth', 'module.enabled'])->group(function (): void {
    Route::get('dashboard', DashboardController::class)->name('dashboard');
    Route::get('search', SearchController::class)->name('search');
    Route::get('topbar/counts', TopbarCountsController::class)->name('topbar.counts');
    Route::get('support', [SupportTicketController::class, 'index'])->name('support.index');
    Route::get('support/tickets', [SupportTicketController::class, 'tickets'])->name('support.tickets.index');
    Route::get('support/new', [SupportTicketController::class, 'create'])->name('support.tickets.create');
    Route::post('support', [SupportTicketController::class, 'store'])->middleware('throttle:10,1')->name('support.tickets.store');
    Route::get('support/community', [SupportCommunityController::class, 'index'])->name('support.community');
    Route::post('support/community', [SupportCommunityController::class, 'store'])->middleware('throttle:10,1')->name('support.community.store');
    Route::get('support/knowledge', [SupportResourceController::class, 'knowledge'])->name('support.knowledge');
    Route::get('support/live', [SupportResourceController::class, 'live'])->name('support.live');
    Route::post('support/live/messages', [SupportResourceController::class, 'sendLiveMessage'])->middleware('throttle:30,1')->name('support.live.messages');
    Route::get('support/central-connection', [CentralSupportController::class, 'index'])->name('central-support.index');
    Route::put('support/central-connection', [CentralSupportController::class, 'update'])->name('central-support.update');
    Route::post('support/central-connection/test', [CentralSupportController::class, 'test'])->middleware('throttle:10,1')->name('central-support.test');
    Route::post('support/central-connection/sync', [CentralSupportController::class, 'sync'])->middleware('throttle:10,1')->name('central-support.sync');
    Route::post('support/central-connection/grants', [CentralSupportController::class, 'grant'])->middleware('throttle:10,1')->name('central-support.grants.store');
    Route::delete('support/central-connection/grants/{centralSupportSession}', [CentralSupportController::class, 'revoke'])->name('central-support.grants.revoke');
    Route::post('support/central-access/end', [RemoteSupportAccessController::class, 'end'])->name('central-support.remote.end');
    Route::get('support/attachments/{attachment}/download', [SupportTicketController::class, 'downloadAttachment'])->name('support.attachments.download');
    Route::get('support/{ticket}', [SupportTicketController::class, 'show'])->name('support.tickets.show');
    Route::post('support/{ticket}/replies', [SupportTicketController::class, 'reply'])->middleware('throttle:20,1')->name('support.tickets.replies.store');
    Route::patch('support/{ticket}/tracking', [SupportTicketController::class, 'updateTracking'])->middleware('throttle:20,1')->name('support.tickets.tracking.update');
    Route::get('bible/admin/translations', [BibleTranslationController::class, 'index'])->name('bible.translations.index');
    Route::get('bible/admin/plans', [BiblePlanManagementController::class, 'index'])->name('bible.admin.plans.index');
    Route::post('bible/admin/plans', [BiblePlanManagementController::class, 'store'])->name('bible.admin.plans.store');
    Route::put('bible/admin/plans/{plan}', [BiblePlanManagementController::class, 'update'])->name('bible.admin.plans.update');
    Route::delete('bible/admin/plans/{plan}', [BiblePlanManagementController::class, 'destroy'])->name('bible.admin.plans.destroy');
    Route::post('bible/admin/translations', [BibleTranslationController::class, 'store'])->name('bible.translations.store');
    Route::post('bible/admin/translations/{translation}/install', [BibleTranslationController::class, 'install'])->name('bible.translations.install');
    Route::delete('bible/admin/translations/{translation}/uninstall', [BibleTranslationController::class, 'uninstall'])->name('bible.translations.uninstall');
    Route::delete('bible/admin/translations/{translation}', [BibleTranslationController::class, 'destroy'])->name('bible.translations.destroy');
    Route::post('bible/admin/translations/{translation}/import', [BibleTranslationController::class, 'import'])->name('bible.translations.import');
    Route::get('bible/admin/translations/sample', [BibleTranslationController::class, 'sample'])->name('bible.translations.sample');
    Route::get('bible', [BibleController::class, 'index'])->name('bible.index');
    Route::get('bible/plans', [BibleStudyController::class, 'plans'])->name('bible.plans');
    Route::get('bible/bookmarks', [BibleStudyController::class, 'bookmarks'])->name('bible.bookmarks');
    Route::get('bible/notes', [BibleStudyController::class, 'notes'])->name('bible.notes');
    Route::get('bible/highlights', [BibleStudyController::class, 'highlights'])->name('bible.highlights');
    Route::post('bible/plans/{plan}/start', [BibleStudyController::class, 'startPlan'])->name('bible.plans.start');
    Route::post('bible/plans/{plan}/complete-day', [BibleStudyController::class, 'completePlanDay'])->name('bible.plans.complete-day');
    Route::post('bible/bookmarks', [BibleStudyController::class, 'storeBookmark'])->name('bible.bookmarks.store');
    Route::get('bible/bookmarks/export', [BibleStudyController::class, 'exportBookmarks'])->name('bible.bookmarks.export');
    Route::delete('bible/bookmarks/{bookmark}', [BibleStudyController::class, 'destroyBookmark'])->name('bible.bookmarks.destroy');
    Route::post('bible/notes', [BibleStudyController::class, 'storeNote'])->name('bible.notes.store');
    Route::get('bible/notes/export', [BibleStudyController::class, 'exportNotes'])->name('bible.notes.export');
    Route::put('bible/notes/{note}', [BibleStudyController::class, 'updateNote'])->name('bible.notes.update');
    Route::delete('bible/notes/{note}', [BibleStudyController::class, 'destroyNote'])->name('bible.notes.destroy');
    Route::post('bible/highlights', [BibleStudyController::class, 'storeHighlight'])->name('bible.highlights.store');
    Route::get('bible/highlights/export', [BibleStudyController::class, 'exportHighlights'])->name('bible.highlights.export');
    Route::get('bible/reference-options', [BibleController::class, 'referenceOptions'])->name('bible.reference-options');
    Route::get('bible/search', [BibleController::class, 'search'])->name('bible.search');
    Route::get('bible/compare', [BibleController::class, 'compare'])->name('bible.compare');
    Route::get('bible/settings', [BibleController::class, 'settings'])->name('bible.settings');
    Route::put('bible/settings', [BibleController::class, 'updateSettings'])->name('bible.settings.update');
    Route::get('bible/{page}', [BibleController::class, 'placeholder'])->whereIn('page', ['search', 'compare', 'settings'])->name('bible.placeholder');
    Route::get('messages', [MessageController::class, 'index'])->name('messages.index');
    Route::get('messages/sent', [MessageController::class, 'sent'])->name('messages.sent');
    Route::get('messages/create', [MessageController::class, 'create'])->name('messages.create');
    Route::post('messages', [MessageController::class, 'store'])->name('messages.store');
    Route::post('messages/read-all', [MessageController::class, 'markAllRead'])->name('messages.read-all');
    Route::post('messages/drafts', [MessageController::class, 'saveDraft'])->name('messages.drafts.store');
    Route::put('messages/drafts/{draft}', [MessageController::class, 'saveDraft'])->name('messages.drafts.update');
    Route::delete('messages/drafts/{draft}', [MessageController::class, 'deleteDraft'])->name('messages.drafts.destroy');
    Route::get('messages/attachments/{attachment}', [MessageController::class, 'downloadAttachment'])->name('messages.attachments.download');
    Route::post('messages/items/{message}/forward', [MessageController::class, 'forward'])->name('messages.forward');
    Route::get('messages/{thread}', [MessageController::class, 'show'])->name('messages.show');
    Route::post('messages/{thread}/reply', [MessageController::class, 'reply'])->name('messages.reply');
    Route::post('messages/{thread}/read', [MessageController::class, 'read'])->name('messages.read');
    Route::post('messages/{thread}/state', [MessageController::class, 'state'])->name('messages.state');
    Route::post('messages/{thread}/action', [MessageController::class, 'action'])->name('messages.action');
    Route::post('messages/{thread}/participants', [MessageController::class, 'participants'])->name('messages.participants');
    Route::get('messages/{thread}/export', [MessageController::class, 'export'])->name('messages.export');
    Route::get('messages/{thread}/audit', [MessageController::class, 'audit'])->name('messages.audit');
    Route::post('messages/{thread}/report', [MessageController::class, 'report'])->name('messages.report');
    Route::get('programs', [EventFlowController::class, 'programs'])->name('programs.index');
    Route::post('programs', [EventFlowController::class, 'storeProgram'])->name('programs.store');
    Route::put('programs/{program}', [EventFlowController::class, 'updateProgram'])->name('programs.update');
    Route::delete('programs/{program}', [EventFlowController::class, 'destroyProgram'])->name('programs.destroy');
    Route::get('programs/{program}/events', [EventFlowController::class, 'events'])->name('programs.events');
    Route::post('programs/{program}/events', [EventFlowController::class, 'storeEvent'])->name('programs.events.store');
    Route::get('events', [EventFlowController::class, 'events'])->name('events.index');
    Route::get('programs/{program}/events/{event}/sessions', [EventFlowController::class, 'sessions'])->name('event-sessions.index');
    Route::post('programs/{program}/events/{event}/sessions', [EventFlowController::class, 'storeSession'])->name('event-sessions.store');
    Route::post('programs/{program}/events/{event}/recurrences', [EventFlowController::class, 'storeRecurringSessions'])->name('event-sessions.recurrences.store');
    Route::post('programs/{program}/events/{event}/sections', [EventFlowController::class, 'storeProgramSection'])->name('event-sections.store');
    Route::post('programs/{program}/events/{event}/sections/{section}/assignments', [EventFlowController::class, 'storeProgramSectionAssignment'])->name('event-section-assignments.store');
    Route::get('calendar', [EventFlowController::class, 'calendar'])->name('calendar.index');
    Route::get('meetings', [EventFlowController::class, 'meetings'])->name('meetings.index');
    Route::get('event-sessions/{eventSession}/meeting', [EventFlowController::class, 'meeting'])->name('event-sessions.meeting');
    Route::put('event-sessions/{eventSession}/meeting', [EventFlowController::class, 'updateMeeting'])->name('event-sessions.meeting.update');
    Route::get('meetings/rooms/{eventSession}/{provider}', [EventFlowController::class, 'room'])->name('meetings.rooms.show');
    Route::get('meetings/rooms/{eventSession}/{provider}/studio', [EventFlowController::class, 'studio'])->name('meetings.rooms.studio');
    Route::post('meetings/rooms/{eventSession}/{provider}/studio/scenes', [EventFlowController::class, 'storeStudioScene'])->name('meetings.rooms.studio.scenes.store');
    Route::post('meetings/rooms/{eventSession}/{provider}/studio/scenes/{scene}/preview', [EventFlowController::class, 'previewStudioScene'])->name('meetings.rooms.studio.scenes.preview');
    Route::post('meetings/rooms/{eventSession}/{provider}/studio/scenes/{scene}/live', [EventFlowController::class, 'takeStudioSceneLive'])->name('meetings.rooms.studio.scenes.live');
    Route::put('meetings/rooms/{eventSession}/{provider}/studio/scenes/{scene}/source', [EventFlowController::class, 'updateStudioSceneSource'])->name('meetings.rooms.studio.scenes.source');
    Route::delete('meetings/rooms/{eventSession}/{provider}/studio/scenes/{scene}', [EventFlowController::class, 'destroyStudioScene'])->name('meetings.rooms.studio.scenes.destroy');
    Route::put('meetings/rooms/{eventSession}/{provider}/studio/state', [EventFlowController::class, 'updateStudioState'])->name('meetings.rooms.studio.state.update');
    Route::post('meetings/rooms/{eventSession}/{provider}/studio/polls', [EventFlowController::class, 'storeStudioPoll'])->name('meetings.rooms.studio.polls.store');
    Route::put('meetings/rooms/{eventSession}/{provider}/studio/polls/{poll}', [EventFlowController::class, 'updateStudioPoll'])->name('meetings.rooms.studio.polls.update');
    Route::put('meetings/rooms/{eventSession}/{provider}/studio/qna/{question}', [EventFlowController::class, 'updateStudioQuestion'])->name('meetings.rooms.studio.qna.update');
    Route::post('meetings/rooms/{eventSession}/{provider}/attendance', [EventFlowController::class, 'markRoomAttendance'])->name('meetings.rooms.attendance.store');
    Route::post('meetings/rooms/{eventSession}/{provider}/checkout', [EventFlowController::class, 'markRoomCheckout'])->name('meetings.rooms.checkout.store');
    Route::get('event-sessions/{eventSession}/attendance', [EventFlowController::class, 'attendance'])->name('event-sessions.attendance');
    Route::put('event-sessions/{eventSession}/attendance', [EventFlowController::class, 'updateAttendance'])->name('event-sessions.attendance.update');
    Route::get('attendance', [EventFlowController::class, 'attendanceIndex'])->name('attendance.index');
    Route::delete('attendance/{attendanceSession}', [EventFlowController::class, 'destroyAttendanceSession'])->name('attendance.destroy');
    Route::get('attendance/{attendanceSession}/methods', [EventFlowController::class, 'methods'])->name('attendance.methods');
    Route::post('attendance/{attendanceSession}/check-in', [EventFlowController::class, 'checkIn'])->name('attendance.check-in');
    Route::put('attendance-records/{record}', [EventFlowController::class, 'updateAttendanceRecord'])->name('attendance.records.update');
    Route::delete('attendance-records/{record}', [EventFlowController::class, 'destroyAttendanceRecord'])->name('attendance.records.destroy');
    Route::get('attendance/{attendanceSession}/records/{member}', [EventFlowController::class, 'record'])->name('attendance.records.show');
    Route::get('administration/meeting-integrations', [EventFlowController::class, 'integrations'])->name('meeting-integrations.index');
    Route::put('administration/meeting-integrations', [EventFlowController::class, 'updateIntegrations'])->name('meeting-integrations.update');
    Route::post('administration/meeting-integrations/{provider}/test', [EventFlowController::class, 'testIntegration'])->name('meeting-integrations.test');
    Route::get('members/follow-up', [PastoralCareController::class, 'index'])->name('members.follow-up');
    Route::post('members/follow-up', [PastoralCareController::class, 'store'])->name('care-tasks.store');
    Route::post('members/follow-up/bulk', [PastoralCareController::class, 'bulk'])->name('care-tasks.bulk');
    Route::get('members/follow-up/export', [PastoralCareController::class, 'export'])->name('care-tasks.export');
    Route::put('members/follow-up/{task}', [PastoralCareController::class, 'update'])->name('care-tasks.update');
    Route::get('leadership-reports', [LeadershipReportController::class, 'index'])->name('leadership-reports.index');
    Route::post('leadership-reports', [LeadershipReportController::class, 'store'])->name('leadership-reports.store');
    Route::post('leadership-reports/summary', [LeadershipReportController::class, 'generateSummary'])->name('leadership-reports.summary');
    Route::post('leadership-reports/reminders', [LeadershipReportController::class, 'sendReminders'])->name('leadership-reports.reminders');
    Route::put('leadership-reports/settings', [LeadershipReportController::class, 'updateSettings'])->name('leadership-reports.settings.update');
    Route::get('leadership-reports/export', [LeadershipReportController::class, 'export'])->name('leadership-reports.export');
    Route::get('leadership-reports/{leadershipReport}', [LeadershipReportController::class, 'show'])->name('leadership-reports.show');
    Route::put('leadership-reports/{leadershipReport}', [LeadershipReportController::class, 'update'])->name('leadership-reports.update');
    Route::delete('leadership-reports/{leadershipReport}', [LeadershipReportController::class, 'destroy'])->name('leadership-reports.destroy');
    Route::put('leadership-reports/{leadershipReport}/review', [LeadershipReportController::class, 'review'])->name('leadership-reports.review');
    Route::get('members', [MemberManagementController::class, 'index'])->name('members.index');
    Route::get('members/create', [MemberManagementController::class, 'create'])->name('members.create');
    Route::post('members', [MemberManagementController::class, 'store'])->name('members.store');
    Route::post('members/import', [MemberManagementController::class, 'import'])->name('members.import');
    Route::get('members/export', [MemberManagementController::class, 'export'])->name('members.export');
    Route::get('members/bulk', fn () => redirect()->route('members.index')->with('error', 'Use the Bulk Actions menu to apply changes to selected members.'))->name('members.bulk.fallback');
    Route::post('members/bulk', [MemberManagementController::class, 'bulk'])->name('members.bulk');
    Route::get('members/{member}', [MemberManagementController::class, 'show'])->name('members.show');
    Route::post('members/{member}/check-in', [MemberManagementController::class, 'checkIn'])->name('members.check-in');
    Route::post('members/{member}/assign-ministry', [MemberManagementController::class, 'assignMinistry'])->name('members.assign-ministry');
    Route::put('members/{member}', [MemberManagementController::class, 'update'])->name('members.update');
    Route::delete('members/{member}', [MemberManagementController::class, 'destroy'])->name('members.destroy');
    Route::get('ministries', [MinistryController::class, 'index'])->name('ministries.index');
    Route::post('ministries', [MinistryController::class, 'store'])->name('ministries.store');
    Route::post('ministries/import', [MinistryController::class, 'import'])->name('ministries.import');
    Route::post('ministries/clone-campus', [MinistryController::class, 'cloneCampus'])->name('ministries.clone-campus');
    Route::put('ministries/{ministry}', [MinistryController::class, 'update'])->name('ministries.update');
    Route::delete('ministries/{ministry}', [MinistryController::class, 'destroy'])->name('ministries.destroy');
    Route::get('families', [FamilyManagementController::class, 'index'])->name('families.index');
    Route::post('families', [FamilyManagementController::class, 'store'])->name('families.store');
    Route::get('families/export', [FamilyManagementController::class, 'export'])->name('families.export');
    Route::put('families/{family}', [FamilyManagementController::class, 'update'])->name('families.update');
    Route::delete('families/{family}', [FamilyManagementController::class, 'destroy'])->name('families.destroy');
    Route::get('finance', [FinanceController::class, 'index'])->name('finance.index');
    Route::get('finance/overview', [FinanceController::class, 'overview'])->name('finance.overview');
    Route::get('finance/donations/create', [FinanceController::class, 'create'])->name('finance.donations.create');
    Route::get('finance/donations/{donation}/edit', [FinanceController::class, 'edit'])->name('finance.donations.edit');
    Route::post('finance/donations', [FinanceController::class, 'store'])->name('finance.donations.store');
    Route::put('finance/donations/{donation}', [FinanceController::class, 'update'])->name('finance.donations.update');
    Route::delete('finance/donations/{donation}', [FinanceController::class, 'destroy'])->name('finance.donations.destroy');
    Route::post('finance/transactions', [FinanceController::class, 'storeTransaction'])->name('finance.transactions.store');
    Route::put('finance/transactions/{transaction}', [FinanceController::class, 'updateTransaction'])->name('finance.transactions.update');
    Route::delete('finance/transactions/{transaction}', [FinanceController::class, 'destroyTransaction'])->name('finance.transactions.destroy');
    Route::post('finance/funds', [FinanceController::class, 'storeFund'])->name('finance.funds.store');
    Route::put('finance/funds/{fund}', [FinanceController::class, 'updateFund'])->name('finance.funds.update');
    Route::delete('finance/funds/{fund}', [FinanceController::class, 'destroyFund'])->name('finance.funds.destroy');
    Route::get('finance/export', [FinanceController::class, 'export'])->name('finance.export');
    Route::get('financial-assistance', [FinancialAssistanceController::class, 'index'])->name('financial-assistance.index');
    Route::get('financial-assistance/new', [FinancialAssistanceController::class, 'create'])->name('financial-assistance.create');
    Route::post('financial-assistance', [FinancialAssistanceController::class, 'store'])->name('financial-assistance.store');
    Route::get('financial-assistance/evidence/{attachment}/download', [FinancialAssistanceController::class, 'download'])->name('financial-assistance.attachments.download');
    Route::get('financial-assistance/{assistance}', [FinancialAssistanceController::class, 'show'])->name('financial-assistance.show');
    Route::post('financial-assistance/{assistance}/decision', [FinancialAssistanceController::class, 'decide'])->name('financial-assistance.decide');
    Route::post('financial-assistance/{assistance}/resubmit', [FinancialAssistanceController::class, 'resubmit'])->name('financial-assistance.resubmit');
    Route::post('financial-assistance/{assistance}/disburse', [FinancialAssistanceController::class, 'disburse'])->name('financial-assistance.disburse');
    Route::delete('financial-assistance/{assistance}', [FinancialAssistanceController::class, 'cancel'])->name('financial-assistance.cancel');
    Route::get('assets', [AssetInventoryController::class, 'index'])->name('assets.index');
    Route::get('assets/overview', [AssetInventoryController::class, 'overview'])->name('assets.overview');
    Route::get('assets/create', [AssetInventoryController::class, 'create'])->name('assets.create');
    Route::get('assets/{asset}/edit', [AssetInventoryController::class, 'edit'])->name('assets.edit');
    Route::post('assets', [AssetInventoryController::class, 'store'])->name('assets.store');
    Route::post('assets/bookings', [AssetInventoryController::class, 'storeBooking'])->name('assets.bookings.store');
    Route::put('assets/bookings/{booking}', [AssetInventoryController::class, 'updateBooking'])->name('assets.bookings.update');
    Route::delete('assets/bookings/{booking}', [AssetInventoryController::class, 'destroyBooking'])->name('assets.bookings.destroy');
    Route::put('assets/{asset}', [AssetInventoryController::class, 'update'])->name('assets.update');
    Route::delete('assets/{asset}', [AssetInventoryController::class, 'destroy'])->name('assets.destroy');
    Route::post('asset-categories', [AssetInventoryController::class, 'storeCategory'])->name('asset-categories.store');
    Route::get('assets/export', [AssetInventoryController::class, 'export'])->name('assets.export');
    Route::get('bookstore', [BookstoreController::class, 'index'])->name('bookstore.index');
    Route::get('bookstore/overview', [BookstoreController::class, 'overview'])->name('bookstore.overview');
    Route::get('bookstore/library', [BookstoreController::class, 'library'])->name('bookstore.library');
    Route::get('bookstore/products/create', [BookstoreController::class, 'createProduct'])->name('bookstore.products.create');
    Route::get('bookstore/products/{product}/edit', [BookstoreController::class, 'editProduct'])->name('bookstore.products.edit');
    Route::get('bookstore/orders/create', [BookstoreController::class, 'createOrder'])->name('bookstore.orders.create');
    Route::post('bookstore/products', [BookstoreController::class, 'storeProduct'])->name('bookstore.products.store');
    Route::put('bookstore/products/{product}', [BookstoreController::class, 'updateProduct'])->name('bookstore.products.update');
    Route::delete('bookstore/products/{product}', [BookstoreController::class, 'destroyProduct'])->name('bookstore.products.destroy');
    Route::post('bookstore/orders', [BookstoreController::class, 'storeOrder'])->name('bookstore.orders.store');
    Route::put('bookstore/orders/{order}', [BookstoreController::class, 'updateOrder'])->name('bookstore.orders.update');
    Route::delete('bookstore/orders/{order}', [BookstoreController::class, 'destroyOrder'])->name('bookstore.orders.destroy');
    Route::get('bookstore/orders/export', [BookstoreController::class, 'exportOrders'])->name('bookstore.orders.export');
    Route::post('bookstore/library/loans', [BookstoreController::class, 'storeLibraryLoan'])->name('bookstore.library.loans.store');
    Route::put('bookstore/library/loans/{loan}', [BookstoreController::class, 'updateLibraryLoan'])->name('bookstore.library.loans.update');
    Route::delete('bookstore/library/loans/{loan}', [BookstoreController::class, 'destroyLibraryLoan'])->name('bookstore.library.loans.destroy');
    Route::get('bookstore/library/export', [BookstoreController::class, 'exportLibrary'])->name('bookstore.library.export');
    Route::get('bookstore/export', [BookstoreController::class, 'export'])->name('bookstore.export');
    Route::get('children-youth', [ChildrenYouthController::class, 'index'])->name('children-youth.index');
    Route::get('children-youth/overview', [ChildrenYouthController::class, 'overview'])->name('children-youth.overview');
    Route::get('children-youth/create', [ChildrenYouthController::class, 'create'])->name('children-youth.create');
    Route::get('children-youth/{record}/edit', [ChildrenYouthController::class, 'edit'])->name('children-youth.edit');
    Route::post('children-youth', [ChildrenYouthController::class, 'store'])->name('children-youth.store');
    Route::put('children-youth/{record}', [ChildrenYouthController::class, 'update'])->name('children-youth.update');
    Route::delete('children-youth/{record}', [ChildrenYouthController::class, 'destroy'])->name('children-youth.destroy');
    Route::get('children-youth/export', [ChildrenYouthController::class, 'export'])->name('children-youth.export');
    Route::get('counselling', [CounsellingController::class, 'index'])->name('counselling.index');
    Route::get('counselling/overview', [CounsellingController::class, 'overview'])->name('counselling.overview');
    Route::get('counselling/create', [CounsellingController::class, 'create'])->name('counselling.create');
    Route::get('counselling/{case}/edit', [CounsellingController::class, 'edit'])->name('counselling.edit');
    Route::post('counselling', [CounsellingController::class, 'store'])->name('counselling.store');
    Route::post('counselling/bookings', [CounsellingController::class, 'storeBooking'])->name('counselling.bookings.store');
    Route::put('counselling/bookings/{booking}', [CounsellingController::class, 'updateBooking'])->name('counselling.bookings.update');
    Route::delete('counselling/bookings/{booking}', [CounsellingController::class, 'destroyBooking'])->name('counselling.bookings.destroy');
    Route::put('counselling/{case}', [CounsellingController::class, 'update'])->name('counselling.update');
    Route::delete('counselling/{case}', [CounsellingController::class, 'destroy'])->name('counselling.destroy');
    Route::get('counselling/export', [CounsellingController::class, 'export'])->name('counselling.export');
    Route::get('settings', SystemSettingsController::class)->name('settings.index');
    Route::put('settings/system', [SystemSettingsController::class, 'update'])->name('settings.system.update');
    Route::put('settings/system/reset', [SystemSettingsController::class, 'reset'])->name('settings.system.reset');
    Route::post('settings/system/test-connection', [SystemSettingsController::class, 'testConnection'])->name('settings.system.test-connection');
    Route::get('administration/payment-gateways', [PaymentGatewaySettingsController::class, 'index'])->name('payment-gateways.index');
    Route::put('administration/payment-gateways', [PaymentGatewaySettingsController::class, 'update'])->name('payment-gateways.update');
    Route::put('administration/payment-gateways/{provider}', [PaymentGatewaySettingsController::class, 'update'])->name('payment-gateways.update-provider');
    Route::post('administration/payment-gateways/test', [PaymentGatewaySettingsController::class, 'test'])->name('payment-gateways.test');
    Route::post('administration/payment-gateways/{provider}/test', [PaymentGatewaySettingsController::class, 'test'])->name('payment-gateways.test-provider');
    Route::post('settings/branding/sidebar-background', [BrandingController::class, 'updateSidebarBackground'])->name('settings.branding.sidebar-background');
    Route::delete('settings/branding/sidebar-background', [BrandingController::class, 'resetSidebarBackground'])->name('settings.branding.sidebar-background.reset');
    Route::get('communications', [CommunicationController::class, 'overview'])->name('communications.index');
    Route::get('communications/notifications', [CommunicationController::class, 'notifications'])->name('communications.notifications');
    Route::post('communications/notifications/read-all', [CommunicationController::class, 'markAllNotificationsRead'])->name('communications.notifications.read-all');
    Route::post('communications/notifications/archive-old', [CommunicationController::class, 'archiveOldNotifications'])->name('communications.notifications.archive-old');
    Route::post('communications/notifications/{delivery}/read', [CommunicationController::class, 'markNotificationRead'])->name('communications.notifications.read');
    Route::post('communications/notifications/{delivery}/archive', [CommunicationController::class, 'archiveNotification'])->name('communications.notifications.archive');
    Route::get('communications/templates', [CommunicationController::class, 'templates'])->name('communications.templates');
    Route::get('communications/templates/export', [CommunicationController::class, 'exportTemplates'])->name('communications.templates.export');
    Route::post('communications/templates', [CommunicationController::class, 'storeTemplate'])->name('communications.templates.store');
    Route::put('communications/templates/{template}', [CommunicationController::class, 'updateTemplate'])->name('communications.templates.update');
    Route::delete('communications/templates/{template}', [CommunicationController::class, 'deleteTemplate'])->name('communications.templates.destroy');
    Route::post('communications/templates/{template}/clone', [CommunicationController::class, 'cloneTemplate'])->name('communications.templates.clone');
    Route::post('communications/templates/{template}/test-send', [CommunicationController::class, 'testSendTemplate'])->name('communications.templates.test-send');
    Route::get('communications/scheduled', [CommunicationController::class, 'scheduled'])->name('communications.scheduled');
    Route::get('communications/bulk', [CommunicationController::class, 'bulk'])->name('communications.bulk');
    Route::post('communications/campaigns', [CommunicationController::class, 'storeCampaign'])->name('communications.campaigns.store');
    Route::post('communications/campaigns/{campaign}/send', [CommunicationController::class, 'sendCampaignNow'])->name('communications.campaigns.send');
    Route::delete('communications/campaigns/{campaign}', [CommunicationController::class, 'deleteCampaign'])->name('communications.campaigns.destroy');
    Route::get('communications/delivery-logs', [CommunicationController::class, 'deliveryLogs'])->name('communications.delivery-logs');
    Route::get('communications/delivery-logs/export', [CommunicationController::class, 'exportDeliveries'])->name('communications.delivery-logs.export');
    Route::post('communications/delivery-logs/{delivery}/retry', [CommunicationController::class, 'retryDelivery'])->name('communications.delivery-logs.retry');
    Route::get('communications/preferences', [CommunicationController::class, 'preferences'])->name('communications.preferences');
    Route::get('communications/preferences/export', [CommunicationController::class, 'exportPreferences'])->name('communications.preferences.export');
    Route::post('communications/preferences/defaults', [CommunicationController::class, 'applyDefaultPreferences'])->name('communications.preferences.defaults');
    Route::post('communications/preferences/reminders', [CommunicationController::class, 'sendPreferenceReminder'])->name('communications.preferences.reminders');
    Route::post('communications/preferences/import', [CommunicationController::class, 'importPreferences'])->name('communications.preferences.import');
    Route::put('communications/preferences/{preference}', [CommunicationController::class, 'updatePreference'])->name('communications.preferences.update');
    Route::get('communications/automation', [NotificationAutomationController::class, 'index'])->name('communications.automation');
    Route::put('communications/automation/{automationRule}', [NotificationAutomationController::class, 'update'])->name('communications.automation.update');
    Route::post('communications/automation/{automationRule}/test', [NotificationAutomationController::class, 'test'])->name('communications.automation.test');
    Route::post('communications/automation/retry-failed', [NotificationAutomationController::class, 'retryFailed'])->name('communications.automation.retry-failed');
    Route::get('communications/integrations', fn () => redirect()->route('communications.integrations'));
    Route::get('administration/communication-integrations', [CommunicationController::class, 'integrations'])->name('communications.integrations');
    Route::put('administration/communication-integrations', [CommunicationController::class, 'updateIntegrations'])->name('communications.integrations.update');
    Route::post('administration/communication-integrations/zender/groups', [CommunicationController::class, 'storeZenderWhatsAppGroup'])->name('communications.integrations.zender-groups.store');
    Route::post('administration/communication-integrations/zender/groups/sync', [CommunicationController::class, 'syncZenderWhatsAppGroups'])->name('communications.integrations.zender-groups.sync');
    Route::post('administration/communication-integrations/{channel}/test', [CommunicationController::class, 'testIntegration'])->name('communications.integrations.test');
    Route::get('administration/users', UserDirectoryController::class)->name('users.index');
    Route::get('administration/users/export', [UserDirectoryController::class, 'export'])->name('users.export');
    Route::get('administration/users/{user}', [UserManagementController::class, 'show'])->name('users.show');
    Route::get('administration/roles', RoleDirectoryController::class)->name('roles.index');
    Route::get('administration/roles/report', [RolePermissionController::class, 'report'])->name('roles.report');
    Route::get('administration/campuses', CampusManagementController::class)->name('campuses.index');
    Route::post('administration/campuses', [CampusManagementController::class, 'store'])->name('campuses.store');
    Route::put('administration/campuses/{campus}', [CampusManagementController::class, 'update'])->name('campuses.update');
    Route::delete('administration/campuses/{campus}', [CampusManagementController::class, 'destroy'])->name('campuses.destroy');
    Route::put('administration/churches/{church}', [CampusManagementController::class, 'updateChurch'])->name('churches.update');
    Route::delete('administration/churches/{church}', [CampusManagementController::class, 'destroyChurch'])->name('churches.destroy');
    Route::post('administration/campuses/import', [CampusManagementController::class, 'import'])->name('campuses.import');
    Route::get('administration/modules', ModuleManagementController::class)->name('modules.index');
    Route::put('administration/modules', [ModuleManagementController::class, 'update'])->name('modules.update');
    Route::put('administration/modules/bulk', [ModuleManagementController::class, 'bulkUpdate'])->name('modules.bulk-update');
    Route::put('administration/modules/reset', [ModuleManagementController::class, 'reset'])->name('modules.reset');
    Route::get('administration/authentication', [AuthenticationSettingsController::class, 'index'])->name('auth-settings.index');
    Route::put('administration/authentication', [AuthenticationSettingsController::class, 'update'])->name('auth-settings.update');
    Route::get('administration/developer-hub', DeveloperHubController::class)->name('developer-hub.index');
    Route::get('administration/system-updates', [SystemUpdateController::class, 'index'])->name('system-updates.index');
    Route::post('administration/system-updates/check', [SystemUpdateController::class, 'check'])->middleware('throttle:6,1')->name('system-updates.check');
    Route::post('administration/system-updates/{systemUpdate}/approve', [SystemUpdateController::class, 'approve'])->middleware('throttle:3,1')->name('system-updates.approve');
    Route::post('administration/system-updates/{systemUpdate}/skip', [SystemUpdateController::class, 'skip'])->middleware('throttle:6,1')->name('system-updates.skip');
    Route::get('administration/audit-logs', AuditLogController::class)->name('audit-logs.index');
    Route::get('administration/audit-logs/export', [AuditLogController::class, 'export'])->name('audit-logs.export');
    Route::get('workflows', [WorkflowController::class, 'index'])->name('workflows.index');
    Route::post('workflows', [WorkflowController::class, 'store'])->name('workflows.store');
    Route::put('workflows/{workflow}', [WorkflowController::class, 'update'])->name('workflows.update');
    Route::delete('workflows/{workflow}', [WorkflowController::class, 'destroy'])->name('workflows.destroy');
    Route::post('workflows/import', [WorkflowController::class, 'import'])->name('workflows.import');
    Route::post('workflows/approvals/{approval}/approve', [WorkflowController::class, 'approve'])->name('workflows.approvals.approve');
    Route::post('workflows/approvals/{approval}/reject', [WorkflowController::class, 'reject'])->name('workflows.approvals.reject');
    Route::post('program-section-assignments/{assignment}/accept', [WorkflowController::class, 'acceptAssignment'])->name('program-section-assignments.accept');
    Route::post('program-section-assignments/{assignment}/decline', [WorkflowController::class, 'declineAssignment'])->name('program-section-assignments.decline');
    Route::post('settings/users', [UserManagementController::class, 'store'])->name('users.store');
    Route::post('settings/users/bulk', [UserManagementController::class, 'bulk'])->name('users.bulk');
    Route::post('settings/users/impersonation/stop', [UserManagementController::class, 'stopImpersonating'])->name('users.impersonation.stop');
    Route::put('settings/users/{user}', [UserManagementController::class, 'update'])->name('users.update');
    Route::put('settings/users/{user}/password', [UserManagementController::class, 'resetPassword'])->name('users.password');
    Route::post('settings/users/{user}/message', [UserManagementController::class, 'message'])->name('users.message');
    Route::post('settings/users/{user}/impersonate', [UserManagementController::class, 'impersonate'])->name('users.impersonate');
    Route::post('settings/roles', [RolePermissionController::class, 'store'])->name('roles.store');
    Route::post('settings/roles/{role}/clone', [RolePermissionController::class, 'clone'])->name('roles.clone');
    Route::put('settings/roles/{role}/reset', [RolePermissionController::class, 'reset'])->name('roles.reset');
    Route::put('settings/roles/{role}', [RolePermissionController::class, 'update'])->name('roles.update');

    foreach (collect(config('navigation'))->flatMap(fn (array $item): array => $item['children'] ?? [$item]) as $item) {
        if (in_array(($item['route'] ?? null), ['dashboard', 'programs.index', 'events.index', 'calendar.index', 'meetings.index', 'attendance.index', 'members.index', 'ministries.index', 'families.index', 'finance.index', 'financial-assistance.index', 'assets.index', 'bookstore.index', 'children-youth.index', 'counselling.index', 'leadership-reports.index', 'settings.index', 'users.index', 'roles.index', 'campuses.index', 'modules.index', 'auth-settings.index', 'developer-hub.index', 'system-updates.index', 'audit-logs.index', 'workflows.index', 'meeting-integrations.index', 'payment-gateways.index', 'communications.index', 'communications.notifications', 'communications.templates', 'communications.scheduled', 'communications.bulk', 'communications.delivery-logs', 'communications.preferences', 'communications.automation', 'communications.integrations', 'messages.index', 'messages.sent', 'messages.create', 'bible.index', 'bible.plans', 'bible.admin.plans.index', 'bible.bookmarks', 'bible.notes', 'bible.highlights', 'bible.search', 'bible.compare', 'bible.settings', 'bible.placeholder', 'bible.translations.index', 'support.index'], true)) {
            continue;
        }

        Route::get(str_replace('.index', '', (string) $item['route']), ModuleController::class)->name($item['route']);
    }

    Route::get('profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::put('profile/password', [ProfileController::class, 'password'])->name('profile.password');
    Route::post('profile/impersonate', [ProfileController::class, 'impersonate'])->name('profile.impersonate');
    Route::get('account/settings', [AccountSettingsController::class, 'edit'])->name('account.settings');
    Route::put('account/settings', [AccountSettingsController::class, 'update'])->name('account.settings.update');
    Route::post('account/settings/test-notification', [AccountSettingsController::class, 'testNotification'])->name('account.settings.test-notification');
    Route::get('account/notifications/{notification}/open', [AccountSettingsController::class, 'openNotification'])->name('account.notifications.open');
    Route::get('account/mfa/setup', [AccountSettingsController::class, 'mfaSetup'])->name('account.mfa.setup');
    Route::post('account/mfa/confirm', [AccountSettingsController::class, 'confirmMfa'])->name('account.mfa.confirm');
    Route::post('account/mfa/recovery-codes', [AccountSettingsController::class, 'regenerateRecoveryCodes'])->name('account.mfa.recovery-codes');
    Route::post('logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
    Route::get('admin-only', fn () => 'ok')->middleware('role:Super Administrator')->name('admin.only');
});
