<x-app-layout title="Member Profile" :breadcrumbs="$breadcrumbs">
    @php
        $attendanceScore = min(100, $member->attendanceRecords->where('service_date', '>=', now()->subDays(90))->count() * 10);
        $givingConsistency = $member->donations->where('received_at', '>=', now()->subMonths(6))->count() > 0 ? 92 : 0;
        $volunteerHours = $member->volunteers->count() * 24;
        $profileCompletion = collect([$member->email, $member->phone, $member->campus_id, $member->family_id, $member->joined_at])->filter()->count() * 20;
    @endphp

    <div x-data="{ editOpen: {{ request()->boolean('edit') ? 'true' : 'false' }}, careOpen: false, ministryOpen: false }" class="space-y-5">
        <div class="flex flex-wrap justify-end gap-2">
            <a href="mailto:{{ $member->email }}" class="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-medium text-slate-700"><i data-lucide="send" class="size-4"></i>Send Message</a>
            <form method="POST" action="{{ route('members.check-in', $member) }}">@csrf<button class="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-medium text-slate-700"><i data-lucide="check" class="size-4"></i>Check In</button></form>
            <button @click="ministryOpen = true" class="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-medium text-slate-700"><i data-lucide="users-round" class="size-4"></i>Assign Ministry</button>
            <button @click="editOpen = true" class="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2.5 text-sm font-medium text-white"><i data-lucide="pencil" class="size-4"></i>Edit Member</button>
        </div>

        @if(session('status'))<div class="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm font-medium text-emerald-700">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm font-medium text-rose-700">{{ $errors->first() }}</div>@endif

        <section class="dashboard-card">
            <div class="grid gap-5 xl:grid-cols-[1fr_560px]">
                <div class="flex items-center gap-5">
                    <div class="relative grid size-28 place-items-center rounded-full bg-violet-100 text-3xl font-semibold text-violet-700">{{ Str::substr($member->first_name, 0, 1) }}{{ Str::substr($member->last_name, 0, 1) }}<span class="absolute bottom-1 right-1 size-4 rounded-full border-2 border-white bg-emerald-500"></span></div>
                    <div>
                        <h1 class="text-3xl font-semibold text-slate-950">{{ $member->first_name }} {{ $member->last_name }}</h1>
                        <p class="mt-1 text-sm text-slate-500">Member ID: {{ $profile['code'] }}</p>
                        <div class="mt-3 flex flex-wrap gap-2"><span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-medium text-emerald-700">{{ Str::headline($member->status) }}</span><span class="rounded-full bg-violet-50 px-2.5 py-1 text-xs font-medium text-violet-700">{{ $profile['givingStatus'] }}</span></div>
                        <div class="mt-3 grid gap-1 text-sm text-slate-600"><span><i data-lucide="calendar-days" class="mr-2 inline size-4 text-slate-400"></i>Joined: {{ $profile['joined'] }}</span><span><i data-lucide="users-round" class="mr-2 inline size-4 text-slate-400"></i>{{ $member->family?->name ?? 'No household' }}</span></div>
                    </div>
                </div>
                <div class="grid gap-3 sm:grid-cols-4">
                    @foreach ([['Attendance Score', $attendanceScore.'%', 'Consistent'], ['Giving Consistency', $givingConsistency.'%', $givingConsistency ? 'Faithful' : 'No gifts'], ['Volunteer Hours', $volunteerHours, 'Hours'], ['Profile Completeness', $profileCompletion.'%', 'Current']] as [$label, $value, $note])
                        <div class="rounded-lg border border-slate-200 p-4 text-center"><div class="text-xs font-medium text-slate-500">{{ $label }}</div><div class="mt-3 text-2xl font-semibold text-slate-950">{{ $value }}</div><div class="mt-1 text-xs text-emerald-600">{{ $note }}</div></div>
                    @endforeach
                </div>
            </div>
        </section>

        <nav class="flex gap-6 border-b border-slate-200 text-sm font-medium text-slate-500">
            @foreach(['Overview','Family','Attendance','Giving','Ministry Involvement','Notes','Documents','Activity Timeline'] as $item)<a href="#{{ Str::slug($item) }}" class="border-b-2 border-transparent px-1 pb-3 hover:border-violet-600 hover:text-violet-600">{{ $item }}</a>@endforeach
        </nav>

        <section id="overview" class="grid gap-4 md:grid-cols-2 xl:grid-cols-5">
            <div class="dashboard-card"><h2 class="mb-4 flex items-center gap-2 text-base font-semibold text-slate-950"><i data-lucide="user-round" class="size-4 text-violet-600"></i>Personal Information</h2><dl class="space-y-2 text-sm">@foreach([['Full Name', $profile['name']], ['Email', $profile['email']], ['Phone', $profile['phone']], ['Status', Str::headline($member->status)], ['Member Type', $profile['givingStatus'] === 'Tither' ? 'Regular Member' : 'Member']] as [$label, $value])<div class="flex justify-between gap-3"><dt class="text-slate-500">{{ $label }}</dt><dd class="text-right font-medium text-slate-900">{{ $value }}</dd></div>@endforeach</dl></div>
            <div class="dashboard-card"><h2 class="mb-4 flex items-center gap-2 text-base font-semibold text-slate-950"><i data-lucide="phone" class="size-4 text-violet-600"></i>Contact Information</h2><div class="space-y-3 text-sm text-slate-600"><div><i data-lucide="mail" class="mr-2 inline size-4 text-violet-600"></i>{{ $profile['email'] }}</div><div><i data-lucide="phone" class="mr-2 inline size-4 text-violet-600"></i>{{ $profile['phone'] }}</div><div><i data-lucide="map-pin" class="mr-2 inline size-4 text-violet-600"></i>{{ $member->family?->address ?? 'No address on file' }}</div></div></div>
            <div class="dashboard-card"><h2 class="mb-4 flex items-center gap-2 text-base font-semibold text-slate-950"><i data-lucide="users-round" class="size-4 text-violet-600"></i>Family & Household</h2><div class="space-y-2 text-sm">@forelse($member->family?->members ?? [] as $relative)<a href="{{ route('members.show', $relative) }}" class="flex justify-between"><span>{{ $relative->first_name }} {{ $relative->last_name }}</span><span class="text-slate-500">{{ $relative->id === $member->family?->primary_contact_id ? 'Head' : 'Member' }}</span></a>@empty<div class="text-slate-500">No household assigned.</div>@endforelse</div></div>
            <div class="dashboard-card"><h2 class="mb-4 flex items-center gap-2 text-base font-semibold text-slate-950"><i data-lucide="landmark" class="size-4 text-violet-600"></i>Church & Campus Assignment</h2><dl class="space-y-2 text-sm"><div class="flex justify-between"><dt class="text-slate-500">Church</dt><dd class="font-medium">{{ $member->church?->name }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">Campus</dt><dd class="font-medium">{{ $member->campus?->name ?? 'Unassigned' }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">Ministry</dt><dd class="font-medium">{{ $profile['ministry'] }}</dd></div></dl></div>
            <div class="dashboard-card"><h2 class="mb-4 flex items-center gap-2 text-base font-semibold text-slate-950"><i data-lucide="hand-heart" class="size-4 text-violet-600"></i>Pastoral Care Status</h2><dl class="space-y-2 text-sm"><div class="flex justify-between"><dt class="text-slate-500">Open Tasks</dt><dd class="font-medium">{{ $member->careTasks->where('status', '!=', 'resolved')->count() }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">Prayer Requests</dt><dd class="font-medium">{{ $member->prayerRequests->count() }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">Last Contact</dt><dd class="font-medium">{{ $member->careTasks->sortByDesc('updated_at')->first()?->updated_at?->format('M d, Y') ?? 'No contact' }}</dd></div></dl><button @click="careOpen = true" class="mt-4 text-sm font-medium text-violet-600">Create Task</button></div>
        </section>

        <section class="grid gap-4 lg:grid-cols-3">
            <div class="dashboard-card"><h2 class="mb-4 text-base font-semibold text-slate-950">Follow-up Tasks</h2><div class="space-y-3">@forelse($member->careTasks as $task)<div class="flex items-start justify-between gap-3 text-sm"><span>{{ $task->next_action ?: $task->type }}</span><span class="rounded-full bg-orange-50 px-2 py-1 text-xs text-orange-700">{{ Str::headline($task->status) }}</span></div>@empty<div class="text-sm text-slate-500">No care tasks.</div>@endforelse</div></div>
            <div class="dashboard-card"><h2 class="mb-4 text-base font-semibold text-slate-950">Prayer Requests</h2><div class="space-y-3">@forelse($member->prayerRequests as $request)<div class="text-sm"><div class="font-medium text-slate-900">{{ $request->title }}</div><div class="text-xs text-slate-500">{{ Str::headline($request->status) }} · {{ $request->created_at->format('M d, Y') }}</div></div>@empty<div class="text-sm text-slate-500">No prayer requests.</div>@endforelse</div></div>
            <div class="dashboard-card"><h2 class="mb-4 text-base font-semibold text-slate-950">Giving Summary</h2><div class="text-2xl font-semibold text-slate-950">{{ Number::currency((float) $givingTotal, $member->church?->currency ?? 'USD') }}</div><p class="mt-1 text-sm text-slate-500">Total giving recorded for this member.</p></div>
        </section>

        <section class="dashboard-card"><div class="mb-4 flex items-center justify-between"><h2 class="text-base font-semibold text-slate-950">Activity Timeline</h2><a href="{{ route('audit-logs.index', ['keyword' => $member->first_name]) }}" class="text-sm font-medium text-violet-600">View Full Timeline</a></div><div class="grid gap-3 md:grid-cols-4">@forelse($recentActivity as $activity)<div class="rounded-lg border border-slate-200 p-3 text-sm"><div class="font-medium text-slate-900">{{ $activity->description }}</div><div class="mt-1 text-xs text-slate-500">{{ $activity->created_at->format('M d, Y h:i A') }}</div></div>@empty<div class="text-sm text-slate-500">No activity for this member yet.</div>@endforelse</div></section>

        <div x-show="editOpen || careOpen || ministryOpen" class="fixed inset-0 z-40 bg-slate-950/40" @click="editOpen = false; careOpen = false; ministryOpen = false"></div>
        <aside x-show="editOpen" class="fixed inset-y-0 right-0 z-50 w-full max-w-lg overflow-y-auto bg-white p-6 shadow-2xl"><div class="mb-5 flex justify-between"><h2 class="text-lg font-semibold text-slate-950">Edit Member</h2><button @click="editOpen = false"><i data-lucide="x" class="size-5"></i></button></div>@include('members.partials.form', ['action' => route('members.update', $member), 'method' => 'PUT', 'member' => $profile])</aside>
        <aside x-show="careOpen" class="fixed inset-y-0 right-0 z-50 w-full max-w-md overflow-y-auto bg-white p-6 shadow-2xl"><div class="mb-5 flex justify-between"><h2 class="text-lg font-semibold text-slate-950">Create Care Task</h2><button @click="careOpen = false"><i data-lucide="x" class="size-5"></i></button></div><form method="POST" action="{{ route('care-tasks.store') }}" class="space-y-4">@csrf<input type="hidden" name="member_id" value="{{ $member->opaqueId() }}"><select name="type" class="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"><option>Counseling</option><option>Visitation</option><option>Prayer Request</option><option>Membership</option><option>Family Care</option><option>Hospital Visit</option></select><select name="priority" class="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option><option value="low">Low</option></select><select name="status" class="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="pending">Pending</option><option value="assigned">Assigned</option><option value="in-progress">In Progress</option></select><input name="next_action" class="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" placeholder="Next action"><textarea name="notes" rows="4" class="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" placeholder="Notes"></textarea><button class="w-full rounded-lg bg-violet-600 px-4 py-2.5 text-sm font-medium text-white">Create Task</button></form></aside>
        <aside x-show="ministryOpen" class="fixed inset-y-0 right-0 z-50 w-full max-w-md overflow-y-auto bg-white p-6 shadow-2xl"><div class="mb-5 flex justify-between"><h2 class="text-lg font-semibold text-slate-950">Assign Ministry</h2><button @click="ministryOpen = false"><i data-lucide="x" class="size-5"></i></button></div><form method="POST" action="{{ route('members.assign-ministry', $member) }}" class="space-y-4">@csrf<select name="ministry_id" required class="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm">@foreach($ministries as $ministry)<option value="{{ $ministry->id }}">{{ $ministry->name }}</option>@endforeach</select><button class="w-full rounded-lg bg-violet-600 px-4 py-2.5 text-sm font-medium text-white">Assign Ministry</button></form></aside>
    </div>
</x-app-layout>
