<x-app-layout title="Media Library" :breadcrumbs="$breadcrumbs">
    <div class="mx-auto max-w-[1500px] space-y-6">
        <div class="flex flex-col gap-4 rounded-3xl bg-gradient-to-br from-violet-700 via-indigo-700 to-slate-950 px-6 py-8 text-white shadow-xl shadow-violet-100 sm:flex-row sm:items-end sm:justify-between sm:px-10"><div><p class="text-xs font-black uppercase tracking-[.18em] text-violet-200">Website Studio / Media</p><h1 class="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Central media library</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-violet-100">Upload images once, reuse them across sections, and keep your website assets organized.</p></div><a href="{{ route('website-studio.sections') }}" class="rounded-xl bg-white/10 px-4 py-3 text-sm font-bold text-white ring-1 ring-white/25 hover:bg-white/20">Back to sections</a></div>
        @if (session('status'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ session('status') }}</div>@endif
        @if ($errors->any())<div class="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{{ $errors->first() }}</div>@endif
        <section class="dashboard-card p-5"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-lg font-bold text-slate-950">Upload a reusable image</h2><p class="mt-1 text-sm text-slate-500">Images added here can be copied into any image URL field in Website Studio.</p></div><form method="POST" action="{{ route('website-studio.media.upload') }}" enctype="multipart/form-data" class="flex flex-wrap items-center gap-3">@csrf<input type="file" name="media" accept="image/*" required class="rounded-xl border border-dashed border-violet-300 bg-violet-50 px-3 py-2 text-xs text-slate-600"><button class="rounded-xl bg-violet-600 px-4 py-3 text-sm font-bold text-white shadow-lg shadow-violet-200 hover:bg-violet-700">Upload image</button></form></div></section>
        <section class="dashboard-card p-5"><div class="mb-5 flex items-center justify-between"><div><h2 class="text-lg font-bold text-slate-950">Your images</h2><p class="mt-1 text-sm text-slate-500">{{ $media->count() }} image(s) available for reuse.</p></div><span class="rounded-full bg-violet-50 px-3 py-1 text-xs font-bold text-violet-700">Reusable assets</span></div>@if ($media->isNotEmpty())<div class="grid gap-5 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5">@foreach ($media as $item)<article class="group overflow-hidden rounded-2xl border border-slate-200 bg-white"><div class="aspect-[4/3] overflow-hidden bg-slate-100"><img src="{{ asset('storage/'.ltrim($item['path'], '/')) }}" alt="{{ $item['name'] ?? 'Website image' }}" class="h-full w-full object-cover transition duration-300 group-hover:scale-105"></div><div class="space-y-3 p-3"><p class="truncate text-xs font-bold text-slate-800" title="{{ $item['name'] ?? '' }}">{{ $item['name'] ?? 'Image' }}</p><input readonly value="{{ asset('storage/'.ltrim($item['path'], '/')) }}" onclick="this.select()" class="w-full rounded-lg border border-slate-200 bg-slate-50 px-2 py-2 text-[10px] text-slate-500"><form method="POST" action="{{ route('website-studio.media.delete', $item['id']) }}" onsubmit="return confirm('Delete this image from the media library?')">@csrf @method('DELETE')<button class="w-full rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-600 hover:bg-rose-50">Delete image</button></form></div></article>@endforeach</div>@else<div class="rounded-2xl border border-dashed border-violet-200 bg-violet-50/50 px-6 py-16 text-center"><div class="mx-auto grid size-14 place-items-center rounded-2xl bg-violet-100 text-2xl text-violet-600">✦</div><h3 class="mt-4 text-lg font-bold text-slate-900">Your media library is empty</h3><p class="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">Upload your first image above. It will be available to reuse throughout your church website.</p></div>@endif</section>
    </div>
</x-app-layout>
