<x-app-layout title="New Section" :breadcrumbs="$breadcrumbs">
    <link rel="stylesheet" href="{{ asset('css/website-studio/section-builder.css') }}?v={{ filemtime(public_path('css/website-studio/section-builder.css')) }}">
    <div class="section-create-page mx-auto max-w-[1500px] space-y-6">
        <a href="{{ route('website-studio.media') }}" class="inline-flex rounded-xl border border-violet-200 bg-violet-50 px-4 py-2 text-xs font-bold text-violet-700 hover:bg-violet-100">Open central media library →</a>
        <div class="rounded-3xl bg-gradient-to-br from-violet-700 via-indigo-700 to-slate-950 px-6 py-8 text-white shadow-xl shadow-violet-100 sm:px-10"><div class="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-black uppercase tracking-[.18em] text-violet-200">Website Studio / Reusable sections</p><h1 class="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Create a new section</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-violet-100">Build a reusable section once, then place it on as many pages as you need.</p></div><a href="{{ route('website-studio.sections') }}" class="rounded-xl bg-white/10 px-4 py-3 text-sm font-bold text-white ring-1 ring-white/25 hover:bg-white/20">Cancel</a></div></div>
        @if ($errors->any())<div class="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{{ $errors->first() }}</div>@endif
        <form method="POST" action="{{ route('website-studio.sections.store') }}" enctype="multipart/form-data" class="space-y-5">@csrf
            <div class="grid gap-5 lg:grid-cols-[minmax(0,1fr)_320px]">
                <section class="dashboard-card space-y-4"><div><h2 class="text-lg font-bold text-slate-950">1. Add your content</h2><p class="mt-1 text-sm text-slate-500">Give the section a name, then design its columns visually.</p></div><div class="grid gap-4 sm:grid-cols-2"><label><span class="field-label">Section title</span><input name="title" required class="field-input" placeholder="A place to belong"></label><label><span class="field-label">Small label <span class="optional">(optional)</span></span><input name="eyebrow" class="field-input" placeholder="Your next step"></label></div><label><span class="field-label">Intro text <span class="optional">(optional)</span></span><textarea name="body" rows="4" class="field-input" placeholder="Write a short introduction..."></textarea></label><div class="builder-shell" data-builder><div class="mb-2 text-xs font-bold text-slate-700">2. Design your columns and widgets</div><div data-builder-canvas></div><input type="hidden" name="components" data-components-output><script type="application/json" data-components-seed>[]</script></div></section>
                <aside class="space-y-5"><section class="dashboard-card space-y-4"><div><h2 class="text-base font-bold text-slate-950">3. Publish location</h2><p class="mt-1 text-xs leading-5 text-slate-500">Choose the pages that should display this section.</p></div><div class="space-y-2">@foreach ($pages as $page)<label class="flex items-start gap-2 rounded-lg border border-slate-100 px-3 py-2 text-sm font-semibold text-slate-700"><input type="checkbox" name="page_slugs[]" value="{{ $page->slug }}" @checked($page->slug === 'home') class="mt-1 rounded border-slate-300 text-violet-600"><span>{{ $page->title }}</span></label>@endforeach</div></section><section class="dashboard-card space-y-4"><h2 class="text-base font-bold text-slate-950">Optional section media</h2><label><span class="field-label">Image URL</span><input name="image_url" class="field-input" placeholder="https://..."></label><label><span class="field-label">Upload image</span><input type="file" name="image_file" accept="image/*" class="field-input"></label><label><span class="field-label">Video URL</span><input name="video_url" class="field-input" placeholder="https://..."></label><label><span class="field-label">Upload video</span><input type="file" name="video_file" accept="video/mp4,video/webm,video/ogg" class="field-input"></label></section></aside>
            </div>
            <div class="flex justify-end"><button class="rounded-xl bg-violet-600 px-7 py-3 text-sm font-bold text-white shadow-lg shadow-violet-200 hover:bg-violet-700">Create section</button></div>
        </form>
    </div>
    <style>
        .section-create-page .bg-gradient-to-br{background:#fff!important;color:#0f172a!important;padding:0!important;box-shadow:none!important}.section-create-page .bg-gradient-to-br p{color:#64748b!important}.section-create-page .bg-gradient-to-br a{border:1px solid #e2e8f0;background:#fff;color:#334155;box-shadow:0 4px 12px rgb(15 23 42 / .04)}
        .section-create-page .dashboard-card{border:1px solid #e5e7eb;border-radius:1rem;background:#fff;box-shadow:0 8px 24px rgb(15 23 42 / .04);padding:1.25rem}.section-create-page .dashboard-card>div:first-child h2{letter-spacing:-.02em}.section-create-page .builder-shell{border:1px solid #ddd6fe;border-radius:1rem;background:#fbfaff;padding:1rem}.section-create-page input[type=file]{min-height:4rem;border:1px dashed #c4b5fd;border-radius:.8rem;background:#fafaff;padding:.75rem;color:#64748b;font-size:.75rem}.section-create-page input[type=file]::file-selector-button{margin-right:.6rem;border:0;border-radius:.5rem;background:#ede9fe;padding:.45rem .65rem;color:#6d28d9;font-size:.72rem;font-weight:800}.section-create-page aside .dashboard-card{box-shadow:0 8px 24px rgb(15 23 42 / .035)}
        .section-create-page .dashboard-card:first-child>div:first-child:before{content:'1';display:inline-grid;place-items:center;width:2rem;height:2rem;margin-bottom:.7rem;border-radius:.65rem;background:#ede9fe;color:#6d28d9;font-size:.9rem;font-weight:900}.section-create-page .builder-shell:before{content:'2';display:inline-grid;place-items:center;width:2rem;height:2rem;margin-bottom:.7rem;border-radius:.65rem;background:#ede9fe;color:#6d28d9;font-size:.9rem;font-weight:900}.section-create-page aside .dashboard-card:first-child:before{content:'3';display:inline-grid;place-items:center;width:2rem;height:2rem;margin-bottom:.7rem;border-radius:.65rem;background:#ede9fe;color:#6d28d9;font-size:.9rem;font-weight:900}.section-create-page aside .dashboard-card:last-child:before{content:'+';display:inline-grid;place-items:center;width:2rem;height:2rem;margin-bottom:.7rem;border-radius:.65rem;background:#ede9fe;color:#6d28d9;font-size:.9rem;font-weight:900}
        .field-label{display:block;margin-bottom:.35rem;font-size:.72rem;font-weight:700;color:#475569}.field-input{display:block;width:100%;border-radius:.7rem;border:1px solid #e2e8f0;background:#fff;padding:.65rem .75rem;font-size:.875rem;color:#0f172a;outline:none}.field-input:focus{border-color:#8b5cf6;box-shadow:0 0 0 3px rgb(139 92 246 / .12)}.optional{font-weight:400;color:#94a3b8}
    </style>
    <script src="{{ asset('js/website-studio/section-builder.js') }}?v={{ filemtime(public_path('js/website-studio/section-builder.js')) }}" defer></script>
</x-app-layout>
