<x-app-layout title="Finance Overview" :breadcrumbs="$breadcrumbs">
    <div class="space-y-5">
        <div class="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
            <div class="flex items-center gap-4"><div class="grid size-14 place-items-center rounded-xl bg-emerald-100 text-emerald-600"><i data-lucide="badge-dollar-sign" class="size-7"></i></div><div><h1 class="text-2xl font-semibold text-slate-950">Finance Overview</h1><p class="text-sm text-slate-500">Giving totals, fund mix, payment methods, and recent donation activity.</p></div></div>
            <div class="flex flex-wrap gap-2"><a href="{{ route('finance.index') }}" class="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700"><i data-lucide="list" class="size-4"></i>Ledger</a><a href="{{ route('finance.donations.create') }}" class="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white"><i data-lucide="plus" class="size-4"></i>Record Donation</a></div>
        </div>
        <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
            <x-stat-card :metric="['label' => 'This Month', 'value' => $stats['month'], 'change' => null, 'period' => 'received giving', 'icon' => 'calendar-days', 'color' => 'emerald', 'route' => 'finance.index']" />
            <x-stat-card :metric="['label' => 'This Year', 'value' => $stats['year'], 'change' => null, 'period' => 'year to date', 'icon' => 'chart-column', 'color' => 'purple', 'route' => 'finance.index']" />
            <x-stat-card :metric="['label' => 'Transactions', 'value' => number_format($stats['count']), 'change' => null, 'period' => 'donation records', 'icon' => 'receipt', 'color' => 'orange', 'route' => 'finance.index']" />
            <x-stat-card :metric="['label' => 'Average Gift', 'value' => $stats['average'], 'change' => null, 'period' => 'per record', 'icon' => 'wallet', 'color' => 'teal', 'route' => 'finance.index']" />
        </div>
        <div class="grid gap-4 xl:grid-cols-[1fr_360px]">
            <section class="dashboard-card p-0"><div class="border-b border-slate-100 p-4"><h2 class="text-base font-semibold text-slate-950">Recent Donations</h2></div><div class="overflow-x-auto"><table class="table-compact min-w-[760px]"><thead><tr><th>Reference</th><th>Date</th><th>Member</th><th>Fund</th><th>Amount</th><th class="text-right">Action</th></tr></thead><tbody>@forelse($recentDonations as $donation)<tr><td class="font-semibold text-slate-950">{{ $donation->reference }}</td><td>{{ $donation->received_at?->format('M d, Y h:i A') }}</td><td>{{ $donation->member ? $donation->member->first_name.' '.$donation->member->last_name : 'Anonymous' }}</td><td>{{ $donation->fund?->name ?? 'Unassigned' }}</td><td class="font-semibold">{{ $donation->currency }} {{ number_format((float) $donation->amount, 2) }}</td><td class="text-right"><a href="{{ route('finance.donations.edit', $donation) }}" class="text-sm font-semibold text-violet-600">Edit</a></td></tr>@empty<tr><td colspan="6" class="px-4 py-12"><x-empty-state icon="badge-dollar-sign" title="No donations yet" message="Record the first donation to start the ledger." /></td></tr>@endforelse</tbody></table></div></section>
            <aside class="space-y-4"><section class="dashboard-card"><h2 class="mb-4 text-base font-semibold text-slate-950">Giving by Fund</h2><div class="space-y-3">@forelse($fundRows as $row)<div class="flex justify-between gap-3 text-sm"><span class="truncate text-slate-600">{{ $row['label'] }}</span><span class="font-semibold">{{ $currency }} {{ number_format($row['value'], 2) }}</span></div>@empty<div class="text-sm text-slate-500">No fund giving yet.</div>@endforelse</div></section><section class="dashboard-card"><h2 class="mb-4 text-base font-semibold text-slate-950">Payment Methods</h2><div class="space-y-3">@forelse($methodRows as $row)<div class="flex justify-between text-sm"><span class="text-slate-600">{{ $row['label'] }}</span><span class="font-semibold">{{ number_format($row['value']) }}</span></div>@empty<div class="text-sm text-slate-500">No method data yet.</div>@endforelse</div></section></aside>
        </div>
    </div>
</x-app-layout>
