<?php

return [
    'permissions' => [
        'view dashboard',
        'manage users',
        'manage roles',
        'manage permissions',
        'view audit log',
        'manage members',
        'manage attendance',
        'manage finance',
        'view finance',
        'record finance entries',
        'view ministry finance',
        'record ministry contributions',
        'manage events',
        'manage studio',
        'manage media',
        'manage prayer',
        'manage communications',
        'manage volunteers',
        'manage ministries',
        'manage campuses',
        'manage assets',
        'manage facilities',
        'manage bookstore',
        'manage youth',
        'manage counselling',
        'view leadership reports',
        'manage feedback',
        'manage staff',
        'view reports',
        'manage workflows',
        'manage settings',
    ],

    'roles' => [
        'Super Administrator' => ['*'],
        'Church Administrator' => ['view dashboard', 'manage users', 'manage roles', 'manage permissions', 'view audit log', 'manage members', 'manage attendance', 'manage events', 'manage studio', 'manage communications', 'manage ministries', 'manage campuses', 'manage staff', 'view reports', 'manage settings'],
        'Senior Pastor' => ['view dashboard', 'manage members', 'manage attendance', 'manage prayer', 'manage communications', 'manage ministries', 'manage campuses', 'view finance', 'view leadership reports', 'manage feedback', 'view reports'],
        'Branch Pastor' => ['view dashboard', 'manage members', 'manage attendance', 'manage prayer', 'manage communications', 'manage ministries', 'view finance', 'view leadership reports', 'manage feedback'],
        'Finance Officer' => ['view dashboard', 'manage finance', 'view finance', 'record finance entries', 'view reports'],
        'Membership Officer' => ['view dashboard', 'manage members', 'manage attendance', 'manage communications'],
        'Asset Manager' => ['view dashboard', 'manage assets', 'manage facilities', 'view reports'],
        'Book Store Manager' => ['view dashboard', 'manage bookstore', 'view reports'],
        'Ministry Leader' => ['view dashboard', 'manage volunteers', 'manage ministries', 'manage events', 'manage communications', 'view ministry finance', 'record ministry contributions'],
        'Staff' => ['view dashboard'],
        'Viewer' => ['view dashboard'],
    ],
];
