<?php

return [
    'permissions' => [
        'view dashboard',
        'use messages',
        'use bible',
        'manage bible plans',
        'manage bible translations',
        'send messages',
        'create message groups',
        'manage message participants',
        'forward messages',
        'export message history',
        'view sensitive messages',
        'administer messages',
        'manage users',
        'manage roles',
        'manage permissions',
        'view audit log',
        'manage members',
        'manage attendance',
        'manage finance',
        'view finance',
        'record finance entries',
        'view ministry finance',
        'record ministry contributions',
        'request financial assistance',
        'request cross-campus financial assistance',
        'approve financial assistance',
        'manage financial assistance',
        'manage events',
        'manage studio',
        'manage media',
        'manage prayer',
        'manage communications',
        'manage volunteers',
        'manage ministries',
        'manage campuses',
        'manage assets',
        'manage facilities',
        'manage bookstore',
        'manage youth',
        'manage counselling',
        'view leadership reports',
        'review leadership reports',
        'manage feedback',
        'manage staff',
        'view reports',
        'manage workflows',
        'manage settings',
    ],

    'roles' => [
        'Super Administrator' => ['*'],
        'Church Administrator' => ['view dashboard', 'use messages', 'use bible', 'manage bible plans', 'manage bible translations', 'send messages', 'create message groups', 'manage message participants', 'forward messages', 'export message history', 'view sensitive messages', 'administer messages', 'manage users', 'manage roles', 'manage permissions', 'view audit log', 'manage members', 'manage attendance', 'manage events', 'manage studio', 'manage communications', 'manage ministries', 'manage campuses', 'manage staff', 'view leadership reports', 'review leadership reports', 'view reports', 'manage settings', 'request financial assistance', 'request cross-campus financial assistance', 'approve financial assistance', 'manage financial assistance'],
        'Senior Pastor' => ['view dashboard', 'use messages', 'use bible', 'send messages', 'create message groups', 'manage message participants', 'forward messages', 'export message history', 'view sensitive messages', 'manage members', 'manage attendance', 'manage prayer', 'manage communications', 'manage ministries', 'manage campuses', 'view finance', 'view leadership reports', 'review leadership reports', 'manage feedback', 'view reports', 'request financial assistance', 'request cross-campus financial assistance', 'approve financial assistance'],
        'Branch Pastor' => ['view dashboard', 'use messages', 'use bible', 'send messages', 'create message groups', 'manage message participants', 'forward messages', 'view sensitive messages', 'manage members', 'manage attendance', 'manage prayer', 'manage communications', 'manage ministries', 'view finance', 'view leadership reports', 'review leadership reports', 'manage feedback', 'request financial assistance', 'request cross-campus financial assistance', 'approve financial assistance'],
        'Finance Officer' => ['view dashboard', 'use messages', 'use bible', 'send messages', 'forward messages', 'manage finance', 'view finance', 'record finance entries', 'view reports', 'request financial assistance', 'request cross-campus financial assistance', 'approve financial assistance', 'manage financial assistance'],
        'Membership Officer' => ['view dashboard', 'use messages', 'use bible', 'send messages', 'forward messages', 'manage members', 'manage attendance', 'manage communications'],
        'Asset Manager' => ['view dashboard', 'use messages', 'use bible', 'send messages', 'forward messages', 'manage assets', 'manage facilities', 'view reports'],
        'Book Store Manager' => ['view dashboard', 'use messages', 'use bible', 'send messages', 'forward messages', 'manage bookstore', 'view reports'],
        'Ministry Leader' => ['view dashboard', 'use messages', 'use bible', 'send messages', 'create message groups', 'manage message participants', 'forward messages', 'manage volunteers', 'manage ministries', 'manage events', 'manage communications', 'view ministry finance', 'record ministry contributions', 'request financial assistance'],
        'Staff' => ['view dashboard', 'use messages', 'use bible', 'send messages', 'forward messages'],
        'Member' => ['use messages', 'use bible'],
        'Viewer' => ['view dashboard', 'use messages', 'use bible'],
    ],
];
