<?php

$planned = [
    'members.index' => ['Member registration', 'Member profiles', 'Membership status', 'Family relationships', 'Communication history', 'Document storage', 'Attendance history', 'Giving history'],
    'families.index' => ['Household profiles', 'Family links', 'Care notes', 'Anniversary tracking', 'Communication preferences'],
    'programs.index' => ['Program planning', 'Events under programs', 'Session scheduling', 'Calendar publishing', 'Attendance workflows'],
    'calendar.index' => ['Shared session calendar', 'Meeting links', 'Venue bookings', 'Attendance windows', 'Schedule visibility'],
    'meetings.index' => ['Physical meetings', 'Online rooms', 'Provider links', 'Join tracking', 'Meeting setup'],
    'attendance.index' => ['Attendance sessions', 'Manual check-in', 'QR code', 'Geolocation', 'Kiosk', 'Face capture', 'Online auto attendance', 'Final records'],
    'finance.index' => ['Donation entry', 'Fund accounting', 'Giving statements', 'Campaign tracking', 'Finance exports'],
    'events.index' => ['Event planning', 'Registration', 'Room booking', 'Volunteer rosters', 'Calendar subscriptions'],
    'sermons.index' => ['Sermon library', 'Media uploads', 'Series planning', 'Engagement tracking', 'Publishing workflow'],
    'prayer-requests.index' => ['Prayer intake', 'Confidential routing', 'Follow-up tasks', 'Answered prayer history'],
    'communications.index' => ['Email campaigns', 'SMS groups', 'Announcements', 'Templates', 'Delivery reports'],
    'volunteers.index' => ['Volunteer onboarding', 'Skill matching', 'Rosters', 'Availability', 'Serving history'],
    'ministries.index' => ['Ministry directories', 'Department goals', 'Leaders', 'Activities', 'Impact reports'],
    'campuses.index' => ['Campus profiles', 'Regional leadership', 'Attendance summaries', 'Operational status'],
    'assets.index' => ['Asset catalog', 'Maintenance schedules', 'Assignments', 'Depreciation notes', 'Condition tracking'],
    'facilities.index' => ['Room inventory', 'Facility requests', 'Bookings', 'Maintenance tickets', 'Vendor notes'],
    'bookstore.index' => ['Product catalog', 'Stock control', 'Orders', 'Revenue reports', 'Low-stock alerts'],
    'children-youth.index' => ['Class rosters', 'Guardian check-in', 'Age groups', 'Consent records', 'Safety notes'],
    'counselling.index' => ['Session scheduling', 'Care plans', 'Confidential notes', 'Referrals', 'Follow-up reminders'],
    'leadership-reports.index' => ['Leadership KPIs', 'Pastoral dashboards', 'Branch scorecards', 'Task reporting'],
    'feedback.index' => ['Surveys', 'Complaints', 'Suggestions', 'Sentiment summaries', 'Resolution tracking'],
    'staff.index' => ['Staff profiles', 'Departments', 'Contracts', 'Leave tracking', 'Performance reviews'],
    'reports.index' => ['Custom reports', 'Saved views', 'Exports', 'Scheduled reports', 'Analytics dashboards'],
    'workflows.index' => ['Approval chains', 'Task queues', 'Status tracking', 'Audit logs', 'Escalations'],
    'settings.index' => ['Church profile', 'Branding', 'Campuses', 'Currency', 'Timezone', 'Notifications', 'Security', 'Roles and permissions', 'Integrations', 'Backups', 'Audit logs'],
];

return [
    [
        'label' => 'Dashboard',
        'route' => 'dashboard',
        'icon' => 'layout-dashboard',
        'permission' => 'view dashboard',
        'implemented' => true,
    ],
    ['label' => 'Members', 'route' => 'members.index', 'icon' => 'users', 'permission' => 'manage members', 'planned' => $planned['members.index']],
    ['label' => 'Families', 'route' => 'families.index', 'icon' => 'users-round', 'permission' => 'manage members', 'planned' => $planned['families.index']],
    [
        'label' => 'Programs & Attendance',
        'route' => 'programs.index',
        'icon' => 'calendar-clock',
        'children' => [
            ['label' => 'Programs', 'route' => 'programs.index', 'icon' => 'layout-list', 'permission' => 'manage events', 'planned' => $planned['programs.index']],
            ['label' => 'Events', 'route' => 'events.index', 'icon' => 'calendar-plus', 'permission' => 'manage events', 'planned' => $planned['events.index'], 'active_routes' => ['programs.events', 'event-sessions.index']],
            ['label' => 'Calendar', 'route' => 'calendar.index', 'icon' => 'calendar-days', 'permission' => 'manage events', 'planned' => $planned['calendar.index']],
            ['label' => 'Meetings', 'route' => 'meetings.index', 'icon' => 'video', 'permission' => 'manage events', 'planned' => $planned['meetings.index'], 'active_routes' => ['event-sessions.meeting', 'meetings.rooms.show', 'meeting-integrations.index']],
            ['label' => 'Attendance', 'route' => 'attendance.index', 'icon' => 'clipboard-check', 'permission' => 'manage attendance', 'planned' => $planned['attendance.index'], 'active_routes' => ['event-sessions.attendance', 'attendance.methods', 'attendance.check-in', 'attendance.records.show']],
        ],
    ],
    ['label' => 'Giving & Finance', 'route' => 'finance.index', 'icon' => 'badge-dollar-sign', 'permission' => 'manage finance', 'planned' => $planned['finance.index']],
    ['label' => 'Sermons & Media', 'route' => 'sermons.index', 'icon' => 'monitor-play', 'permission' => 'manage media', 'planned' => $planned['sermons.index']],
    ['label' => 'Prayer Requests', 'route' => 'prayer-requests.index', 'icon' => 'hand-heart', 'permission' => 'manage prayer', 'badge' => '23', 'planned' => $planned['prayer-requests.index']],
    [
        'label' => 'Communications',
        'route' => 'communications.index',
        'icon' => 'message-square',
        'permission' => 'manage communications',
        'children' => [
            ['label' => 'Overview', 'route' => 'communications.index', 'icon' => 'layout-dashboard', 'permission' => 'manage communications'],
            ['label' => 'Notifications', 'route' => 'communications.notifications', 'icon' => 'bell', 'permission' => 'manage communications'],
            ['label' => 'Templates', 'route' => 'communications.templates', 'icon' => 'file-search', 'permission' => 'manage communications'],
            ['label' => 'Scheduled Messages', 'route' => 'communications.scheduled', 'icon' => 'calendar-clock', 'permission' => 'manage communications'],
            ['label' => 'Bulk Messaging', 'route' => 'communications.bulk', 'icon' => 'send', 'permission' => 'manage communications'],
            ['label' => 'Delivery Logs', 'route' => 'communications.delivery-logs', 'icon' => 'clipboard-list', 'permission' => 'manage communications'],
            ['label' => 'Preferences', 'route' => 'communications.preferences', 'icon' => 'sliders-horizontal', 'permission' => 'manage communications'],
        ],
    ],
    ['label' => 'Volunteer Management', 'route' => 'volunteers.index', 'icon' => 'network', 'permission' => 'manage volunteers', 'planned' => $planned['volunteers.index']],
    ['label' => 'Ministries', 'route' => 'ministries.index', 'icon' => 'landmark', 'permission' => 'manage ministries', 'planned' => $planned['ministries.index']],
    ['label' => 'Branches & Campuses', 'route' => 'campuses.index', 'icon' => 'map-pin', 'permission' => 'manage campuses', 'planned' => $planned['campuses.index']],
    ['label' => 'Asset Inventory', 'route' => 'assets.index', 'icon' => 'package-check', 'permission' => 'manage assets', 'planned' => $planned['assets.index']],
    ['label' => 'Facilities', 'route' => 'facilities.index', 'icon' => 'building-2', 'permission' => 'manage facilities', 'planned' => $planned['facilities.index']],
    ['label' => 'Book Store', 'route' => 'bookstore.index', 'icon' => 'book-open', 'permission' => 'manage bookstore', 'planned' => $planned['bookstore.index']],
    ['label' => 'Child & Youth', 'route' => 'children-youth.index', 'icon' => 'baby', 'permission' => 'manage youth', 'planned' => $planned['children-youth.index']],
    ['label' => 'Counselling', 'route' => 'counselling.index', 'icon' => 'circle-help', 'permission' => 'manage counselling', 'planned' => $planned['counselling.index']],
    ['label' => 'Pastor & Leadership Reports', 'route' => 'leadership-reports.index', 'icon' => 'gauge', 'permission' => 'view leadership reports', 'implemented' => true],
    ['label' => 'Feedback System', 'route' => 'feedback.index', 'icon' => 'message-square-text', 'permission' => 'manage feedback', 'planned' => $planned['feedback.index']],
    ['label' => 'HR & Staff', 'route' => 'staff.index', 'icon' => 'user-round-cog', 'permission' => 'manage staff', 'planned' => $planned['staff.index']],
    ['label' => 'Reports & Analytics', 'route' => 'reports.index', 'icon' => 'chart-column', 'permission' => 'view reports', 'planned' => $planned['reports.index']],
    ['label' => 'Workflow & Approvals', 'route' => 'workflows.index', 'icon' => 'git-branch', 'permission' => 'manage workflows', 'badge' => '5', 'planned' => $planned['workflows.index']],
    [
        'label' => 'Administration',
        'route' => 'users.index',
        'icon' => 'shield-check',
        'permission' => 'manage users',
        'children' => [
            ['label' => 'User Management', 'route' => 'users.index', 'icon' => 'users', 'permission' => 'manage users'],
            ['label' => 'Roles & Permissions', 'route' => 'roles.index', 'icon' => 'shield-check', 'permission' => 'manage roles'],
            ['label' => 'Churches & Campuses', 'route' => 'campuses.index', 'icon' => 'landmark', 'permission' => 'manage campuses'],
            ['label' => 'System Settings', 'route' => 'settings.index', 'icon' => 'settings', 'permission' => 'manage settings'],
            ['label' => 'Meeting Integrations', 'route' => 'meeting-integrations.index', 'icon' => 'radio-tower', 'permission' => 'manage settings'],
            ['label' => 'Communication Integrations', 'route' => 'communications.integrations', 'icon' => 'webhook', 'permission' => 'manage settings'],
            ['label' => 'Module Management', 'route' => 'modules.index', 'icon' => 'layout-grid', 'permission' => 'manage settings'],
            ['label' => 'Developer Hub', 'route' => 'developer-hub.index', 'icon' => 'book-open', 'permission' => 'manage settings'],
            ['label' => 'Audit Logs', 'route' => 'audit-logs.index', 'icon' => 'clipboard-list', 'permission' => 'view audit log'],
        ],
    ],
];
