<x-app-layout title="AI Reports & Analytics Copilot" :breadcrumbs="$breadcrumbs">
    <style>
        .copilot-markdown h1,.copilot-markdown h2,.copilot-markdown h3{margin:1rem 0 .45rem;color:#172033;font-weight:800;line-height:1.3}
        .copilot-markdown h1{font-size:1.05rem}.copilot-markdown h2{font-size:.95rem}.copilot-markdown h3{font-size:.875rem}
        .copilot-markdown p{margin:.45rem 0}.copilot-markdown ul,.copilot-markdown ol{margin:.55rem 0;padding-left:1.35rem}
        .copilot-markdown ul{list-style:disc}.copilot-markdown ol{list-style:decimal}.copilot-markdown li{margin:.25rem 0;padding-left:.15rem}
        .copilot-markdown strong{color:#172033;font-weight:800}.copilot-markdown em{color:#64748b}
        .copilot-markdown code{border-radius:.35rem;background:#f1f5f9;padding:.12rem .3rem;font-size:.85em;color:#5b21b6}
        .copilot-markdown blockquote{margin:.65rem 0;border-left:3px solid #8b5cf6;padding-left:.75rem;color:#64748b}
        .copilot-markdown a{color:#6d28d9;text-decoration:underline}.copilot-markdown hr{margin:1rem 0;border-color:#e2e8f0}
        .copilot-markdown table{width:100%;margin:.75rem 0;border-collapse:separate;border-spacing:0;overflow:hidden;border:1px solid #e2e8f0;border-radius:.65rem;font-size:.78rem}
        .copilot-markdown th{background:#f8fafc;color:#334155;font-weight:800;text-align:left}
        .copilot-markdown th,.copilot-markdown td{border-bottom:1px solid #e2e8f0;padding:.55rem .65rem;vertical-align:top}
        .copilot-markdown tr:last-child td{border-bottom:0}.copilot-markdown tbody tr:nth-child(even){background:#fcfcff}
        .copilot-markdown{overflow-wrap:anywhere}.copilot-markdown table{display:block;overflow-x:auto;white-space:nowrap}
        [x-ref="messages"]{min-height:0;scroll-behavior:smooth;scrollbar-color:#cbd5e1 #f8fafc;scrollbar-width:thin}
        [x-ref="messages"]::-webkit-scrollbar{width:8px}[x-ref="messages"]::-webkit-scrollbar-track{background:#f8fafc;border-radius:999px}[x-ref="messages"]::-webkit-scrollbar-thumb{background:#cbd5e1;border:2px solid #f8fafc;border-radius:999px}[x-ref="messages"]::-webkit-scrollbar-thumb:hover{background:#a78bfa}
    </style>
    <div class="mx-auto max-w-[1800px] space-y-5">
        <section class="relative overflow-hidden rounded-2xl border border-violet-100 bg-gradient-to-r from-violet-50 via-white to-sky-50 px-6 py-6 shadow-sm lg:px-8">
            <div class="absolute -right-10 -top-20 size-56 rounded-full bg-violet-200/25 blur-3xl"></div>
                    <div class="relative flex flex-col justify-between gap-5 lg:flex-row lg:items-center">
                <div class="flex items-center gap-4"><div class="grid size-16 shrink-0 place-items-center rounded-full border border-violet-200 bg-white text-violet-600 shadow-sm"><i data-lucide="chart-no-axes-combined" class="size-8"></i></div><div><div class="flex flex-wrap items-center gap-2"><h1 class="text-2xl font-black tracking-tight text-violet-950 lg:text-3xl">AI Reports & Analytics Copilot</h1><span class="rounded-md bg-violet-100 px-2 py-1 text-[10px] font-black uppercase tracking-wider text-violet-700">Focused</span></div><p class="mt-1 text-sm text-slate-600">Analyze verified church metrics, trends, comparisons, and leadership reports with permission-aware data.</p></div></div>
                <button type="button" x-data x-on:click="document.getElementById('copilot-question').focus()" class="inline-flex items-center justify-center gap-2 rounded-xl bg-violet-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-violet-200 transition hover:-translate-y-0.5 hover:bg-violet-700"><i data-lucide="message-square" class="size-4"></i> New conversation</button>
            </div>
        </section>

        <div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px_275px]" x-data="copilotChat()">
            <section x-show="conversations.length" class="dashboard-card col-span-full p-4"><div class="mb-3 flex items-center justify-between"><div><h2 class="font-bold text-slate-950">Saved conversations</h2><p class="mt-1 text-xs text-slate-500">Continue where you left off.</p></div><button type="button" x-on:click="clearConversation()" class="rounded-lg border border-violet-200 bg-violet-50 px-3 py-2 text-xs font-bold text-violet-700 hover:bg-violet-100">New conversation</button></div><div class="flex gap-2 overflow-x-auto pb-1"><template x-for="conversation in conversations" :key="conversation.id"><button type="button" x-on:click="loadConversation(conversation)" class="min-w-[220px] max-w-[300px] rounded-xl border px-3 py-2 text-left transition" :class="conversation.id === conversationId ? 'border-violet-300 bg-violet-50' : 'border-slate-100 bg-slate-50 hover:border-violet-200 hover:bg-violet-50'"><span class="block truncate text-xs font-bold text-slate-700" x-text="conversation.title"></span><span class="mt-1 block text-[10px] text-slate-400" x-text="conversation.updated || 'Saved conversation'"></span></button></template></div></section>
            <section class="dashboard-card flex h-[690px] min-h-0 flex-col overflow-hidden p-0">
                <div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><div class="flex items-center gap-2"><h2 class="font-bold text-slate-950">Analysis Conversation</h2><span class="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700"><span class="size-1.5 rounded-full bg-emerald-500"></span>Secure</span></div><p class="mt-1 text-xs text-slate-500">Only verified, permission-filtered report data is used.</p></div><button type="button" x-show="messages.length" x-on:click="clearConversation()" class="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-violet-600"><i data-lucide="trash-2" class="size-3.5"></i>Clear chat</button></div>
                <div class="flex-1 space-y-4 overflow-y-auto bg-slate-50/35 p-5" x-ref="messages"><template x-for="message in messages" :key="message.id"><div :class="message.role === 'user' ? 'ml-auto max-w-[92%]' : 'max-w-[96%]'" class="space-y-1"><div x-show="message.role === 'user'" class="flex items-center justify-end gap-2 text-[11px] font-bold text-violet-600"><span x-text="message.time"></span><span>You</span></div><div x-show="message.role === 'user'" class="rounded-xl bg-white px-4 py-3 text-sm font-medium text-slate-700 shadow-sm ring-1 ring-slate-100" x-text="message.text"></div><div x-show="message.role === 'assistant'" class="rounded-2xl border border-violet-100 bg-white p-4 shadow-sm"><div class="mb-3 flex items-center gap-2"><span class="grid size-7 place-items-center rounded-lg bg-violet-100 text-violet-600"><i data-lucide="sparkles" class="size-4"></i></span><span class="text-sm font-bold text-slate-900">Copilot</span><span class="ml-auto text-[10px] text-slate-400" x-text="message.time"></span></div><div class="copilot-markdown text-sm leading-6 text-slate-700" x-html="message.html"></div><div class="mt-3 flex items-center gap-2 border-t border-slate-100 pt-3 text-[10px] font-semibold text-slate-400"><i data-lucide="shield-check" class="size-3.5 text-emerald-500"></i> Verified, permission-filtered response</div></div></div></template><div x-show="!messages.length" class="grid min-h-[400px] place-items-center text-center"><div><div class="mx-auto grid size-16 place-items-center rounded-2xl bg-violet-100 text-violet-600"><i data-lucide="message-square" class="size-8"></i></div><h3 class="mt-4 text-lg font-bold text-slate-900">Start a conversation</h3><p class="mt-1 max-w-sm text-sm text-slate-500">Ask about your members, attendance, giving, reports, or follow-up work.</p></div></div><div x-show="loading" class="flex items-center gap-2 rounded-xl border border-violet-100 bg-white p-3 text-xs font-semibold text-slate-500 shadow-sm"><i data-lucide="loader-circle" class="size-4 animate-spin text-violet-600"></i> Checking permissions and preparing a verified answer…</div></div>
                <div id="ask" class="border-t border-slate-100 bg-white p-4"><div class="mb-3 flex flex-wrap gap-2">@foreach($suggestedQuestions as $suggestion)<button type="button" x-on:click="question = @js($suggestion); submit()" class="rounded-lg border border-violet-100 bg-violet-50 px-3 py-2 text-[11px] font-semibold text-violet-700 transition hover:border-violet-200 hover:bg-violet-100">{{ $suggestion }}</button>@endforeach</div><form x-on:submit.prevent="submit" class="flex items-center gap-2"><div class="relative min-w-0 flex-1"><i data-lucide="chart-no-axes-combined" class="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"></i><input id="copilot-question" x-model="question" :disabled="loading" class="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 pl-10 pr-4 text-sm outline-none transition placeholder:text-slate-400 focus:border-violet-400 focus:bg-white focus:ring-4 focus:ring-violet-100" placeholder="Ask for a report, trend, comparison, or analysis…" maxlength="500"></div><button type="submit" :disabled="loading" class="grid size-12 shrink-0 place-items-center rounded-xl bg-violet-600 text-white shadow-md shadow-violet-200 transition hover:-translate-y-0.5 hover:bg-violet-700 disabled:opacity-50"><i data-lucide="send" class="size-4"></i></button></form><p class="mt-2 text-center text-[10px] text-slate-400">Use verified results for decision support and review important conclusions.</p></div>
            </section>

            <aside class="space-y-5"><section class="dashboard-card"><div class="mb-4 flex items-center justify-between"><h2 class="font-bold text-slate-950">AI Provider</h2><span class="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700"><span class="size-1.5 rounded-full bg-emerald-500"></span>{{ $settings['configured'] ? 'Connected' : 'Needs setup' }}</span></div><div class="space-y-3"><label class="block text-[11px] font-bold text-slate-500">Provider<div class="mt-1 flex items-center justify-between rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 text-xs font-semibold text-slate-700">{{ $providers[$settings['provider']]['label'] ?? ucfirst($settings['provider']) }}<i data-lucide="chevron-down" class="size-3.5 text-slate-400"></i></div></label><label class="block text-[11px] font-bold text-slate-500">Model<div class="mt-1 flex items-center justify-between rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 text-xs font-semibold text-slate-700">{{ $settings['model'] }}<i data-lucide="chevron-down" class="size-3.5 text-slate-400"></i></div></label></div><a href="{{ route('ai-copilot.settings') }}" class="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-lg border border-violet-200 bg-violet-50 px-3 py-2.5 text-xs font-bold text-violet-700 hover:bg-violet-100"><i data-lucide="settings" class="size-3.5"></i> Manage provider & models</a></section><section class="dashboard-card"><h2 class="mb-4 font-bold text-slate-950">Safety & Controls</h2><div class="space-y-3 text-xs text-slate-600">@foreach(['Permission-aware data access','Role-based query restrictions','No data leaves your secure environment','Audit logging enabled','AI responses are filtered & verified','Sources are displayed for transparency'] as $item)<div class="flex items-start gap-2"><i data-lucide="circle-check" class="mt-0.5 size-4 shrink-0 text-emerald-500"></i><span>{{ $item }}</span></div>@endforeach</div></section><section class="dashboard-card"><h2 class="mb-4 font-bold text-slate-950">Suggested Questions</h2><div class="space-y-2">@foreach($suggestedQuestions as $suggestion)<button type="button" x-on:click="question = @js($suggestion); submit()" class="flex w-full items-center gap-2 rounded-lg border border-slate-100 bg-slate-50 px-3 py-2.5 text-left text-[11px] font-semibold text-slate-600 hover:border-violet-200 hover:bg-violet-50 hover:text-violet-700"><i data-lucide="sparkles" class="size-3.5 shrink-0 text-violet-500"></i><span>{{ $suggestion }}</span></button>@endforeach</div><button type="button" class="mt-3 w-full text-center text-xs font-bold text-violet-600 hover:text-violet-800">View all suggestions <i data-lucide="arrow-right" class="inline size-3.5"></i></button></section></aside>

            <aside class="space-y-5"><section class="dashboard-card"><div class="mb-4 flex items-center justify-between"><h2 class="font-bold text-slate-950">Recent Conversations</h2><button type="button" class="text-xs font-bold text-violet-600 hover:text-violet-800">View all</button></div><div class="space-y-2">@foreach($suggestedQuestions as $suggestion)<button type="button" x-on:click="question = @js($suggestion); submit()" class="group flex w-full items-start gap-2 rounded-lg border border-slate-100 p-3 text-left hover:border-violet-200 hover:bg-violet-50"><i data-lucide="chevron-right" class="mt-0.5 size-3.5 shrink-0 text-slate-400 group-hover:text-violet-600"></i><span class="text-xs font-semibold leading-5 text-slate-600 group-hover:text-violet-800">{{ $suggestion }}<small class="mt-1 block text-[10px] font-normal text-slate-400">Suggested query</small></span></button>@endforeach</div></section><section class="overflow-hidden rounded-xl border border-violet-100 bg-gradient-to-br from-violet-50 to-white p-5"><div class="flex items-center gap-2 text-violet-800"><i data-lucide="sparkles" class="size-4"></i><h2 class="font-bold">AI Copilot Tips</h2></div><p class="mt-3 text-xs leading-5 text-slate-600">Ask questions in natural language. The Copilot will securely query your data and provide accurate, permission-aware insights.</p><a href="#ask" class="mt-4 inline-flex items-center gap-1 text-xs font-bold text-violet-600 hover:text-violet-800">Ask a question <i data-lucide="arrow-right" class="size-3.5"></i></a></section></aside>
        </div>
    </div>
    @push('scripts')<script>function copilotChat(){return{question:'',loading:false,messages:@js($activeConversation['messages'] ?? []),conversations:@js($conversations),conversationId:@js($activeConversation['id'] ?? null),clearConversation(){this.messages=[];this.conversationId=null},loadConversation(conversation){this.conversationId=conversation.id;this.messages=conversation.messages||[];this.$nextTick(()=>this.$refs.messages.scrollTop=this.$refs.messages.scrollHeight)},time(){return new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})},submit(){if(!this.question.trim()||this.loading)return;const q=this.question.trim();this.messages.push({id:Date.now(),role:'user',text:q,time:this.time()});this.question='';this.loading=true;fetch('{{ route('ai-copilot.ask') }}',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content,'Accept':'text/html'},body:JSON.stringify({question:q,conversation_id:this.conversationId})}).then(r=>r.text()).then(html=>{const t=document.createElement('div');t.innerHTML=html;const answer=t.querySelector('[data-copilot-answer]');if(answer?.dataset.conversationId)this.conversationId=Number(answer.dataset.conversationId);this.messages.push({id:Date.now()+1,role:'assistant',html:answer?answer.querySelector('.copilot-markdown')?.innerHTML:'<p>The Copilot returned an empty answer.</p>',time:this.time()});const saved=this.conversations.find(conversation=>conversation.id===this.conversationId);if(saved){saved.messages=this.messages;saved.updated='Just now'}else{this.conversations.unshift({id:this.conversationId,title:q,updated:'Just now',messages:this.messages})}}).catch(()=>this.messages.push({id:Date.now()+1,role:'assistant',html:'<p>The Copilot could not complete this request. Please check the provider settings and try again.</p>',time:this.time()})).finally(()=>{this.loading=false;this.$nextTick(()=>this.$refs.messages.scrollTop=this.$refs.messages.scrollHeight)})}}}</script>@endpush
</x-app-layout>
