<x-app-layout title="Bookstore Overview" :breadcrumbs="$breadcrumbs">
    <div class="space-y-5">
        <div class="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
            <div class="flex items-center gap-4"><div class="grid size-14 place-items-center rounded-xl bg-amber-100 text-amber-600"><i data-lucide="book-open" class="size-7"></i></div><div><h1 class="text-2xl font-semibold text-slate-950">Bookstore Overview</h1><p class="text-sm text-slate-500">Product inventory, low stock, sales orders, and category value.</p></div></div>
            <div class="flex flex-wrap gap-2"><a href="{{ route('bookstore.index') }}" class="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700"><i data-lucide="list" class="size-4"></i>Catalog</a><a href="{{ route('bookstore.products.create') }}" class="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white"><i data-lucide="plus" class="size-4"></i>Add Product</a><a href="{{ route('bookstore.orders.create') }}" class="inline-flex items-center gap-2 rounded-lg border border-violet-200 bg-white px-4 py-2.5 text-sm font-semibold text-violet-700"><i data-lucide="shopping-cart" class="size-4"></i>New Order</a></div>
        </div>
        <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
            <x-stat-card :metric="['label' => 'Products', 'value' => number_format($stats['products']), 'change' => null, 'period' => 'catalog records', 'icon' => 'book-open', 'color' => 'purple', 'route' => 'bookstore.index']" />
            <x-stat-card :metric="['label' => 'Stock Units', 'value' => number_format($stats['stock']), 'change' => null, 'period' => 'available count', 'icon' => 'boxes', 'color' => 'teal', 'route' => 'bookstore.index']" />
            <x-stat-card :metric="['label' => 'Low Stock', 'value' => number_format($stats['low_stock']), 'change' => null, 'period' => 'needs reorder', 'icon' => 'triangle-alert', 'color' => 'orange', 'route' => 'bookstore.index']" />
            <x-stat-card :metric="['label' => 'Month Sales', 'value' => $stats['month_sales'], 'change' => null, 'period' => 'orders total', 'icon' => 'receipt', 'color' => 'emerald', 'route' => 'bookstore.index']" />
        </div>
        <div class="grid gap-4 xl:grid-cols-[1fr_360px]">
            <section class="dashboard-card p-0"><div class="border-b border-slate-100 p-4"><h2 class="text-base font-semibold text-slate-950">Low Stock Products</h2></div><div class="overflow-x-auto"><table class="table-compact min-w-[720px]"><thead><tr><th>Product</th><th>Campus</th><th>Stock</th><th>Reorder</th><th>Status</th><th class="text-right">Action</th></tr></thead><tbody>@forelse($lowStockProducts as $product)<tr><td><div class="font-semibold text-slate-950">{{ $product->name }}</div><div class="text-xs text-slate-500">{{ $product->sku ?: 'No SKU' }}</div></td><td>{{ $product->campus?->name ?? 'Unassigned' }}</td><td class="font-semibold">{{ number_format($product->stock_quantity) }}</td><td>{{ number_format($product->reorder_level) }}</td><td><x-status-badge :status="Str::headline($product->status)" /></td><td class="text-right"><a href="{{ route('bookstore.products.edit', $product) }}" class="text-sm font-semibold text-violet-600">Edit</a></td></tr>@empty<tr><td colspan="6" class="px-4 py-12"><x-empty-state icon="boxes" title="No low stock products" message="Products above reorder level will stay out of this list." /></td></tr>@endforelse</tbody></table></div></section>
            <aside class="space-y-4"><section class="dashboard-card"><h2 class="mb-4 text-base font-semibold text-slate-950">Category Value</h2><div class="space-y-3">@forelse($categoryRows as $row)<div class="flex justify-between gap-3 text-sm"><span class="truncate text-slate-600">{{ $row['label'] }} <span class="text-xs text-slate-400">({{ $row['products'] }})</span></span><span class="font-semibold">{{ $currency }} {{ number_format($row['value'], 2) }}</span></div>@empty<div class="text-sm text-slate-500">No category value yet.</div>@endforelse</div></section><section class="dashboard-card"><h2 class="mb-4 text-base font-semibold text-slate-950">Recent Orders</h2><div class="space-y-3">@forelse($recentOrders as $order)<div class="rounded-lg border border-slate-100 p-3 text-sm"><div class="flex justify-between gap-3"><span class="font-semibold text-slate-950">{{ $order->order_number }}</span><span>{{ $order->currency }} {{ number_format((float) $order->total_amount, 2) }}</span></div><div class="mt-1 text-xs text-slate-500">{{ $order->ordered_at?->format('M d, Y') }} · {{ $order->member ? $order->member->first_name.' '.$order->member->last_name : 'Walk-in' }}</div></div>@empty<div class="text-sm text-slate-500">No orders yet.</div>@endforelse</div></section></aside>
        </div>
    </div>
</x-app-layout>
