@php
    $template = $settings['template'] ?? 'modern';
    $sections = $page->sections ?? ['hero', 'welcome', 'services', 'events', 'ministries', 'giving', 'contact'];
    $logo = $settings['logo_url'] ?? null;
    $font = $settings['font'] ?? 'Manrope';
@endphp
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $page->seo_title ?: $settings['site_name'] }}</title>
    <meta name="description" content="{{ $page->seo_description ?: ($settings['seo_description'] ?: $settings['tagline']) }}">
    <style>
        :root { --primary: {{ $settings['primary_color'] }}; --accent: {{ $settings['accent_color'] }}; --ink:#18212f; --muted:#657084; --paper:#fbfaf8; --font:'{{ $font }}', system-ui, sans-serif; }
        * { box-sizing:border-box; } body { margin:0; color:var(--ink); background:var(--paper); font-family:var(--font); } a { color:inherit; text-decoration:none; }
        .site-shell { min-height:100vh; overflow:hidden; } .wrap { width:min(1160px, calc(100% - 40px)); margin:auto; } .nav { display:flex; align-items:center; justify-content:space-between; gap:24px; padding:24px 0; }
        .brand { display:flex; align-items:center; gap:12px; font-weight:800; letter-spacing:-.03em; } .brand-mark { display:grid; place-items:center; width:42px; height:42px; border-radius:14px; color:#fff; background:var(--primary); overflow:hidden; } .brand-mark img { width:100%; height:100%; object-fit:cover; } .brand small { display:block; color:var(--muted); font-size:10px; font-weight:700; letter-spacing:.12em; text-transform:uppercase; }
        .nav-links { display:flex; gap:24px; color:var(--muted); font-size:13px; font-weight:700; } .nav-links a:hover { color:var(--primary); } .nav-cta, .button { display:inline-flex; align-items:center; justify-content:center; gap:8px; border-radius:999px; padding:12px 18px; background:var(--primary); color:white; font-size:13px; font-weight:800; box-shadow:0 12px 25px rgb(24 33 47 / 12%); }
        .hero { position:relative; padding:74px 0 100px; background:radial-gradient(circle at 90% 5%, color-mix(in srgb, var(--accent) 26%, transparent), transparent 34%), linear-gradient(135deg, color-mix(in srgb, var(--primary) 12%, white), transparent 62%); } .hero:after { position:absolute; content:''; width:360px; height:360px; border-radius:50%; right:-150px; bottom:-210px; background:color-mix(in srgb, var(--accent) 24%, transparent); filter:blur(4px); }
        .hero-grid { display:grid; grid-template-columns:1.1fr .9fr; align-items:center; gap:70px; } .eyebrow { color:var(--primary); font-size:12px; font-weight:900; letter-spacing:.18em; text-transform:uppercase; } h1 { max-width:680px; margin:16px 0; font-size:clamp(42px, 6vw, 76px); line-height:.98; letter-spacing:-.075em; } .hero p { max-width:570px; color:var(--muted); font-size:18px; line-height:1.75; } .hero-actions { display:flex; flex-wrap:wrap; gap:12px; margin-top:30px; } .button.secondary { background:#fff; color:var(--ink); }
        .visual { min-height:390px; position:relative; border-radius:38px; background:linear-gradient(150deg, color-mix(in srgb, var(--primary) 88%, black), color-mix(in srgb, var(--primary) 55%, var(--accent))); box-shadow:0 26px 70px rgb(24 33 47 / 22%); transform:rotate(2deg); } .visual-card { position:absolute; left:28px; right:28px; bottom:28px; padding:22px; border-radius:24px; background:rgb(255 255 255 / 88%); backdrop-filter:blur(10px); } .visual-card strong { display:block; font-size:19px; } .visual-card span { display:block; margin-top:6px; color:var(--muted); font-size:12px; line-height:1.6; }
        .section { padding:92px 0; } .section.alt { background:#fff; } .section-heading { max-width:700px; margin-bottom:38px; } .kicker { color:var(--accent); font-size:12px; font-weight:900; letter-spacing:.17em; text-transform:uppercase; } h2 { margin:10px 0; font-size:clamp(30px, 4vw, 52px); line-height:1.03; letter-spacing:-.06em; } .lead { color:var(--muted); font-size:17px; line-height:1.75; }
        .welcome-grid { display:grid; grid-template-columns:.8fr 1.2fr; gap:60px; align-items:start; } .quote { border-left:4px solid var(--accent); padding:10px 0 10px 24px; font-size:20px; font-weight:700; line-height:1.5; } .cards { display:grid; grid-template-columns:repeat(3,1fr); gap:16px; } .card { padding:24px; border:1px solid #edf0f3; border-radius:24px; background:#fff; } .card strong { display:block; font-size:16px; } .card p { color:var(--muted); font-size:13px; line-height:1.65; }
        .event-card { display:flex; align-items:center; gap:18px; } .date { display:grid; place-items:center; min-width:58px; height:58px; border-radius:18px; background:color-mix(in srgb, var(--primary) 10%, white); color:var(--primary); font-weight:900; text-align:center; } .date b { display:block; font-size:20px; line-height:1; } .date span { display:block; font-size:9px; text-transform:uppercase; }
        .cta { border-radius:32px; padding:48px; color:white; background:linear-gradient(120deg, var(--primary), color-mix(in srgb, var(--primary) 56%, var(--accent))); } .cta p { max-width:620px; color:rgb(255 255 255 / 75%); line-height:1.7; } .cta .button { background:white; color:var(--primary); }
        footer { padding:40px 0; border-top:1px solid #e8eaed; color:var(--muted); font-size:12px; } .footer-grid { display:flex; align-items:center; justify-content:space-between; gap:20px; } .preview { position:fixed; z-index:20; top:14px; right:14px; border-radius:999px; padding:9px 13px; color:#fff; background:#111827; font-size:11px; font-weight:800; }
        .classic .hero { background:#f3ede3; } .classic h1, .classic h2 { font-family:Georgia, serif; letter-spacing:-.04em; } .classic .visual { border-radius:12px; transform:none; } .community .hero { background:linear-gradient(135deg, #eefbf5, #fff); } .community .card { border-radius:16px; } .community .visual { border-radius:50px 16px 50px 16px; transform:none; }
        @media (max-width:800px) { .wrap { width:min(100% - 28px, 680px); } .nav-links { display:none; } .hero { padding:48px 0 74px; } .hero-grid, .welcome-grid { grid-template-columns:1fr; gap:36px; } .visual { min-height:270px; } .section { padding:64px 0; } .cards { grid-template-columns:1fr; } .cta { padding:30px; } .footer-grid { align-items:flex-start; flex-direction:column; } }
    </style>
</head>
<body class="{{ $template }}">
    <div class="site-shell">
        @if ($preview)<div class="preview">Preview mode · unpublished changes are visible only to you</div>@endif
        <header class="wrap nav">
            <a class="brand" href="{{ route('website.public', ['church' => $church->slug]) }}"><span class="brand-mark">@if ($logo)<img src="{{ str_starts_with($logo, 'http') ? $logo : asset('storage/'.ltrim($logo, '/')) }}" alt="">@else<span>✦</span>@endif</span><span>{{ $settings['site_name'] }}<small>{{ $settings['tagline'] }}</small></span></a>
            <nav class="nav-links">@foreach ($navigation as $item)<a href="{{ $item['url'] }}">{{ $item['label'] }}</a>@endforeach</nav>
            <a class="nav-cta" href="{{ $settings['hero_button_url'] ?: '#visit' }}">{{ $settings['hero_button_label'] ?: 'Plan a visit' }}</a>
        </header>

        @if ($page->slug === 'home' || in_array('hero', $sections, true))
            <section class="hero"><div class="wrap hero-grid"><div><div class="eyebrow">{{ $settings['hero_eyebrow'] }}</div><h1>{{ $settings['hero_heading'] }}</h1><p>{{ $settings['hero_body'] }}</p><div class="hero-actions"><a class="button" href="{{ $settings['hero_button_url'] ?: '#visit' }}">{{ $settings['hero_button_label'] ?: 'Plan your visit' }} →</a><a class="button secondary" href="#community">Meet our community</a></div></div><div class="visual"><div class="visual-card"><strong>{{ $church->name }}</strong><span>Come as you are. Leave with hope. We are saving you a seat this Sunday.</span></div></div></div></section>
        @endif

        @if ($page->body && $page->slug !== 'home')<section class="section"><div class="wrap section-heading"><div class="kicker">{{ $page->title }}</div><div class="lead" style="white-space:pre-line">{{ $page->body }}</div></div></section>@endif
        @if (in_array('welcome', $sections, true) && $page->slug === 'home')<section class="section"><div class="wrap welcome-grid"><div class="section-heading"><div class="kicker">Our family</div><h2>{{ $settings['welcome_heading'] }}</h2></div><div><div class="quote">{{ $settings['welcome_body'] }}</div><p class="lead" style="margin-top:24px">There is room at the table, room to ask questions, and room to grow. Start with one simple step: come and see.</p></div></div></section>@endif
        @if (in_array('services', $sections, true))<section id="visit" class="section alt"><div class="wrap"><div class="section-heading"><div class="kicker">Gather with us</div><h2>There is a place for you this Sunday.</h2><p class="lead">Come early for coffee, stay after for conversation, and worship with a community that wants to know your name.</p></div><div class="cards"><div class="card"><strong>Sunday Worship</strong><p>Every Sunday · 9:00 AM & 11:00 AM</p></div><div class="card"><strong>Midweek Community</strong><p>Wednesday · 6:30 PM</p></div><div class="card"><strong>Kids & Students</strong><p>Safe, joyful spaces for every age.</p></div></div></div></section>@endif
        @if (in_array('events', $sections, true) && $events->isNotEmpty())<section class="section"><div class="wrap"><div class="section-heading"><div class="kicker">Coming up</div><h2>Find your people.</h2></div><div class="cards">@foreach ($events as $event)<div class="card event-card"><div class="date"><div><b>{{ $event->starts_at->format('d') }}</b><span>{{ $event->starts_at->format('M') }}</span></div></div><div><strong>{{ $event->title }}</strong><p>{{ $event->venue ?: 'At our church' }} · {{ $event->starts_at->format('g:i A') }}</p></div></div>@endforeach</div></div></section>@endif
        @if (in_array('ministries', $sections, true) && $ministries->isNotEmpty())<section id="community" class="section alt"><div class="wrap"><div class="section-heading"><div class="kicker">Life together</div><h2>Grow through community.</h2></div><div class="cards">@foreach ($ministries as $ministry)<div class="card"><strong>{{ $ministry->name }}</strong><p>{{ $ministry->description ?: 'A place to connect, serve, and make a difference together.' }}</p></div>@endforeach</div></div></section>@endif
        @if (in_array('locations', $sections, true) && $campuses->isNotEmpty())<section id="locations" class="section"><div class="wrap"><div class="section-heading"><div class="kicker">Our locations</div><h2>Find a place to gather.</h2><p class="lead">Visit one of our campuses and find a church family near you.</p></div><div class="cards">@foreach ($campuses as $campus)<div class="card"><strong>{{ $campus->name }}</strong><p>{{ collect([$campus->city, $campus->country])->filter()->join(', ') }}</p><p>{{ $campus->address ?: 'Details available from the church office.' }}</p></div>@endforeach</div></div></section>@endif
        @if (in_array('giving', $sections, true))<section class="section"><div class="wrap"><div class="cta"><div class="kicker" style="color:var(--accent)">Make an impact</div><h2>Generosity changes lives.</h2><p>Your gifts help us care for people, strengthen families, and bring hope beyond our walls.</p><a class="button" href="{{ url('/give') }}">Give online →</a></div></div></section>@endif
        @if (in_array('contact', $sections, true))<section id="contact" class="section alt"><div class="wrap welcome-grid"><div class="section-heading"><div class="kicker">Plan your visit</div><h2>We would love to meet you.</h2></div><div><p class="lead">{{ $settings['contact_address'] ?: 'Come find us at our church campus.' }}</p>@if ($settings['contact_email'])<p class="lead"><a href="mailto:{{ $settings['contact_email'] }}">{{ $settings['contact_email'] }}</a></p>@endif @if ($settings['contact_phone'])<p class="lead"><a href="tel:{{ $settings['contact_phone'] }}">{{ $settings['contact_phone'] }}</a></p>@endif</div></div></section>@endif
        <footer><div class="wrap footer-grid"><div>© {{ now()->year }} {{ $settings['site_name'] }}. All rights reserved.</div><div>Built with EcclesiaOS · <a href="{{ route('home') }}">Church management, beautifully connected.</a></div></div></footer>
        @if (in_array('sermons', $sections, true) && $sermons->isNotEmpty())<section id="sermons" class="section"><div class="wrap"><div class="section-heading"><div class="kicker">Messages for the journey</div><h2>Listen, learn, and live it out.</h2></div><div class="cards">@foreach ($sermons as $sermon)<a class="card" href="{{ $sermon->video_url ?: ($sermon->audio_url ?: '#sermons') }}" @if ($sermon->video_url || $sermon->audio_url) target="_blank" rel="noreferrer" @endif><strong>{{ $sermon->title }}</strong><p>{{ $sermon->speaker ?: 'Our teaching team' }} - {{ $sermon->preached_at?->format('M d, Y') ?: 'Recent message' }}</p><p>{{ $sermon->summary ?: ($sermon->scripture ?: 'A message from our church family.') }}</p></a>@endforeach</div></div></section>@endif
        @if (in_array('store', $sections, true) && $products->isNotEmpty())<section id="store" class="section alt"><div class="wrap"><div class="section-heading"><div class="kicker">Church store</div><h2>Resources for your next step.</h2><p class="lead">These products are connected directly to the church bookstore catalog.</p></div><div class="cards">@foreach ($products as $product)<article class="card"><strong>{{ $product->name }}</strong><p>{{ $product->author ?: ($product->category ?: 'Church resource') }} - {{ $product->format ?: 'Available now' }}</p><p class="font-semibold">{{ $church->currency }} {{ number_format((float) $product->price, 2) }}</p>@if ($product->digital_url)<a href="{{ $product->digital_url }}" target="_blank" rel="noreferrer" class="font-bold text-violet-700">Open digital resource -></a>@endif</article>@endforeach</div></div></section>@endif
    </div>
</body>
</html>
