<x-app-layout title="Add Child or Youth" :breadcrumbs="$breadcrumbs">
    <div class="mx-auto max-w-5xl space-y-5"><div class="flex items-center justify-between gap-3"><div><h1 class="text-2xl font-semibold text-slate-950">Add Child or Youth</h1><p class="text-sm text-slate-500">Create guardian, consent, check-in, and care details.</p></div><a href="{{ route('children-youth.index') }}" class="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700"><i data-lucide="list" class="size-4"></i>Register</a></div>
        @if ($errors->any())<div class="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm font-medium text-rose-700">{{ $errors->first() }}</div>@endif
        <section class="dashboard-card"><form method="POST" action="{{ route('children-youth.store') }}" class="grid gap-4 md:grid-cols-2">@csrf
            <label class="space-y-1 text-sm font-medium text-slate-700">First Name<input name="first_name" value="{{ old('first_name') }}" required class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Last Name<input name="last_name" value="{{ old('last_name') }}" required class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Linked Member<select name="member_id" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="">Not linked</option>@foreach($members as $member)<option value="{{ $member->id }}" @selected(old('member_id') == $member->id)>{{ $member->first_name }} {{ $member->last_name }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Guardian Member<select name="guardian_member_id" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="">Not linked</option>@foreach($members as $member)<option value="{{ $member->id }}" @selected(old('guardian_member_id') == $member->id)>{{ $member->first_name }} {{ $member->last_name }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Date of Birth<input name="date_of_birth" type="date" value="{{ old('date_of_birth') }}" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Age Group<select name="age_group" required class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">@foreach($ageGroups as $group)<option value="{{ $group }}" @selected(old('age_group', 'elementary') === $group)>{{ Str::headline($group) }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Campus<select name="campus_id" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="">Unassigned</option>@foreach($campuses as $campus)<option value="{{ $campus->id }}" @selected(old('campus_id') == $campus->id)>{{ $campus->name }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Guardian Name<input name="guardian_name" value="{{ old('guardian_name') }}" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Guardian Phone<input name="guardian_phone" value="{{ old('guardian_phone') }}" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Pickup Code<input name="pickup_code" value="{{ old('pickup_code') }}" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Consent<select name="consent_status" required class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">@foreach($consentStatuses as $status)<option value="{{ $status }}" @selected(old('consent_status', 'pending') === $status)>{{ Str::headline($status) }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Check-in<select name="check_in_status" required class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">@foreach($checkInStatuses as $status)<option value="{{ $status }}" @selected(old('check_in_status', 'not_checked_in') === $status)>{{ Str::headline($status) }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Status<select name="status" required class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">@foreach($statuses as $status)<option value="{{ $status }}" @selected(old('status', 'active') === $status)>{{ Str::headline($status) }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700 md:col-span-2">Medical Notes<textarea name="medical_notes" rows="4" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">{{ old('medical_notes') }}</textarea></label>
            <div class="md:col-span-2 flex justify-end gap-2"><a href="{{ route('children-youth.index') }}" class="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700">Cancel</a><button class="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white"><i data-lucide="plus" class="size-4"></i>Add Record</button></div>
        </form></section>
    </div>
</x-app-layout>
