<x-app-layout title="Edit Child or Youth" :breadcrumbs="$breadcrumbs">
    <div class="mx-auto max-w-5xl space-y-5"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div class="min-w-0"><h1 class="text-2xl font-semibold text-slate-950">Edit Child or Youth</h1><p class="text-sm text-slate-500">{{ $record->first_name }} {{ $record->last_name }}</p></div><a href="{{ route('children-youth.index') }}" class="inline-flex w-full items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 sm:w-auto"><i data-lucide="list" class="size-4"></i>Register</a></div>
        @if ($errors->any())<div class="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm font-medium text-rose-700">{{ $errors->first() }}</div>@endif
        <section class="dashboard-card"><form method="POST" action="{{ route('children-youth.update', $record) }}" class="grid gap-4 md:grid-cols-2">@csrf @method('PUT')
            <label class="space-y-1 text-sm font-medium text-slate-700">First Name<input name="first_name" value="{{ old('first_name', $record->first_name) }}" required class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Last Name<input name="last_name" value="{{ old('last_name', $record->last_name) }}" required class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Linked Member<select name="member_id" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="">Not linked</option>@foreach($members as $member)<option value="{{ $member->id }}" @selected((string) old('member_id', $record->member_id) === (string) $member->id)>{{ $member->first_name }} {{ $member->last_name }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Guardian Member<select name="guardian_member_id" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="">Not linked</option>@foreach($members as $member)<option value="{{ $member->id }}" @selected((string) old('guardian_member_id', $record->guardian_member_id) === (string) $member->id)>{{ $member->first_name }} {{ $member->last_name }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Date of Birth<input name="date_of_birth" type="date" value="{{ old('date_of_birth', $record->date_of_birth?->format('Y-m-d')) }}" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Age Group<select name="age_group" required class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">@foreach($ageGroups as $group)<option value="{{ $group }}" @selected(old('age_group', $record->age_group) === $group)>{{ Str::headline($group) }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Campus<select name="campus_id" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="">Unassigned</option>@foreach($campuses as $campus)<option value="{{ $campus->id }}" @selected((string) old('campus_id', $record->campus_id) === (string) $campus->id)>{{ $campus->name }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Guardian Name<input name="guardian_name" value="{{ old('guardian_name', $record->guardian_name) }}" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Guardian Phone<input name="guardian_phone" value="{{ old('guardian_phone', $record->guardian_phone) }}" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Pickup Code<input name="pickup_code" value="{{ old('pickup_code', $record->pickup_code) }}" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Consent<select name="consent_status" required class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">@foreach($consentStatuses as $status)<option value="{{ $status }}" @selected(old('consent_status', $record->consent_status) === $status)>{{ Str::headline($status) }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Check-in<select name="check_in_status" required class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">@foreach($checkInStatuses as $status)<option value="{{ $status }}" @selected(old('check_in_status', $record->check_in_status) === $status)>{{ Str::headline($status) }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700">Status<select name="status" required class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">@foreach($statuses as $status)<option value="{{ $status }}" @selected(old('status', $record->status) === $status)>{{ Str::headline($status) }}</option>@endforeach</select></label>
            <label class="space-y-1 text-sm font-medium text-slate-700 md:col-span-2">Medical Notes<textarea name="medical_notes" rows="4" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">{{ old('medical_notes', $record->medical_notes) }}</textarea></label>
            <div class="md:col-span-2 flex justify-between gap-2"><button form="delete-record" class="rounded-lg border border-rose-200 px-4 py-2.5 text-sm font-semibold text-rose-700">Archive</button><div class="flex gap-2"><a href="{{ route('children-youth.index') }}" class="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700">Cancel</a><button class="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white"><i data-lucide="save" class="size-4"></i>Save Changes</button></div></div>
        </form><form id="delete-record" method="POST" action="{{ route('children-youth.destroy', $record) }}" class="hidden">@csrf @method('DELETE')</form></section>
    </div>
</x-app-layout>
