<x-app-layout title="Children & Youth Overview" :breadcrumbs="$breadcrumbs">
    <div class="space-y-5">
        <div class="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div class="flex items-center gap-4"><div class="grid size-14 place-items-center rounded-xl bg-sky-100 text-sky-600"><i data-lucide="baby" class="size-7"></i></div><div><h1 class="text-2xl font-semibold text-slate-950">Children & Youth Overview</h1><p class="text-sm text-slate-500">Check-in, consent, age groups, guardian records, and care notes.</p></div></div><div class="flex flex-wrap gap-2"><a href="{{ route('children-youth.index') }}" class="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700"><i data-lucide="list" class="size-4"></i>Register</a><a href="{{ route('children-youth.create') }}" class="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white"><i data-lucide="plus" class="size-4"></i>Add Record</a></div></div>
        <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
            <x-stat-card :metric="['label' => 'Active Records', 'value' => number_format($stats['total']), 'change' => null, 'period' => 'children and youth', 'icon' => 'users', 'color' => 'purple', 'route' => 'children-youth.index']" />
            <x-stat-card :metric="['label' => 'Checked In', 'value' => number_format($stats['checked_in']), 'change' => null, 'period' => 'current status', 'icon' => 'badge-check', 'color' => 'emerald', 'route' => 'children-youth.index']" />
            <x-stat-card :metric="['label' => 'Consent Pending', 'value' => number_format($stats['consent_pending']), 'change' => null, 'period' => 'needs follow-up', 'icon' => 'file-warning', 'color' => 'orange', 'route' => 'children-youth.index']" />
            <x-stat-card :metric="['label' => 'Medical Notes', 'value' => number_format($stats['medical_notes']), 'change' => null, 'period' => 'care alerts', 'icon' => 'heart-pulse', 'color' => 'rose', 'route' => 'children-youth.index']" />
        </div>
        <div class="grid gap-4 xl:grid-cols-[1fr_360px]">
            <section class="dashboard-card p-0"><div class="border-b border-slate-100 p-4"><h2 class="text-base font-semibold text-slate-950">Recent Records</h2></div><div class="overflow-x-auto"><table class="table-compact min-w-[760px]"><thead><tr><th>Name</th><th>Age Group</th><th>Guardian</th><th>Consent</th><th>Check-in</th><th class="text-right">Action</th></tr></thead><tbody>@forelse($recentRecords as $record)<tr><td><div class="font-semibold text-slate-950">{{ $record->first_name }} {{ $record->last_name }}</div><div class="text-xs text-slate-500">{{ $record->campus?->name ?? 'Unassigned' }}</div></td><td>{{ Str::headline($record->age_group) }}</td><td>{{ $record->guardian ? $record->guardian->first_name.' '.$record->guardian->last_name : ($record->guardian_name ?: 'Not recorded') }}</td><td><x-status-badge :status="Str::headline($record->consent_status)" /></td><td><x-status-badge :status="Str::headline($record->check_in_status)" /></td><td class="text-right"><a href="{{ route('children-youth.edit', $record) }}" class="text-sm font-semibold text-violet-600">Edit</a></td></tr>@empty<tr><td colspan="6" class="px-4 py-12"><x-empty-state icon="baby" title="No records yet" message="Add the first child or youth record to begin." /></td></tr>@endforelse</tbody></table></div></section>
            <aside class="space-y-4"><section class="dashboard-card"><h2 class="mb-4 text-base font-semibold text-slate-950">Age Groups</h2><div class="space-y-3">@forelse($ageRows as $row)<div class="grid grid-cols-[1fr_auto] gap-2 text-sm"><span class="text-slate-600">{{ $row['label'] }}</span><span class="font-semibold">{{ $row['value'] }}</span><span class="col-span-2 h-1.5 rounded-full bg-slate-100"><span class="block h-full rounded-full bg-sky-500" style="width: {{ $row['percent'] }}%"></span></span></div>@empty<div class="text-sm text-slate-500">No age data yet.</div>@endforelse</div></section><section class="dashboard-card"><h2 class="mb-4 text-base font-semibold text-slate-950">Consent</h2><div class="space-y-3">@foreach($consentRows as $row)<div class="grid grid-cols-[1fr_auto] gap-2 text-sm"><span class="text-slate-600">{{ $row['label'] }}</span><span class="font-semibold">{{ $row['value'] }}</span><span class="col-span-2 h-1.5 rounded-full bg-slate-100"><span class="block h-full rounded-full bg-violet-500" style="width: {{ $row['percent'] }}%"></span></span></div>@endforeach</div></section></aside>
        </div>
    </div>
</x-app-layout>
