<x-app-layout title="Sermons & Media" :breadcrumbs="$breadcrumbs">
    <div class="space-y-5">
        <div class="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><div class="mb-2 inline-flex items-center gap-2 rounded-full bg-orange-50 px-3 py-1 text-xs font-bold uppercase tracking-[0.14em] text-orange-700"><i data-lucide="monitor-play" class="size-3.5"></i>Connected content</div><h1 class="text-2xl font-semibold text-slate-950">Sermons & Media</h1><p class="mt-1 text-sm text-slate-500">Publish sermon recordings once. Website Studio automatically reads the published library.</p></div><a href="{{ route('website-studio.index') }}" class="inline-flex items-center gap-2 rounded-lg border border-violet-200 bg-white px-4 py-2.5 text-sm font-bold text-violet-700 hover:bg-violet-50"><i data-lucide="panels-top-left" class="size-4"></i>Open Website Studio</a></div>
        @if (session('status'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ session('status') }}</div>@endif
        @if ($errors->any())<div class="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{{ $errors->first() }}</div>@endif
        <div class="grid gap-5 xl:grid-cols-[390px_1fr]">
            <section class="dashboard-card h-fit"><h2 class="text-base font-bold text-slate-950">Add sermon</h2><p class="mt-1 text-sm text-slate-500">Drafts stay private. Published sermons appear in the public sermon section.</p><form method="POST" action="{{ route('sermons.store') }}" enctype="multipart/form-data" class="mt-5 space-y-3">@csrf
                <label><span class="field-label">Title</span><input name="title" required class="field-input" placeholder="The grace to begin again"></label>
                <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-1"><label><span class="field-label">Speaker</span><input name="speaker" class="field-input" placeholder="Pastor name"></label><label><span class="field-label">Scripture</span><input name="scripture" class="field-input" placeholder="John 3:16"></label></div>
                <label><span class="field-label">Date preached</span><input type="date" name="preached_at" class="field-input"></label><label><span class="field-label">Summary</span><textarea name="summary" rows="4" class="field-input" placeholder="Short description for the website"></textarea></label>
                <label><span class="field-label">Video URL <span class="font-normal text-slate-400">(optional)</span></span><input type="url" name="video_url" class="field-input" placeholder="https://youtube.com/..."></label><label><span class="field-label">Upload video <span class="font-normal text-slate-400">(optional)</span></span><input type="file" name="video_file" accept="video/mp4,video/webm,video/ogg" class="field-input"></label><label><span class="field-label">Audio URL <span class="font-normal text-slate-400">(optional)</span></span><input type="url" name="audio_url" class="field-input" placeholder="https://..."></label><label><span class="field-label">Thumbnail URL <span class="font-normal text-slate-400">(optional)</span></span><input type="url" name="thumbnail_url" class="field-input" placeholder="https://..."></label><label><span class="field-label">Upload thumbnail image <span class="font-normal text-slate-400">(optional)</span></span><input type="file" name="thumbnail_file" accept="image/*" class="field-input"></label>
                <select name="status" class="field-input"><option value="published">Publish</option><option value="draft">Save draft</option></select><button class="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white hover:bg-violet-700"><i data-lucide="plus" class="size-4"></i>Add sermon</button>
            </form></section>
            <section class="dashboard-card p-0 overflow-hidden"><div class="border-b border-slate-100 p-4"><h2 class="text-base font-bold text-slate-950">Sermon library <span class="ml-1 text-xs font-normal text-slate-400">{{ $sermons->count() }} records</span></h2></div><div class="divide-y divide-slate-100">@forelse ($sermons as $sermon)<form method="POST" action="{{ route('sermons.update', $sermon) }}" class="grid gap-3 p-4 lg:grid-cols-[1fr_150px_120px_auto] lg:items-end">@csrf @method('PUT')<div class="min-w-0"><input name="title" value="{{ $sermon->title }}" class="field-input font-bold"><div class="mt-2 grid gap-2 sm:grid-cols-2"><input name="speaker" value="{{ $sermon->speaker }}" placeholder="Speaker" class="field-input"><input name="scripture" value="{{ $sermon->scripture }}" placeholder="Scripture" class="field-input"></div><textarea name="summary" rows="2" class="field-input mt-2" placeholder="Summary">{{ $sermon->summary }}</textarea><div class="mt-2 grid gap-2 sm:grid-cols-3"><input name="video_url" value="{{ $sermon->video_url }}" placeholder="Video URL" class="field-input"><input name="audio_url" value="{{ $sermon->audio_url }}" placeholder="Audio URL" class="field-input"><input name="thumbnail_url" value="{{ $sermon->thumbnail_url }}" placeholder="Thumbnail URL" class="field-input"></div></div><label><span class="field-label">Date</span><input type="date" name="preached_at" value="{{ $sermon->preached_at?->format('Y-m-d') }}" class="field-input"></label><select name="status" class="field-input"><option value="published" @selected($sermon->status === 'published')>Published</option><option value="draft" @selected($sermon->status === 'draft')>Draft</option></select><div class="flex gap-2"><button class="inline-flex items-center gap-1.5 rounded-lg bg-violet-50 px-3 py-2 text-xs font-bold text-violet-700 hover:bg-violet-100"><i data-lucide="save" class="size-3.5"></i>Save</button><button type="submit" form="delete-sermon-{{ $sermon->id }}" class="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><i data-lucide="archive" class="size-4"></i></button></div></form><form id="delete-sermon-{{ $sermon->id }}" method="POST" action="{{ route('sermons.destroy', $sermon) }}">@csrf @method('DELETE')</form>@empty<div class="p-14 text-center text-sm text-slate-500">No sermons yet. Add one to connect the sermon library to your public website.</div>@endforelse</div></section>
        </div>
    </div>
    <style>.field-label{display:block;margin-bottom:.4rem;font-size:.72rem;font-weight:700;color:#475569}.field-input{display:block;width:100%;border-radius:.7rem;border:1px solid #e2e8f0;background:#fff;padding:.65rem .75rem;font-size:.875rem;color:#0f172a;outline:none}.field-input:focus{border-color:#8b5cf6;box-shadow:0 0 0 3px rgb(139 92 246 / .12)}</style>
</x-app-layout>
