<x-app-layout title="Sermons & Media" :breadcrumbs="$breadcrumbs">
    <div class="space-y-6">
        <div class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
            <div><p class="text-xs font-black uppercase tracking-[.18em] text-violet-600">Connected content</p><h1 class="mt-2 text-3xl font-semibold tracking-tight text-slate-950">Sermons & Media</h1><p class="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Manage every sermon published to your church website from one focused library.</p></div>
            <div class="flex flex-wrap gap-2"><a href="{{ route('website-studio.index') }}" class="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-700 hover:bg-slate-50"><i data-lucide="panels-top-left" class="size-4"></i>Website Studio</a><a href="{{ route('sermons.create') }}" class="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-3 text-sm font-bold text-white shadow-lg shadow-violet-200 hover:bg-violet-700"><i data-lucide="plus" class="size-4"></i>Create sermon</a></div>
        </div>
        @if (session('status'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ session('status') }}</div>@endif
        @if ($errors->any())<div class="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{{ $errors->first() }}</div>@endif
        <div class="grid gap-4 sm:grid-cols-3"><div class="dashboard-card"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Total sermons</p><p class="mt-2 text-3xl font-black text-slate-950">{{ $sermons->count() }}</p></div><div class="dashboard-card"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Published</p><p class="mt-2 text-3xl font-black text-emerald-600">{{ $sermons->where('status', 'published')->count() }}</p></div><div class="dashboard-card"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Drafts</p><p class="mt-2 text-3xl font-black text-amber-600">{{ $sermons->where('status', 'draft')->count() }}</p></div></div>
        <section class="dashboard-card overflow-hidden p-0"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 class="font-bold text-slate-950">Sermon library</h2><p class="mt-1 text-xs text-slate-500">{{ $sermons->count() }} sermon records</p></div><span class="rounded-full bg-violet-50 px-3 py-1 text-xs font-bold text-violet-700">All sermons</span></div>
            <div class="divide-y divide-slate-100">
                @forelse ($sermons as $sermon)
                    <div class="flex flex-col gap-4 p-5 transition hover:bg-slate-50 sm:flex-row sm:items-center">
                        @if ($sermon->thumbnail_url)<img src="{{ str_starts_with($sermon->thumbnail_url, 'http') ? $sermon->thumbnail_url : asset('storage/'.ltrim($sermon->thumbnail_url, '/')) }}" alt="{{ $sermon->title }}" class="h-20 w-32 rounded-xl object-cover">@else<div class="grid h-20 w-32 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-violet-600 to-slate-950 text-2xl text-white">▶</div>@endif
                        <div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><h3 class="truncate font-bold text-slate-950">{{ $sermon->title }}</h3><span class="rounded-full px-2 py-1 text-[10px] font-black uppercase tracking-wide {{ $sermon->status === 'published' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700' }}">{{ $sermon->status }}</span></div><p class="mt-1 text-sm text-slate-500">{{ $sermon->speaker ?: 'Teaching team' }}{{ $sermon->preached_at ? ' · '.$sermon->preached_at->format('M j, Y') : '' }}</p><p class="mt-1 line-clamp-1 text-xs text-slate-400">{{ $sermon->summary ?: ($sermon->scripture ?: 'No summary added') }}</p></div>
                        <div class="flex shrink-0 gap-2"><a href="{{ route('sermons.edit', $sermon) }}" class="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700 hover:bg-white"><i data-lucide="pencil" class="size-3.5"></i>Edit</a><form method="POST" action="{{ route('sermons.destroy', $sermon) }}" onsubmit="return confirm('Archive this sermon?')">@csrf @method('DELETE')<button class="inline-flex items-center gap-2 rounded-lg border border-rose-100 px-3 py-2 text-xs font-bold text-rose-600 hover:bg-rose-50"><i data-lucide="archive" class="size-3.5"></i>Archive</button></form></div>
                    </div>
                @empty
                    <div class="p-16 text-center"><span class="mx-auto grid size-14 place-items-center rounded-2xl bg-violet-50 text-2xl text-violet-600">▶</span><h2 class="mt-4 font-bold text-slate-950">No sermons yet</h2><p class="mt-1 text-sm text-slate-500">Create your first sermon to connect it to the public website.</p><a href="{{ route('sermons.create') }}" class="mt-5 inline-flex rounded-xl bg-violet-600 px-4 py-3 text-sm font-bold text-white">Create sermon</a></div>
                @endforelse
            </div>
        </section>
    </div>
</x-app-layout>
